function activityQuery(){return{source:val('activitySource'),category:val('activityCategory'),status:val('activityStatus'),limit:val('activityLimit')||'100',cursor:activityPager.cursor||undefined,actor:val('activityActor')||undefined,agent:val('activityAgent')||'all',thread:val('activityThread')||undefined,workspace:val('activityWorkspace')||undefined,type:val('activityType')||undefined,since:val('activitySince')||undefined}}
async function loadActivity(reset=true){if(reset)activityPager.reset();setLoading('activityList','Loading activity...');const data=await api('/api/activity',{query:activityQuery()});state.activityEvents=data.events||[];renderActivity(state.activityEvents);activityPager.render(data.pagination||{})}
function activityWorkspace(e){const active=state.snapshot?.session;return e.workspace||(active?.threadId&&e.threadId===active.threadId?active.workspace:'')}
function activityActorText(e){const a=e.actor||{};return a.label||a.username||a.id||({web:'Web user',telegram:'Telegram user',discord:'Discord user',slack:'Slack user',cli:'CLI',system:'System'}[a.channel]||'System')}
function activityMetaHtml(e){const workspace=activityWorkspace(e);const duration=typeof e.durationMs==='number'?fmtDuration(e.durationMs):'';const actor=activityActorText(e);const parts=[];if(actor)parts.push('User: '+esc(actor));if(e.correlationId)parts.push(uiTraceControls(e.correlationId));if(e.threadId)parts.push(uiCopyButton(e.threadId,'Thread ID copied'));if(workspace)parts.push(esc(workspace));if(duration)parts.push(esc(duration));return parts.join(' | ')}
function activityCell(label,html,cls=''){return '<td data-label="'+attr(label)+'"'+(cls?' class="'+cls+'"':'')+'>'+html+'</td>'}
function activityAgeHtml(e){return '<span class="activity-age" data-activity-age-at="'+attr(e.timestamp||'')+'" title="'+attr(fmtDate(e.timestamp))+'">'+esc(fmtRelativeAgo(e.timestamp))+'</span>'}
function activityStatusClass(status){if(status==='failed'||status==='aborted')return'error';if(status==='queued'||status==='running')return'warn';return''}
function activityContextHtml(e){const workspace=activityWorkspace(e);const duration=typeof e.durationMs==='number'?fmtDuration(e.durationMs):'';const parts=[];if(e.agentId)parts.push('<span class="truncate-cell" title="'+attr(e.agentId)+'">'+esc(e.agentId)+'</span>');if(e.threadId)parts.push('<button type="button" class="copy-id" data-copy-value="'+attr(e.threadId)+'" data-copy-label="Thread ID copied" title="'+attr(e.threadId)+'">'+esc(shortMiddle(e.threadId))+'</button>');if(workspace)parts.push('<span class="truncate-cell" title="'+attr(workspace)+'">'+esc(short(workspace,120))+'</span>');if(duration)parts.push('<span>'+esc(duration)+'</span>');if(e.correlationId)parts.push('<span>CID '+uiCopyButton(e.correlationId,'Correlation ID copied')+'</span>');return parts.length?'<div class="activity-context">'+parts.join('')+'</div>':'-'}
function renderActivityRow(e){const type=[e.category,e.type].filter(Boolean).join(' / ')||'-';const detail=e.prompt||e.detail||'';const status='<span class="chip '+activityStatusClass(e.status)+'">'+esc(e.status||'-')+'</span>';const actions=e.correlationId?'<div class="data-table-actions"><button type="button" class="secondary" data-trace-id="'+attr(e.correlationId)+'">Trace</button></div>':'-';return '<tr>'+activityCell('Time',activityAgeHtml(e),'updated-cell')+activityCell('Source',esc(e.source||'-'))+activityCell('Status',status,'status-cell')+activityCell('Type','<span class="truncate-cell" title="'+attr(type)+'">'+esc(short(type,80))+'</span>','type-cell')+activityCell('User','<span class="truncate-cell" title="'+attr(activityActorText(e))+'">'+esc(short(activityActorText(e),80))+'</span>','user-cell')+activityCell('Context',activityContextHtml(e),'context-cell')+activityCell('Detail','<span class="truncate-cell" title="'+attr(detail)+'">'+esc(short(detail||'-',220))+'</span>','detail-cell')+activityCell('Actions',actions,'actions-cell')+'</tr>'}
function renderActivityTable(events){renderIncrementalTable('activityList',events||[],{key:'activity-table',emptyText:'No activity.',tableClass:'activity-table',tableClassHtml:'class="data-table activity-table"',headHtml:'<tr><th>Time</th><th>Source</th><th>Status</th><th>Type</th><th>User</th><th>Context</th><th>Detail</th><th class="actions-heading">Actions</th></tr>',renderItem:renderActivityRow,initialCount:80,batchSize:80,onDone:bindActivityTable})}
function bindActivityTable(root=document){bindUiCopyButtons(root);bindUiTraceButtons(root);startActivityAgeCounter()}
function renderActivity(events){renderActivityTable(events||[])}
document.getElementById('loadActivityBtn').onclick=()=>loadActivity(true);
document.getElementById('activitySince').onchange=()=>loadActivity(true);
document.getElementById('exportActivityBtn').onclick=()=>{const rows=(state.activityEvents||[]).map(e=>[e.timestamp,e.source,e.category||'',e.status,e.type,activityActorText(e),e.agentId||'',e.threadId||'',activityWorkspace(e),e.prompt||e.detail||''].join('\\t')).join('\\n');const blob=new Blob([rows],{type:'text/tab-separated-values'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='nordrelay-activity.tsv';a.click();URL.revokeObjectURL(a.href)};
function renderTracePlaceholder(){const target=document.getElementById('traceDetail');if(target&&!target.innerHTML)target.innerHTML='<div class="item">Enter a correlation ID or open Trace from Activity/Tasks.</div>'}
async function openTrace(correlationId){document.getElementById('traceCorrelationId').value=correlationId;switchMonitorTab('trace');page('monitor');await loadTrace(correlationId)}
async function loadTrace(correlationId=val('traceCorrelationId')){if(!correlationId){renderTracePlaceholder();return}setLoading('traceDetail','Loading trace...');const data=await api('/api/trace',{query:{correlationId}});renderTrace(data)}
function traceAgeHtml(item){return '<span class="activity-age" data-activity-age-at="'+attr(item.at||'')+'" title="'+attr(fmtDate(item.at))+'">'+esc(fmtRelativeAgo(item.at))+'</span>'}
function traceContextHtml(item){const parts=[];if(item.agentId)parts.push('<span class="truncate-cell" title="'+attr(item.agentId)+'">'+esc(item.agentId)+'</span>');if(item.threadId)parts.push('<button type="button" class="copy-id" data-copy-value="'+attr(item.threadId)+'" data-copy-label="Thread ID copied" title="'+attr(item.threadId)+'">'+esc(shortMiddle(item.threadId))+'</button>');if(item.workspace)parts.push('<span class="truncate-cell" title="'+attr(item.workspace)+'">'+esc(short(item.workspace,120))+'</span>');return parts.length?'<div class="activity-context">'+parts.join('')+'</div>':'-'}
function renderTraceTimelineRow(item){const status='<span class="chip '+activityStatusClass(item.status)+'">'+esc(item.status||'-')+'</span>';const action=item.id?'<div class="data-table-actions"><button type="button" class="secondary" data-copy-value="'+attr(item.id)+'" data-copy-label="Trace event ID copied">Copy ID</button></div>':'-';return '<tr>'+activityCell('Time',traceAgeHtml(item),'updated-cell')+activityCell('Source',esc(item.source||'-'))+activityCell('Status',status,'status-cell')+activityCell('Type','<span class="truncate-cell" title="'+attr(item.type||'')+'">'+esc(short(item.type||'-',80))+'</span>','type-cell')+activityCell('Title','<span class="truncate-cell" title="'+attr(item.title||'')+'">'+esc(short(item.title||'-',120))+'</span>','user-cell')+activityCell('Context',traceContextHtml(item),'context-cell')+activityCell('Detail','<span class="truncate-cell" title="'+attr(item.detail||'')+'">'+esc(short(item.detail||'-',220))+'</span>','detail-cell')+activityCell('Actions',action,'actions-cell')+'</tr>'}
function renderTraceTimelineTable(timeline){if(!timeline.length)return uiEmpty('No events for this correlation ID.');return '<div class="data-table-wrap"><table class="data-table activity-table trace-table"><thead><tr><th>Time</th><th>Source</th><th>Status</th><th>Type</th><th>Title</th><th>Context</th><th>Detail</th><th class="actions-heading">Actions</th></tr></thead><tbody>'+timeline.map(renderTraceTimelineRow).join('')+'</tbody></table></div>'}
function renderTrace(data){const s=data.summary||{};const rows=[['Correlation ID',data.correlationId],['Status',s.status],['Started',fmtDate(s.startedAt)],['Updated',fmtDate(s.updatedAt)],['Agent',s.agentId],['Thread',s.threadId],['Workspace',s.workspace],['Sources',(s.sources||[]).join(', ')]];const target=document.getElementById('traceDetail');target.innerHTML=card('Trace summary',rows)+'<h2 class="task-section-title">Timeline</h2>'+renderTraceTimelineTable(data.timeline||[]);bindUiCopyButtons(target);startActivityAgeCounter()}
document.getElementById('loadTraceBtn').onclick=()=>loadTrace();
document.getElementById('traceCorrelationId').addEventListener('keydown',e=>{if(e.key==='Enter')loadTrace()});
function monitorTabPermission(tab){return{activity:'sessions.read',tasks:'inspect',trace:'sessions.read',artifacts:'files.read'}[tab]||'inspect'}
function firstAllowedMonitorTab(){return['activity','tasks','trace','artifacts'].find(tab=>can(monitorTabPermission(tab)))||'tasks'}
function ensureMonitorTabAllowed(){if(!can(monitorTabPermission(state.monitorTab)))state.monitorTab=firstAllowedMonitorTab()}
function switchMonitorTab(tab){state.monitorTab=tab||'activity';ensureMonitorTabAllowed();if(state.monitorTab!=='activity'&&state.monitorTab!=='tasks')stopActivityAgeCounter();document.querySelectorAll('[data-monitor-tab]').forEach(b=>{const active=b.dataset.monitorTab===state.monitorTab;b.classList.toggle('active',active);b.setAttribute('aria-selected',active?'true':'false');b.tabIndex=active?0:-1});document.querySelectorAll('[data-monitor-tab-panel]').forEach(panel=>panel.classList.toggle('active',panel.dataset.monitorTabPanel===state.monitorTab))}
function bindMonitorTabs(){document.querySelectorAll('[data-monitor-tab]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='true';b.onclick=()=>safe(async()=>{switchMonitorTab(b.dataset.monitorTab);await loadMonitorTab()})})}
async function loadMonitor(){bindMonitorTabs();ensureMonitorTabAllowed();switchMonitorTab(state.monitorTab||'activity');await loadMonitorTab()}
async function loadMonitorTab(){const tab=state.monitorTab||'activity';if(!can(monitorTabPermission(tab))){const panel=document.querySelector('[data-monitor-tab-panel="'+cssEscape(tab)+'"] .list');if(panel)panel.innerHTML=uiEmpty('Permission required: '+monitorTabPermission(tab));return}if(tab==='activity')await loadActivity(true);else if(tab==='tasks')await loadTasks(true);else if(tab==='trace')renderTracePlaceholder();else if(tab==='artifacts')await loadArtifacts(true)}
