function logQuery(){return{target:val('logTarget'),limit:val('logLines')||'120',lines:val('logLines')||'120',cursor:logPager.cursor||undefined,level:val('logLevel')||'all',search:val('logSearch')||undefined,since:val('logSince')||undefined}}
async function loadLogs(reset=true){if(reset)logPager.reset();if(!document.getElementById('logAutoRefresh').checked)setLoading('logs','Loading logs...');const data=await api('/api/logs',{query:logQuery()});state.logsPlain=data.plain||'';state.logsEntries=data.entries||null;renderLogs();logPager.render(data.pagination||{});if(document.getElementById('logFollow').checked)document.getElementById('logs').scrollTop=document.getElementById('logs').scrollHeight}document.getElementById('loadLogsBtn').onclick=()=>loadLogs(true);
function explicitLogLevelOf(line){const m=String(line||'').match(/^\s*(?:\[[^\]]+\]|\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}(?:\s+[+-]\d{2}:?\d{2})?)?\s*(ERROR|WARN|INFO)\b/);return m?m[1]:''}
function logTimeOf(line){const text=String(line||'');const m=text.match(/^\s*\[?(\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2})(?:\s+[+-]\d{2}:?\d{2})?\]?/);return m?new Date(m[1].replace(' ','T')).getTime():0}
function parsedLogLines(){let currentLevel='INFO';let currentTime=0;return state.logsPlain.split(/\n/).filter(line=>line.length>0).map(line=>{const explicit=explicitLogLevelOf(line);if(explicit)currentLevel=explicit;const time=logTimeOf(line);if(time)currentTime=time;return{line,level:currentLevel,time:currentTime}})}
function renderLogLine(entry){return '<span class="log-line '+esc(entry.level||'INFO')+'">'+esc(entry.line||'')+'</span>'}
function renderLogs(){const lines=Array.isArray(state.logsEntries)?state.logsEntries:parsedLogLines();renderIncrementalHtml('logs',lines,{key:'logs-view',emptyHtml:'(empty)',bodyTag:'span',renderItem:renderLogLine,initialCount:300,batchSize:300,onDone:()=>{if(document.getElementById('logFollow').checked)document.getElementById('logs').scrollTop=document.getElementById('logs').scrollHeight}})}
function queueLogReload(){clearTimeout(state.logSearchTimer);state.logSearchTimer=setTimeout(()=>loadLogs(true),250)}
document.getElementById('logTarget').onchange=()=>safe(()=>loadLogs(true));document.getElementById('logLevel').onchange=()=>safe(()=>loadLogs(true));document.getElementById('logLines').onchange=()=>safe(()=>loadLogs(true));document.getElementById('logSearch').oninput=()=>safe(queueLogReload);document.getElementById('logSince').onchange=()=>safe(()=>loadLogs(true));document.getElementById('logAutoRefresh').onchange=e=>{clearInterval(state.logTimer);state.logTimer=null;if(e.target.checked)state.logTimer=setInterval(()=>{if(!document.hidden)loadLogs(false)},5000)};document.getElementById('downloadLogsBtn').onclick=()=>{const blob=new Blob([state.logsPlain||''],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='nordrelay-log.txt';a.click();URL.revokeObjectURL(a.href)};document.getElementById('clearLogsBtn').onclick=()=>safe(async()=>{if(!can('logs.clear')){toast('Permission required: logs.clear');return}const target=document.getElementById('logTarget').value;if(confirm('Clear '+target+' log?')){await api('/api/logs/clear',{method:'POST',body:JSON.stringify({target})});state.logsPlain='';state.logsEntries=[];logPager.reset();renderLogs();logPager.render({});toast('Cleared '+target+' log')}});
