const CHAT_CODE_BLOCK_PREFIX='\uE010C';
const CHAT_CODE_BLOCK_SUFFIX='\uE010';
const CHAT_INLINE_CODE_PREFIX='\uE011I';
const CHAT_INLINE_CODE_SUFFIX='\uE011';
const CHAT_HISTORY_PAGE_SIZE=80;
function isChatNearBottom(){const box=document.getElementById('messages');if(!box)return true;return box.scrollHeight-box.scrollTop-box.clientHeight<80}
function updateChatJumpLatestButton(){const box=document.getElementById('messages');const button=document.getElementById('chatJumpLatestBtn');if(!box||!button)return;button.hidden=isChatNearBottom()||box.scrollHeight<=box.clientHeight+2}
function bindChatJumpLatestButton(){const box=document.getElementById('messages');const button=document.getElementById('chatJumpLatestBtn');if(box&&!box.dataset.jumpLatestBound){box.dataset.jumpLatestBound='true';box.addEventListener('scroll',updateChatJumpLatestButton,{passive:true})}if(button&&!button.dataset.bound){button.dataset.bound='true';button.onclick=()=>scrollChatToBottom({force:true})}updateChatJumpLatestButton()}
function scrollChatToBottom(options:WebuiChatScrollOptions={}){const box=document.getElementById('messages');if(!box)return;if(!options.force&&!isChatNearBottom())return;requestAnimationFrame(()=>{box.scrollTop=box.scrollHeight;updateChatJumpLatestButton();requestAnimationFrame(()=>{box.scrollTop=box.scrollHeight;updateChatJumpLatestButton()})})}
function markChatRendered(){state.chatRenderVersion=(state.chatRenderVersion||0)+1}
function appendMessage(cls,text,options:WebuiAppendMessageOptions={}){const box=document.getElementById('messages');const stick=options.forceScroll||isChatNearBottom();const previousTop=box?.scrollTop??0;const div=document.createElement('div');div.className='message '+cls;if(options.messageId)div.dataset.messageId=String(options.messageId);if(options.correlationId)div.dataset.correlationId=String(options.correlationId);if(options.peerId)div.dataset.peerId=String(options.peerId);if(options.agentId)div.dataset.agentId=String(options.agentId);if(options.threadId)div.dataset.threadId=String(options.threadId);if(options.contextKey)div.dataset.contextKey=String(options.contextKey);div.insertAdjacentHTML('beforeend',chatMessageActionsHtml());const body=document.createElement('div');body.className='message-body';div.appendChild(body);if(options.meta)div.__meta=options.meta;if(options.attachments)div.__attachments=options.attachments;setMessageText(div,text,options.meta,undefined,undefined,options.attachments);box.appendChild(div);if(stick)scrollChatToBottom({force:true});else box.scrollTop=previousTop;updateChatJumpLatestButton();return div}
function messageBody(div){let body=div.querySelector?.('.message-body');if(!body){body=document.createElement('div');body.className='message-body';div.textContent='';div.appendChild(body)}return body}
function setMessageText(div,text,meta:unknown[]|undefined=undefined,actions:WebuiRecord[]|undefined=undefined,actionResolution:WebuiRecord|null|undefined=undefined,attachments:WebuiChatAttachment[]|undefined=undefined){div.__rawText=String(text??'');if(meta!==undefined)div.__meta=Array.isArray(meta)?meta:[];if(attachments!==undefined)div.__attachments=Array.isArray(attachments)?attachments:[];if(actions!==undefined)div.__actions=Array.isArray(actions)?actions:[];if(actionResolution!==undefined)div.__actionResolution=actionResolution||null;const body=messageBody(div);body.innerHTML=renderChatMarkdown(div.__rawText)+chatMessageMetaHtml(div.__meta)+chatMessageAttachmentsHtml(div.__attachments,div.dataset.messageId)+chatMessageActionResolutionHtml(div.__actionResolution)+chatMessageCustomActionsHtml(div.__actions);bindChatCopyButtons(body);hydrateChatAttachments(body);bindChatMessageActionButtons(div);markChatRendered();return div}
function appendQueuedMessage(id,correlationId){const peerId=currentChatPeerId();const div=appendMessage('system','Queued prompt '+id);const body=messageBody(div);const actions=document.createElement('small');actions.className='queued-message-actions';if(correlationId)actions.insertAdjacentHTML('beforeend',uiTraceControls(correlationId));safe(()=>loadQueue({silent:true}));const btn=document.createElement('button');btn.type='button';btn.textContent='Cancel queued message';btn.className='danger mini-button';btn.onclick=()=>safe(async()=>{await queueActionRequest(peerId,'cancel',id);await loadQueue({silent:true});setMessageText(div,'Cancelled queued prompt '+id)});actions.appendChild(btn);body.appendChild(document.createElement('br'));body.appendChild(actions);bindUiCopyButtons(body);bindUiTraceButtons(body)}
function chatMessageRoleClass(role){return String(role||'system').replace(/[^a-z0-9_-]/gi,'')||'system'}
function isChatUserPromptMessage(message){return message?.role==='user'||(message?.role==='system'&&message?.source==='cli'&&/^Working on\b/i.test(String(message?.text||'')))}
function chatMessageClass(message){return ['message',chatMessageRoleClass(message?.role),isChatUserPromptMessage(message)?'user-prompt':''].filter(Boolean).join(' ')}
function chatMessageMetaHtml(meta){const items=(Array.isArray(meta)?meta:[]).map(item=>String(item||'').trim()).filter(Boolean);return items.length?'<div class="message-meta">'+items.map(item=>'<span>'+esc(item)+'</span>').join('')+'</div>':''}
function chatMessageAttachmentsHtml(attachments:WebuiChatAttachment[]|undefined,messageId:string|undefined=''){const items=(Array.isArray(attachments)?attachments:[]).filter(item=>item&&item.id&&item.name);if(!items.length)return'';return '<div class="chat-attachments">'+items.map(item=>{const id=String(item.id||'');const name=String(item.name||id);const kind=String(item.kind||'file');const mime=String(item.mimeType||'application/octet-stream');const size=Number(item.sizeBytes||0);const isImage=kind==='image'||mime.startsWith('image/');const disabled=!messageId?' disabled aria-disabled="true"':'';const attrs=' data-message-id="'+attr(messageId||'')+'" data-attachment-id="'+attr(id)+'" data-attachment-kind="'+attr(kind)+'" title="'+attr(name)+'"';if(isImage)return '<button type="button" class="chat-attachment chat-attachment-image"'+attrs+disabled+'><span class="chat-attachment-preview">Loading image...</span><small>'+esc(name)+' · '+esc(fmtBytes(size))+'</small></button>';return '<button type="button" class="chat-attachment chat-attachment-file"'+attrs+disabled+'><span>'+esc(chatAttachmentKindLabel(kind,mime))+'</span><small>'+esc(name)+' · '+esc(fmtBytes(size))+'</small></button>'}).join('')+'</div>'}
function chatAttachmentKindLabel(kind,mime){if(kind==='audio'||String(mime||'').startsWith('audio/'))return'Audio';if(kind==='image'||String(mime||'').startsWith('image/'))return'Image';return'File'}
function chatAttachmentDataUrl(file){return 'data:'+(file.mimeType||'application/octet-stream')+';base64,'+(file.dataBase64||'')}
async function fetchChatAttachment(button){return api('/api/chat/attachment',activeChatTabApiOptions({query:{messageId:button.dataset.messageId,attachmentId:button.dataset.attachmentId}}))}
async function loadChatAttachmentPreview(button){if(button.dataset.loaded||button.dataset.loading||button.disabled)return;button.dataset.loading='true';try{const file=await fetchChatAttachment(button);button.dataset.loaded='true';if(String(file.mimeType||'').startsWith('image/')){const preview=button.querySelector('.chat-attachment-preview');if(preview)preview.innerHTML='<img src="'+attr(chatAttachmentDataUrl(file))+'" alt="'+attr(file.name||'Attachment')+'">'}button.onclick=event=>safe(async()=>{event.preventDefault();event.stopPropagation();const data=await fetchChatAttachment(button);downloadBase64(data.name||'attachment',data.dataBase64||'',data.mimeType||'application/octet-stream')},event)}catch(error){button.dataset.loaded='error';button.classList.add('failed');const preview=button.querySelector('.chat-attachment-preview');if(preview)preview.textContent='Preview unavailable';button.title=error instanceof Error?error.message:String(error)}finally{delete button.dataset.loading}}
function hydrateChatAttachments(root:Document|Element=document){root.querySelectorAll?.('.chat-attachment[data-message-id][data-attachment-id]').forEach(button=>{if(!button.dataset.messageId||button.dataset.bound)return;button.dataset.bound='true';button.onclick=event=>safe(async()=>{event.preventDefault();event.stopPropagation();const data=await fetchChatAttachment(button);downloadBase64(data.name||'attachment',data.dataBase64||'',data.mimeType||'application/octet-stream')},event);if(button.classList.contains('chat-attachment-image'))void loadChatAttachmentPreview(button)})}
function chatLoadOlderHtml(){const pagination=state.chatHistoryPagination;if(!pagination?.hasNext||!pagination.nextCursor)return'';return '<div class="chat-history-pager"><button type="button" id="loadOlderChatBtn" class="secondary mini-button" '+(state.chatHistoryLoadingOlder?'disabled':'')+'>'+(state.chatHistoryLoadingOlder?'Loading older...':'Load older messages')+'</button><small>'+esc((state.chatMessages||[]).length+' of '+pagination.total+' shown')+'</small></div>'}
function promptHistoryMessageText(message){return String(messageRawText(message)||'').replace(/^Working on\s+/i,'').trim()}
function promptHistoryMessageMeta(message){return String(message.querySelector?.('small')?.textContent||'').trim()}
function promptHistoryMessageKey(message,index){const key=message.dataset.messageId?'id:'+message.dataset.messageId:message.dataset.correlationId?'correlation:'+message.dataset.correlationId:message.dataset.messageIndex?'index:'+message.dataset.messageIndex:'dom:'+index;message.dataset.promptHistoryKey=key;return key}
function promptHistoryEntries(){const messages=Array.from(document.querySelectorAll('#messages .message.user-prompt'));return messages.map((message,index)=>({message,key:promptHistoryMessageKey(message,index),text:promptHistoryMessageText(message),meta:promptHistoryMessageMeta(message)})).filter(entry=>entry.text).slice(-25).reverse()}
function scrollChatToHistoryPrompt(key){const box=document.getElementById('messages') as HTMLElement|null;const target=box?.querySelector('.message[data-prompt-history-key="'+cssEscape(String(key||''))+'"]') as HTMLElement|null;if(!box||!target){toast('Prompt is not loaded in the current chat page');return}const top=Math.max(0,target.offsetTop-box.offsetTop-Math.max(16,(box.clientHeight-target.clientHeight)/2));box.scrollTo({top,behavior:'smooth'});target.classList.add('message-highlight');setTimeout(()=>target.classList.remove('message-highlight'),1600);updateChatJumpLatestButton()}
function bindPromptHistorySidebar(root=document.getElementById('promptHistoryStream')){if(!root||root.dataset.bound)return;root.dataset.bound='true';root.addEventListener('click',event=>{const button=(event.target as Element|null)?.closest?.('[data-prompt-history-key]') as HTMLElement|null;if(!button)return;event.preventDefault();scrollChatToHistoryPrompt(button.dataset.promptHistoryKey)})}
function renderPromptHistorySidebar(){const root=document.getElementById('promptHistoryStream');if(!root)return;bindPromptHistorySidebar(root);const entries=promptHistoryEntries();root.innerHTML=entries.length?entries.map(entry=>'<button type="button" class="prompt-history-item" data-prompt-history-key="'+attr(entry.key)+'" title="'+attr(entry.text)+'"><span>'+esc(short(entry.text,180))+'</span>'+(entry.meta?'<small>'+esc(entry.meta)+'</small>':'')+'</button>').join(''):'<div class="tool empty">No prompts loaded for this session yet.</div>'}
let promptHistoryRenderFrame=0;
function schedulePromptHistorySidebarRender(){if(state.chatSidebarMode!=='history')return;if(promptHistoryRenderFrame)cancelAnimationFrame(promptHistoryRenderFrame);promptHistoryRenderFrame=requestAnimationFrame(()=>{promptHistoryRenderFrame=0;renderPromptHistorySidebar()})}
const promptHistoryMessagesEl=document.getElementById('messages');
if(promptHistoryMessagesEl)new MutationObserver(schedulePromptHistorySidebarRender).observe(promptHistoryMessagesEl,{childList:true});
function uniqueChatMessages(messages:WebuiChatMessage[]){const byId=new Map<string,WebuiChatMessage>();const withoutId:WebuiChatMessage[]=[];for(const message of messages||[]){const id=String(message?.id||'');if(id)byId.set(id,message);else withoutId.push(message)}return [...withoutId,...byId.values()].sort((left,right)=>Date.parse(left.timestamp)-Date.parse(right.timestamp))}
function chatMessageCorrelation(message){return String(message?.correlationId||'')}
function serverChatHasCorrelation(messages:WebuiChatMessage[],correlationId:string){return Boolean(correlationId&&messages.some(message=>chatMessageCorrelation(message)===correlationId))}
function pruneOptimisticChatMessages(messages:WebuiChatMessage[]){const now=Date.now();state.chatOptimisticMessages=(state.chatOptimisticMessages||[]).filter(message=>{const created=Date.parse(String(message.timestamp||''));if(Number.isFinite(created)&&now-created>300000)return false;const correlationId=chatMessageCorrelation(message);return !serverChatHasCorrelation(messages,correlationId)})}
function currentStreamingChatMessage(messages:WebuiChatMessage[]){if(!currentAgentMessage||!currentAgentMessage.isConnected||!chatElementMatchesCurrentChat(currentAgentMessage))return null;const text=String(currentAgentMessage.__rawText||'');if(!text)return null;const correlationId=String(currentAgentMessage.dataset?.correlationId||'');if(serverChatHasCorrelation(messages,correlationId))return null;return{id:'streaming-'+(correlationId||'agent'),role:'agent',source:'web',timestamp:new Date().toISOString(),text,correlationId,threadId:currentAgentMessage.dataset?.threadId}}
function mergeOptimisticChatMessages(messages:WebuiChatMessage[]){const base=messages||[];pruneOptimisticChatMessages(base);const merged=[...base];for(const message of state.chatOptimisticMessages||[]){const correlationId=chatMessageCorrelation(message);if(!serverChatHasCorrelation(merged,correlationId))merged.push(message)}const streaming=currentStreamingChatMessage(merged);if(streaming)merged.push(streaming);return uniqueChatMessages(merged)}
function upsertOptimisticChatMessage(message:WebuiChatMessage){const correlationId=chatMessageCorrelation(message);if(!correlationId)return;const list=state.chatOptimisticMessages||[];const existing=list.findIndex(item=>chatMessageCorrelation(item)===correlationId);if(existing>=0)list[existing]={...list[existing],...message};else list.push(message);state.chatOptimisticMessages=list}
function removeOptimisticChatMessage(correlationId:string){const id=String(correlationId||'');if(!id)return;state.chatOptimisticMessages=(state.chatOptimisticMessages||[]).filter(message=>chatMessageCorrelation(message)!==id)}
function removeChatMessageForCorrelation(correlationId:string){const id=String(correlationId||'');if(!id)return;removeOptimisticChatMessage(id);document.querySelectorAll('.message[data-correlation-id="'+cssEscape(id)+'"]').forEach(el=>el.remove());state.chatMessages=(state.chatMessages||[]).filter(message=>chatMessageCorrelation(message)!==id);markChatRendered();updateChatJumpLatestButton()}
function renderChatMessages(messages:WebuiChatMessage[]=[],options:WebuiRenderChatOptions={}){const renderMessages=mergeOptimisticChatMessages(messages||[]);state.chatMessages=renderMessages;const box=document.getElementById('messages');if(!box)return;const stick=options.forceScroll||isChatNearBottom();const previousTop=box.scrollTop;const previousHeight=box.scrollHeight;box.innerHTML=chatLoadOlderHtml()+renderMessages.map((m,index)=>'<div class="'+attr(chatMessageClass(m))+'" data-message-index="'+index+'" data-message-id="'+attr(m.id||'')+'" data-correlation-id="'+attr(m.correlationId||'')+'" data-thread-id="'+attr(m.threadId||'')+'">'+chatMessageActionsHtml()+'<small>'+esc((m.source||'web')+' / '+fmtDate(m.timestamp))+'</small><br><div class="message-body">'+renderChatMarkdown(m.text)+chatMessageMetaHtml(m.meta)+chatMessageAttachmentsHtml(m.attachments,m.id)+chatMessageActionResolutionHtml(m.actionResolution)+chatMessageCustomActionsHtml(m.actions)+'</div></div>').join('')+chatWorkingIndicatorHtml();renderMessages.forEach((m,index)=>{const el=box.querySelector<HTMLElement>('.message[data-message-index="'+index+'"]');if(el){el.__rawText=String(m.text??'');el.__meta=Array.isArray(m.meta)?m.meta:[];el.__attachments=Array.isArray(m.attachments)?m.attachments:[];el.__actions=Array.isArray(m.actions)?m.actions:[];el.__actionResolution=m.actionResolution||null}});const older=document.getElementById('loadOlderChatBtn');if(older)older.onclick=()=>safe(loadOlderChatHistory);bindChatCopyButtons(box);hydrateChatAttachments(box);markChatRendered();updateComposerAbortVisibility();syncChatWorkingTimer();bindChatJumpLatestButton();if(options.preserveScrollOffset)box.scrollTop=previousTop+(box.scrollHeight-previousHeight);else if(stick)scrollChatToBottom({force:true});else box.scrollTop=previousTop;updateChatJumpLatestButton()}
Object.assign(window,{renderChatMessages});
async function loadChatHistory(options:WebuiLoadChatHistoryOptions={}){const requestId=(state.chatHistoryRequestId||0)+1;state.chatHistoryRequestId=requestId;const renderVersion=state.chatRenderVersion||0;const data=await api('/api/chat/history',activeChatTabApiOptions({query:{limit:CHAT_HISTORY_PAGE_SIZE}}));if(requestId!==state.chatHistoryRequestId)return false;if(options.skipIfRendered!==false&&(state.chatRenderVersion||0)!==renderVersion)return false;state.chatHistoryPagination=data.pagination||null;renderChatMessages(data.messages||[],options);return true}
async function loadOlderChatHistory(){const pagination=state.chatHistoryPagination;if(!pagination?.hasNext||!pagination.nextCursor||state.chatHistoryLoadingOlder)return;state.chatHistoryLoadingOlder=true;renderChatMessages(state.chatMessages||[],{preserveScrollOffset:true});try{const data=await api('/api/chat/history',activeChatTabApiOptions({query:{limit:CHAT_HISTORY_PAGE_SIZE,cursor:pagination.nextCursor}}));state.chatHistoryPagination=data.pagination||null;renderChatMessages(uniqueChatMessages([...(data.messages||[]),...(state.chatMessages||[])]),{preserveScrollOffset:true})}finally{state.chatHistoryLoadingOlder=false;renderChatMessages(state.chatMessages||[],{preserveScrollOffset:true})}}
let currentAgentMessage=null;
function applyChatHistoryEvent(event:MessageEvent){safe(async()=>{let data:WebuiRecord|null=null;try{data=JSON.parse(event.data||'{}')}catch{}if(!chatEventMatchesCurrentChat(data)){renderChatTabs();return}const messages=Array.isArray(data?.messages)?data.messages as WebuiChatMessage[]:null;if(messages){state.chatHistoryPagination=null;currentAgentMessage=null;renderChatMessages(messages);renderChatTabs();return}await loadChatHistory({skipIfRendered:false});renderChatTabs()})}
function activeSessionPeerId(item){return String(item?.peerId||'local')}
function activeChatTabIdentity(){const tab=state.currentPage==='chat'?activeChatTab():null;if(!tab?.threadId)return null;return{peerId:String(tab.peerId||'local'),agentId:String(tab.agentId||''),threadId:String(tab.threadId||'')}}
function currentChatPeerId(){return activeChatTabIdentity()?.peerId||String(state.selectedPeer||'local')}
function currentChatIdentity(){const tabIdentity=activeChatTabIdentity();if(tabIdentity)return tabIdentity;const session=state.snapshot?.session||{};return{peerId:String(state.selectedPeer||'local'),agentId:String(session.agentId||''),threadId:String(session.threadId||'')}}
function chatEventThreadId(data){const direct=String(data?.threadId||'').trim();if(direct)return direct;const messages=Array.isArray(data?.messages)?data.messages:[];const ids=[...new Set(messages.map(message=>String(message?.threadId||'').trim()).filter(Boolean))];return ids.length===1?ids[0]:''}
function chatEventIdentity(data){const threadId=chatEventThreadId(data);if(!threadId)return null;return{peerId:String(state.eventsTarget||'local'),agentId:String(data?.agentId||''),threadId}}
function chatIdentityMatchesCurrentChat(identity){if(!identity?.threadId)return true;const current=currentChatIdentity();if(!current.threadId)return true;if(identity.peerId!==current.peerId)return false;if(identity.threadId!==current.threadId)return false;return !identity.agentId||!current.agentId||identity.agentId===current.agentId}
function chatEventMatchesCurrentChat(data){return chatIdentityMatchesCurrentChat(chatEventIdentity(data))}
function chatElementMatchesCurrentChat(el){const threadId=String(el?.dataset?.threadId||'').trim();if(!threadId)return true;return chatIdentityMatchesCurrentChat({peerId:String(el.dataset.peerId||state.eventsTarget||'local'),agentId:String(el.dataset.agentId||''),threadId})}
function chatEventAppendOptions(data){const identity=chatEventIdentity(data)||currentChatIdentity();return{peerId:String(identity.peerId||'local'),agentId:String(data?.agentId||identity.agentId||''),threadId:String(identity.threadId||''),contextKey:String(data?.contextKey||'')}}
function handleForeignChatEvent(){renderChatWorkingIndicator();renderSessionControls();renderChatTabs()}
function activeSessionMatchesCurrentChat(item,identity){return activeSessionPeerId(item)===identity.peerId&&String(item.threadId||'')===String(identity.threadId||'')&&(!identity.agentId||!item.agentId||String(item.agentId)===String(identity.agentId))&&(item.status==='running'||item.status==='external'||Boolean(item.approvalRequired))}
function activeSessionsFreshForCurrentChat(peerId){const loaded=state.activeSessionsLoadedTarget||'';if(!state.activeSessionsLastLoadAt)return false;if(loaded==='chat-tabs')return true;if(peerId==='local')return loaded==='local';return loaded===peerId}
function localTurnIsStaleWithoutActive(identity){if(state.localTurnPeerId&&state.localTurnPeerId!==identity.peerId)return true;const started=Date.parse(state.localTurnStartedAt||'');if(!Number.isFinite(started))return false;if(!activeSessionsFreshForCurrentChat(identity.peerId))return false;return state.activeSessionsLastLoadAt>started+1500}
function currentChatWorkingSession(){const identity=currentChatIdentity();if(!identity.threadId)return null;const active=(state.activeSessions?.sessions||[]).find(item=>activeSessionMatchesCurrentChat(item,identity));if(active)return active;if(state.localTurnThreadId===identity.threadId&&(!identity.agentId||!state.localTurnAgentId||state.localTurnAgentId===identity.agentId)){if(localTurnIsStaleWithoutActive(identity)){state.localTurnThreadId=null;state.localTurnAgentId=null;state.localTurnPeerId=null;state.localTurnStartedAt=null;return null}return{source:'web',status:'running',startedAt:state.localTurnStartedAt||new Date().toISOString(),peerId:identity.peerId,agentId:identity.agentId,threadId:identity.threadId}}return null}
function markChatVisibleCompletion(data:WebuiRecord={}){const identity=currentChatIdentity();if(!identity.threadId)return;state.chatVisibleCompletion={...identity,turnId:String(data.id||''),correlationId:String(data.correlationId||''),at:Number.isFinite(Date.parse(String(data.at||'')))?Date.parse(String(data.at)):Date.now()}}
function clearChatVisibleCompletionForCurrentSession(){const identity=currentChatIdentity();const completion=state.chatVisibleCompletion;if(completion&&completion.peerId===identity.peerId&&completion.threadId===identity.threadId&&(!completion.agentId||!identity.agentId||completion.agentId===identity.agentId))state.chatVisibleCompletion=null}
function chatVisibleCompletionMatches(active){const completion=state.chatVisibleCompletion;if(!completion||!active)return false;const completedAt=Number(completion.at||0);if(Date.now()-completedAt>30000){state.chatVisibleCompletion=null;return false}const identity=currentChatIdentity();if(completion.peerId!==identity.peerId||completion.threadId!==identity.threadId)return false;if(completion.agentId&&identity.agentId&&completion.agentId!==identity.agentId)return false;if(!completion.turnId||String(active.id||'')!==completion.turnId)return false;if(active.approvalRequired)return false;const tool=String(active.currentTool||'');if(tool&&tool!=='-')return false;const updated=Date.parse(active.updatedAt||'');if(Number.isFinite(updated)&&updated>completedAt+1000)return false;const activeStarted=Date.parse(active.startedAt||'');if(Number.isFinite(activeStarted)&&activeStarted>completedAt+1000)return false;return true}
function currentChatWorkingIndicatorSession(){const active=currentChatWorkingSession();return chatVisibleCompletionMatches(active)?null:active}
function currentCompletionSoundSessionKey(){const identity=currentChatIdentity();if(!identity.threadId)return'';return [identity.peerId,identity.agentId||'',identity.threadId].join('::')}
function syncCompletionSoundActivity(){const key=currentCompletionSoundSessionKey();const active=Boolean(currentChatWorkingSession());if(!key){state.completionSoundArmedKey=null;return}if(active){state.completionSoundArmedKey=key;return}if(state.completionSoundArmedKey===key){state.completionSoundArmedKey=null;playCompletionSound();return}if(state.completionSoundArmedKey&&state.completionSoundArmedKey!==key)state.completionSoundArmedKey=null}
function clearCurrentChatWorkingState(){state.localTurnThreadId=null;state.localTurnAgentId=null;state.localTurnPeerId=null;state.localTurnStartedAt=null;const identity=currentChatIdentity();if(!identity.threadId||!state.activeSessions?.sessions)return;state.activeSessions={...state.activeSessions,sessions:state.activeSessions.sessions.filter(item=>!activeSessionMatchesCurrentChat(item,identity))};updateActiveSessionsCount(state.activeSessions.sessions)}
function updateComposerAbortVisibility(){const active=Boolean(currentChatWorkingSession());const form=document.getElementById('promptForm');const button=document.getElementById('abortBtn') as HTMLButtonElement|null;if(button)button.hidden=!active;if(form)form.classList.toggle('composer-abort-visible',active)}
function chatWorkingStartedMs(active){const parsed=Date.parse(active?.startedAt||'');if(Number.isFinite(parsed))return parsed;if(Number.isFinite(Number(active?.durationMs)))return Date.now()-Number(active.durationMs);return Date.now()}
function fmtChatWorkingElapsed(ms){const sec=Math.max(0,Math.floor(ms/1000));if(sec<60)return sec+'s';const min=Math.floor(sec/60);if(min<60)return min+'m '+(sec%60)+'s';const hours=Math.floor(min/60);return hours+'h '+(min%60)+'m'}
function updateChatWorkingElapsed(){const el=document.getElementById('chatWorkingElapsed');if(!el)return;const started=Number(el.dataset.workingStartedMs||0);if(!Number.isFinite(started)||started<=0)return;el.textContent='('+fmtChatWorkingElapsed(Date.now()-started)+')'}
function stopChatWorkingTimer(){if(state.chatWorkingTimer)clearInterval(state.chatWorkingTimer);state.chatWorkingTimer=null}
function syncChatWorkingTimer(){updateChatWorkingElapsed();if(!document.getElementById('chatWorkingIndicator')){stopChatWorkingTimer();return}if(state.chatWorkingTimer)return;state.chatWorkingTimer=setInterval(()=>{if(!document.getElementById('chatWorkingIndicator')){stopChatWorkingTimer();return}updateChatWorkingElapsed()},1000)}
function chatWorkingIndicatorHtml(){const active=currentChatWorkingIndicatorSession();if(!active)return'';const approval=(active.approvalRequired||null) as WebuiRecord|null;const source=activeSourceLabel(active.source);const tool=active.currentTool||active.lastTool;const detail=approval?['Action required',approval.command||approval.toolName||''].filter(Boolean).join(' · '):[source,tool&&tool!=='-'?'tool '+tool:'',active.queueLength?active.queueLength+' queued':''].filter(Boolean).join(' · ');const startedMs=chatWorkingStartedMs(active);const label=approval?'Action required':'Working...';return '<div id="chatWorkingIndicator" class="chat-working-indicator '+(approval?'action-required':'')+'" aria-live="polite"><span class="chat-working-dot"></span><span>'+esc(label)+' <span id="chatWorkingElapsed" data-working-started-ms="'+attr(String(startedMs))+'">('+esc(fmtChatWorkingElapsed(Date.now()-startedMs))+')</span></span>'+(detail?'<small>'+esc(detail)+'</small>':'')+'</div>'}
function renderChatWorkingIndicator(){updateComposerAbortVisibility();const box=document.getElementById('messages');if(!box)return;const stick=isChatNearBottom();const previousTop=box.scrollTop;document.getElementById('chatWorkingIndicator')?.remove();const html=chatWorkingIndicatorHtml();if(html){box.insertAdjacentHTML('beforeend',html);startChatHistoryFollowup()}syncChatWorkingTimer();if(stick)scrollChatToBottom({force:true});else box.scrollTop=previousTop;updateChatJumpLatestButton()}
function renderChatMarkdown(text){let output=esc(String(text??''));const codeBlocks=[];const inlineCode=[];output=extractChatCodeBlocks(output,codeBlocks);output=extractChatInlineCode(output,inlineCode);output=formatChatBold(output);output=formatChatItalic(output);output=formatChatLinks(output);output=formatChatBlockquotes(output);output=formatChatLists(output);output=formatChatHeadings(output);output=restoreChatMarkdown(output,CHAT_INLINE_CODE_PREFIX,CHAT_INLINE_CODE_SUFFIX,inlineCode);output=restoreChatMarkdown(output,CHAT_CODE_BLOCK_PREFIX,CHAT_CODE_BLOCK_SUFFIX,codeBlocks);return normalizeChatCodeBlockSpacing(output)}
function extractChatCodeBlocks(text,blocks){return text.replace(/```([^\n`]*)\n?([\s\S]*?)```/g,(_match,rawLanguage,rawCode)=>{const language=String(rawLanguage||'').trim().replace(/[^a-zA-Z0-9_+-]/g,'');const className=language?' class="language-'+attr(language)+'"':'';const label=language?' data-code-language="'+attr(language)+'"':'';const code=String(rawCode??'').replace(/\n$/,'');const block='<pre class="chat-code-block" tabindex="0" title="Copy code" data-chat-copy="code-block"'+label+'><code'+className+'>'+code+'</code></pre>';const index=blocks.push(block)-1;return CHAT_CODE_BLOCK_PREFIX+index+CHAT_CODE_BLOCK_SUFFIX})}
function normalizeChatCodeBlockSpacing(text){return text.replace(/(<\/pre>)[ \t]*\n(?:[ \t]*\n)+/g,'$1\n')}
function extractChatInlineCode(text,inline){let result='';let index=0;while(index<text.length){if(text[index]!=='`'){result+=text[index];index+=1;continue}let tickCount=1;while(text[index+tickCount]==='`')tickCount+=1;const fence='`'.repeat(tickCount);const start=index+tickCount;const end=text.indexOf(fence,start);if(end===-1){result+=fence;index+=tickCount;continue}const content=text.slice(start,end);if(content.includes('\n')){result+=fence;index+=tickCount;continue}const button='<button type="button" class="chat-inline-code copy-id" title="Copy code" data-chat-copy="inline-code">'+content+'</button>';result+=CHAT_INLINE_CODE_PREFIX+(inline.push(button)-1)+CHAT_INLINE_CODE_SUFFIX;index=end+tickCount}return result}
function formatChatBold(text){return text.replace(/(?<!\*)\*\*(?!\s)([^\n]*?\S)\*\*(?!\*)/g,'<strong>$1</strong>')}
function formatChatItalic(text){return text.replace(/(?<![\w_])_(?!\s)([^_\n]*?\S)_(?![\w_])/g,'<em>$1</em>').replace(/(?<![\w*])\*(?!\s)([^*\n]*?\S)\*(?![\w*])/g,'<em>$1</em>')}
function formatChatLinks(text){return text.replace(/\[([^\]]+)\]\(([^)\s]+)\)/g,(_match,label,url)=>{const safeUrl=sanitizeChatUrl(String(url).replace(/&amp;/g,'&'));return '<a class="chat-link" href="'+attr(safeUrl)+'" target="_blank" rel="noreferrer noopener">'+label+'</a>'})}
function sanitizeChatUrl(url){const trimmed=String(url||'').trim().replace(/"/g,'%22');return /^(https?|mailto):/i.test(trimmed)?trimmed:'#'}
function formatChatBlockquotes(text){const lines=text.split('\n');const out=[];let quote=[];const flush=()=>{if(quote.length){out.push('<blockquote class="chat-blockquote">'+quote.join('\n')+'</blockquote>');quote=[]}};for(const line of lines){const match=line.match(/^&gt; ?(.*)$/);if(match){quote.push(match[1]);continue}flush();out.push(line)}flush();return out.join('\n')}
function formatChatLists(text){const lines=text.split('\n');const out=[];let list=null;let itemOpen=false;const closeItem=()=>{if(itemOpen){out.push('</li>');itemOpen=false}};const flush=()=>{closeItem();if(list){out.push('</'+list+'>');list=null}};const openList=(type,className,start='')=>{if(list!==type){flush();out.push('<'+type+' class="'+className+'"'+(start?' start="'+start+'"':'')+'>');list=type}};const startItem=content=>{closeItem();out.push('<li>'+content);itemOpen=true};for(const line of lines){const task=line.match(/^\s*[-*]\s+\[([ xX])\]\s+(.+)$/);const bullet=line.match(/^\s*[-*]\s+(.+)$/);const ordered=line.match(/^\s*(\d+)[.)]\s+(.+)$/);if(task){openList('ul','chat-list chat-task-list');const checked=task[1].toLowerCase()==='x'?'[x]':'[ ]';startItem('<span class="chat-task-mark">'+checked+'</span> '+task[2]);continue}if(bullet){openList('ul','chat-list');startItem(bullet[1]);continue}if(ordered){openList('ol','chat-list',ordered[1]);startItem(ordered[2]);continue}if(list&&itemOpen&&line.trim()){out.push('<span class="chat-list-continuation">'+line.trim()+'</span>');continue}flush();out.push(line)}flush();return normalizeChatListSpacing(out.join('\n'))}
function normalizeChatListSpacing(text){return text.replace(/<\/(ul|ol)>\n+(?=\S)/g,'</$1>')}
function formatChatHeadings(text){return text.split('\n').map(line=>{const match=line.match(/^(#{1,4})\s+(.+)$/);return match?'<strong class="chat-heading chat-heading-'+match[1].length+'">'+match[2]+'</strong>':line}).join('\n')}
function restoreChatMarkdown(text,prefix,suffix,values){const pattern=new RegExp(escapeChatRegExp(prefix)+'(\\d+)'+escapeChatRegExp(suffix),'g');return text.replace(pattern,(_match,rawIndex)=>values[Number.parseInt(rawIndex,10)]??'')}
function escapeChatRegExp(text){return text.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function chatMessageActionsHtml(){return '<button type="button" class="message-action-button message-copy-button" title="Copy message" aria-label="Copy message"></button><button type="button" class="message-action-button message-edit-button" title="Edit message" aria-label="Edit message"></button><button type="button" class="message-action-button message-retry-button" title="Retry message" aria-label="Retry message"></button>'}
function chatMessageCustomActionsHtml(actions){const items=(Array.isArray(actions)?actions:[]).filter(action=>action&&action.label&&action.action);if(!items.length)return'';return '<div class="chat-message-custom-actions">'+items.map(action=>'<button type="button" class="chat-message-custom-action '+attr(action.style||'secondary')+'" data-chat-action="'+attr(action.action)+'" title="'+attr(action.title||action.label)+'">'+esc(action.label)+'</button>').join('')+'</div>'}
function chatMessageActionResolutionHtml(resolution){if(!resolution||!resolution.label)return'';const title=resolution.resolvedAt?fmtDate(resolution.resolvedAt):'';return '<div class="chat-message-action-resolution" title="'+attr(title)+'">'+esc(resolution.label)+'</div>'}
function messageRawText(message){return message?.__rawText||message?.querySelector('.message-body')?.textContent||''}
function editChatMessage(message){const input=document.getElementById('promptInput') as HTMLTextAreaElement|null;if(!input)return;input.value=messageRawText(message);input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();input.setSelectionRange(input.value.length,input.value.length)}
async function retryChatMessage(message){if(!can('prompt.send')){toast('Permission required: prompt.send');return}const text=messageRawText(message).trim();if(!text){toast('Message is empty');return}const r=await api('/api/prompt',activeChatTabApiOptions({method:'POST',body:{text,correlationId:createWebCorrelationId()}}));toast(r.queued?'Retry queued '+r.queueId:'Retry started');if(r.queued&&r.queueId)appendQueuedMessage(r.queueId,r.correlationId)}
async function handleChatCustomAction(action){const queueCancel=String(action||'').match(/^queue:cancel:([a-z0-9]+)$/i);if(queueCancel){if(!can('queue.write')){toast('Permission required: queue.write');return}await queueActionRequest(currentChatPeerId(),'cancel',queueCancel[1]);await loadQueue({silent:true});await loadChatHistory({skipIfRendered:false});toast('Queued prompt cancelled');return}const match=String(action||'').match(/^approval:(yes|persist|no):([a-f0-9]+)$/);if(!match){toast('Unknown action');return}if(!can('prompt.abort')){toast('Permission required: prompt.abort');return}const result=await api('/api/approvals/'+encodeURIComponent(match[2])+'/respond',activeChatTabApiOptions({method:'POST',body:{choice:match[1]}}));toast(result.message||'Approval response submitted');await loadChatHistory({skipIfRendered:false});safe(loadActiveSessions)}
function bindChatMessageActionButtons(root){root.querySelectorAll?.('.message-copy-button').forEach(button=>{button.onclick=event=>{event.preventDefault();event.stopPropagation();const message=button.closest('.message');copyText(messageRawText(message),'Message copied')}});root.querySelectorAll?.('.message-edit-button').forEach(button=>{button.onclick=event=>{event.preventDefault();event.stopPropagation();editChatMessage(button.closest('.message'))}});root.querySelectorAll?.('.message-retry-button').forEach(button=>{button.onclick=event=>safe(async()=>{event.preventDefault();event.stopPropagation();await retryChatMessage(button.closest('.message'))},event)});root.querySelectorAll?.('.chat-message-custom-action').forEach(button=>{button.onclick=event=>safe(async()=>{event.preventDefault();event.stopPropagation();await handleChatCustomAction(button.dataset.chatAction)},event)})}
function bindChatCopyButtons(root){root.querySelectorAll?.('[data-chat-copy]').forEach(el=>{el.onclick=event=>{event.preventDefault();event.stopPropagation();const code=el.dataset.chatCopy==='code-block'?el.querySelector('code')?.textContent:el.textContent;copyText(code||'','Copied code')};el.onkeydown=event=>{if(el.tagName==='BUTTON')return;if(event.key==='Enter'||event.key===' '){event.preventDefault();el.click()}}});bindChatMessageActionButtons(root)}
const AGENT_UPDATE_TERMINAL_STATUSES=new Set(['completed','failed','cancelled']);
let agentUpdateVersionRefreshTimers=[];
function clearAgentUpdateVersionRefreshTimers(){agentUpdateVersionRefreshTimers.forEach(timer=>clearTimeout(timer));agentUpdateVersionRefreshTimers=[]}
function scheduleAgentUpdateVersionRefresh(job){if(!job||!AGENT_UPDATE_TERMINAL_STATUSES.has(job.status))return;clearAgentUpdateVersionRefreshTimers();const delays=[500,2000,5000,10000];agentUpdateVersionRefreshTimers=delays.map(delay=>setTimeout(()=>{if(state.currentPage==='version')loadVersion({quiet:true,refreshJobs:false})},delay))}
function expectedEventTarget(){return state.selectedPeer&&state.selectedPeer!=='local'?state.selectedPeer:'local'}
function expectedEventContextKey(){return expectedEventTarget()==='local'?'':webProxyEventContextKey()}
function eventStreamIsCurrent(){return Boolean(state.events&&state.eventsTarget===expectedEventTarget()&&state.eventsContextKey===expectedEventContextKey()&&state.events.readyState!==EventSource.CLOSED)}
function syncChatEventStreamForActiveContext(){if(state.currentPage!=='chat'||eventStreamIsCurrent())return false;connectEvents();return true}
function setLocalTurnFromCurrentChat(at){const identity=currentChatIdentity();state.localTurnThreadId=identity.threadId||null;state.localTurnAgentId=identity.agentId||null;state.localTurnPeerId=identity.peerId||'local';state.localTurnStartedAt=at||new Date().toISOString()}
function chatMessageExistsForCorrelation(correlationId){const id=String(correlationId||'');return Boolean(id&&document.querySelector('.message[data-correlation-id="'+cssEscape(id)+'"]'))}
function stopChatHistoryFollowup(){if(state.chatHistoryFollowupTimer)clearInterval(state.chatHistoryFollowupTimer);state.chatHistoryFollowupTimer=null}
function startChatHistoryFollowup(){if(state.chatHistoryFollowupTimer)return;const started=Date.now();state.chatHistoryFollowupTimer=setInterval(()=>{if(state.currentPage!=='chat'){stopChatHistoryFollowup();return}if(document.hidden)return;safe(async()=>{const preserve=!isChatNearBottom();await loadChatHistory({skipIfRendered:false,preserveScrollOffset:preserve,forceScroll:!preserve});await loadActiveSessions();if(!currentChatWorkingSession()&&Date.now()-started>5000)stopChatHistoryFollowup()})},2500)}
function connectEvents(){
  if(state.events) state.events.close();
  const eventTarget = expectedEventTarget();
  const remoteContextKey = expectedEventContextKey();
  const eventsUrl = eventTarget !== 'local'
    ? '/api/peers/'+encodeURIComponent(eventTarget)+'/events?contextKey='+encodeURIComponent(remoteContextKey)
    : '/api/events';
  const events = new EventSource(eventsUrl);
  state.events=events;
  state.eventsTarget=eventTarget;
  state.eventsContextKey=remoteContextKey;
  setApiState('restarting',{target:eventTarget,message:'Connecting to NordRelay events...',incrementFailure:false});
  events.onopen=()=>{if(state.reconnectTimer){clearTimeout(state.reconnectTimer);state.reconnectTimer=null}recordApiSuccess(eventTarget)};
  events.addEventListener('snapshot', e=>{const d=JSON.parse(e.data).data;state.snapshot=d;state.snapshotPeerId=eventTarget;syncCurrentSessionChatTab({activate:false});syncCompletionSoundActivity();renderSnapshot(d);renderSessionControls();renderChatWorkingIndicator();renderChatTabs()});
  events.addEventListener('chat_history', applyChatHistoryEvent);
  events.addEventListener('activity_update', e=>renderActivity(JSON.parse(e.data).events||[]));
  events.addEventListener('active_sessions_update', e=>{const d=JSON.parse(e.data);const eventPeer=state.selectedPeer||'local';const target=state.activeSessionsTarget||'local';if(state.currentPage==='chat'){if(Date.now()-(state.activeSessionsLastLoadAt||0)>1000)safe(loadActiveSessions);syncCompletionSoundActivity();renderChatWorkingIndicator();renderSessionControls();renderChatTabs();return}if(target==='all'){if(Date.now()-(state.activeSessionsLastLoadAt||0)>4500)safe(loadActiveSessions);renderChatTabs();return}if(target!==eventPeer){renderChatWorkingIndicator();renderChatTabs();return}state.activeSessions=d.active||null;updateActiveSessionsCount(state.activeSessions?.sessions||[]);syncCompletionSoundActivity();if(state.currentPage==='overview')renderActiveSessions(state.activeSessions?.sessions||[]);else renderChatWorkingIndicator();if(state.currentPage==='chat')renderSessionControls();renderChatTabs()});
  events.addEventListener('session_update', e=>{let d:WebuiRecord={};try{d=JSON.parse(e.data||'{}')}catch{}if(state.currentPage==='chat'&&!chatEventMatchesCurrentChat(d.session||d)){renderChatTabs();return}loadBootstrap();loadChatHistory();renderChatTabs()});
  events.addEventListener('agent_update', e=>{const d=JSON.parse(e.data);upsertAgentUpdateJob(d.job);if(state.currentPage==='version'){renderAgentUpdateJobs();scheduleAgentUpdateVersionRefresh(d.job)}});
  events.addEventListener('queue_update', ()=>{void loadQueue({silent:true}).catch(()=>{});renderChatWorkspaceLine()});
  events.addEventListener('turn_start', e=>{const d=JSON.parse(e.data);if(!chatEventMatchesCurrentChat(d)){handleForeignChatEvent();return}clearChatVisibleCompletionForCurrentSession();setLocalTurnFromCurrentChat(d.at);syncCompletionSoundActivity();const appendOptions={...chatEventAppendOptions(d),meta:d.meta,attachments:d.attachments,messageId:d.messageId,correlationId:d.correlationId};if(!chatMessageExistsForCorrelation(d.correlationId))appendMessage('user',d.text||d.prompt,appendOptions);currentAgentMessage=appendMessage('agent','',{...chatEventAppendOptions(d),correlationId:d.correlationId});startChatHistoryFollowup();renderChatWorkingIndicator();renderSessionControls();renderChatTabs();if(isMonitorTabActive('tasks'))loadTasks()});
  events.addEventListener('text_delta', e=>{const d=JSON.parse(e.data);if(!chatEventMatchesCurrentChat(d)){handleForeignChatEvent();return}clearChatVisibleCompletionForCurrentSession();const stick=isChatNearBottom();if(!currentAgentMessage||!currentAgentMessage.isConnected||!chatElementMatchesCurrentChat(currentAgentMessage))currentAgentMessage=appendMessage('agent','',{...chatEventAppendOptions(d),correlationId:d.correlationId});setMessageText(currentAgentMessage,(currentAgentMessage.__rawText||'')+d.delta);if(stick)scrollChatToBottom({force:true});renderChatWorkingIndicator();if(isMonitorTabActive('tasks'))loadTasks()});
  events.addEventListener('assistant_message_complete', e=>{const d=JSON.parse(e.data);if(!chatEventMatchesCurrentChat(d)){handleForeignChatEvent();return}markChatVisibleCompletion(d);renderChatWorkingIndicator();renderChatTabs()});
  events.addEventListener('tool_start', e=>{const d=JSON.parse(e.data);if(!chatEventMatchesCurrentChat(d)){handleForeignChatEvent();return}clearChatVisibleCompletionForCurrentSession();tool('tool','Started '+d.toolName);renderChatWorkingIndicator();renderSessionControls();renderChatTabs();if(isMonitorTabActive('tasks'))loadTasks()});
  events.addEventListener('tool_update', e=>{const d=JSON.parse(e.data);if(!chatEventMatchesCurrentChat(d)){handleForeignChatEvent();return}clearChatVisibleCompletionForCurrentSession();if(d.partialResult)tool('tool',d.partialResult.slice(-600));renderChatWorkingIndicator()});
  events.addEventListener('tool_end', e=>{const d=JSON.parse(e.data);if(!chatEventMatchesCurrentChat(d)){handleForeignChatEvent();return}clearChatVisibleCompletionForCurrentSession();tool(d.isError?'danger':'tool','Finished '+d.toolCallId+(d.isError?' with error':''));renderChatWorkingIndicator()});
  events.addEventListener('todo_update', e=>{const d=JSON.parse(e.data);if(!chatEventMatchesCurrentChat(d)){handleForeignChatEvent();return}clearChatVisibleCompletionForCurrentSession();tool('tool','Plan:\n'+d.items.map(i=>(i.completed?'[x] ':'[ ] ')+i.text).join('\n'));renderChatWorkingIndicator()});
  events.addEventListener('turn_error', e=>{const d=JSON.parse(e.data);if(!chatEventMatchesCurrentChat(d)){handleForeignChatEvent();return}appendMessage('system','Error: '+d.error,chatEventAppendOptions(d));currentAgentMessage=null;clearCurrentChatWorkingState();state.completionSoundArmedKey=null;stopChatHistoryFollowup();renderChatWorkingIndicator();renderSessionControls();renderChatTabs()});
  events.addEventListener('turn_complete', e=>{let d:WebuiRecord={};try{d=JSON.parse(e.data||'{}')}catch{}if(!chatEventMatchesCurrentChat(d)){handleForeignChatEvent();return}markChatVisibleCompletion(d);currentAgentMessage=null;clearCurrentChatWorkingState();syncCompletionSoundActivity();stopChatHistoryFollowup();renderChatWorkingIndicator();renderSessionControls();renderChatTabs();notify('NordRelay turn finished','The active task completed.');loadBootstrap();loadChatHistory({skipIfRendered:false});if(isMonitorTabActive('tasks'))loadTasks()});
  events.addEventListener('status', e=>{const d=JSON.parse(e.data);const msg=d.message||'';if(isCliRunningStatus(msg)){state.cliStatusActive=true;toast(msg,{sticky:true});return}if(isCliDoneStatus(msg)){state.cliStatusActive=false;clearStickyToast()}toast(msg)});
  events.onerror=()=>{setApiState(apiFetchFailureStatus(eventTarget),{target:eventTarget,message:eventTarget==='local'?'NordRelay events disconnected. Reconnecting...':'Peer events disconnected. Reconnecting...',retryAfterMs:5000});if(!state.reconnectTimer)state.reconnectTimer=setTimeout(()=>{state.reconnectTimer=null;connectEvents()},5000)};
}
function setConnection(text,kind){const el=document.getElementById('connectionStatus');el.className='footer-connection';el.innerHTML='<span class="footer-label">Connection:</span> <span class="footer-connection-value connection-'+attr(kind)+'">'+esc(text)+'</span>'}
window.addEventListener('offline',()=>setApiState('offline',{target:'local',message:'The browser is offline. Reconnect the network to continue.'}));
window.addEventListener('online',()=>{setApiState('restarting',{target:'local',message:'Browser is online. Reconnecting to NordRelay...',incrementFailure:false});connectEvents()});
document.addEventListener('visibilitychange',()=>{if(document.hidden)return;if(shouldRefreshActiveSessions())safe(loadActiveSessions);if(state.currentPage==='metrics')safe(()=>loadMetrics({silent:true}));if(state.currentPage==='diagnostics')safe(loadDiagnostics)});
const NOTIFICATION_PREF_KEY='nordrelayNotificationsEnabled';
function updateNotificationButton(){const button=document.getElementById('notifyBtn');if(!button)return;const enabled=Boolean(state.notifications);const blocked='Notification' in window&&Notification.permission==='denied';button.classList.toggle('notifications-enabled',enabled);button.setAttribute('aria-pressed',enabled?'true':'false');const label=enabled?'Disable notifications':blocked?'Notifications blocked by browser':'Enable notifications';button.setAttribute('aria-label',label);button.setAttribute('title',label)}
function setNotificationPreference(enabled,options:WebuiPersistOptions={}){const supported='Notification' in window;state.notifications=Boolean(enabled&&supported&&Notification.permission==='granted');if(options.persist!==false)localStorage.setItem(NOTIFICATION_PREF_KEY,state.notifications?'true':'false');updateNotificationButton()}
function initializeNotificationPreference(){const enabled=localStorage.getItem(NOTIFICATION_PREF_KEY)==='true';setNotificationPreference(enabled,{persist:false});if(!state.notifications&&enabled)localStorage.setItem(NOTIFICATION_PREF_KEY,'false')}
async function toggleNotifications(){if(state.notifications){setNotificationPreference(false);toast('Browser notifications disabled');return}if(!('Notification' in window)){toast('Browser notifications are not supported');updateNotificationButton();return}const permission=Notification.permission==='granted'?'granted':await Notification.requestPermission();if(permission==='granted'){setNotificationPreference(true);toast('Browser notifications enabled');return}setNotificationPreference(false);toast(permission==='denied'?'Browser notifications blocked':'Browser notifications denied')}
function notify(title,body){if(state.notifications&&'Notification' in window&&Notification.permission==='granted')new Notification(title,{body})}
const COMPLETION_SOUND_PREF_KEY='nordrelayCompletionSoundEnabled';
function updateCompletionSoundButton(){const button=document.getElementById('soundBtn');if(!button)return;const enabled=Boolean(state.completionSound);button.classList.toggle('sound-enabled',enabled);button.setAttribute('aria-pressed',enabled?'true':'false');const label=enabled?'Disable completion sound':'Enable completion sound';button.setAttribute('aria-label',label);button.setAttribute('title',label)}
function completionAudioContext(){const AudioCtor=window.AudioContext||window.webkitAudioContext;if(!AudioCtor)return null;if(!state.completionSoundAudioContext)state.completionSoundAudioContext=new AudioCtor();return state.completionSoundAudioContext}
async function unlockCompletionSoundAudio(){const ctx=completionAudioContext();if(!ctx)throw new Error('Completion sounds are not supported in this browser.');if(ctx.state==='suspended')await ctx.resume();return ctx}
function setCompletionSoundPreference(enabled,options:WebuiPersistOptions={}){state.completionSound=Boolean(enabled);if(options.persist!==false)localStorage.setItem(COMPLETION_SOUND_PREF_KEY,state.completionSound?'true':'false');updateCompletionSoundButton();if(state.completionSound)syncCompletionSoundActivity()}
function initializeCompletionSoundPreference(){setCompletionSoundPreference(localStorage.getItem(COMPLETION_SOUND_PREF_KEY)==='true',{persist:false})}
async function toggleCompletionSound(){if(state.completionSound){setCompletionSoundPreference(false);toast('Completion sound disabled');return}try{await unlockCompletionSoundAudio();setCompletionSoundPreference(true);toast('Completion sound enabled')}catch(error){setCompletionSoundPreference(false,{persist:false});toast(error instanceof Error?error.message:'Completion sound could not be enabled')}}
function playCompletionSound(){if(!state.completionSound)return;const start=ctx=>{const now=ctx.currentTime;const output=ctx.createGain();output.gain.setValueAtTime(0.0001,now);output.gain.exponentialRampToValueAtTime(0.42,now+0.006);output.gain.exponentialRampToValueAtTime(0.0001,now+0.18);output.connect(ctx.destination);const beep=ctx.createOscillator();beep.type='square';beep.frequency.setValueAtTime(880,now);beep.frequency.setValueAtTime(880,now+0.11);beep.connect(output);beep.start(now);beep.stop(now+0.19);const tone=ctx.createOscillator();tone.type='sine';tone.frequency.setValueAtTime(1320,now+0.012);tone.connect(output);tone.start(now+0.012);tone.stop(now+0.13)};try{const ctx=completionAudioContext();if(!ctx)return;if(ctx.state==='suspended')void ctx.resume().then(()=>start(ctx)).catch(()=>{});else start(ctx)}catch{}}
function bindCompletionSoundUnlockGesture(){const unlock=()=>{if(state.completionSound)void unlockCompletionSoundAudio().catch(()=>{});document.removeEventListener('pointerdown',unlock);document.removeEventListener('keydown',unlock)};document.addEventListener('pointerdown',unlock,{once:true});document.addEventListener('keydown',unlock,{once:true})}
initializeNotificationPreference();
initializeCompletionSoundPreference();
bindCompletionSoundUnlockGesture();
function toolAgeText(el){const created=Number(el.dataset.createdAt||Date.now());return 'Updated '+fmtAge(Date.now()-created)}
function refreshToolTooltip(){const tip=document.getElementById('toolTooltip');if(tip&&state.toolTooltipTarget)tip.textContent=toolAgeText(state.toolTooltipTarget)}
function positionToolTooltip(event){const tip=document.getElementById('toolTooltip');if(!tip||tip.style.display==='none')return;const gap=12;const rect=tip.getBoundingClientRect();let x=event.clientX+gap;let y=event.clientY+gap;if(x+rect.width>window.innerWidth-8)x=event.clientX-rect.width-gap;if(y+rect.height>window.innerHeight-8)y=event.clientY-rect.height-gap;tip.style.left=Math.max(8,x)+'px';tip.style.top=Math.max(8,y)+'px'}
function showToolTooltip(target,event){state.toolTooltipTarget=target;const tip=document.getElementById('toolTooltip');if(!tip)return;refreshToolTooltip();tip.style.display='block';positionToolTooltip(event);if(state.toolTooltipTimer)clearInterval(state.toolTooltipTimer);state.toolTooltipTimer=setInterval(refreshToolTooltip,1000)}
function hideToolTooltip(){const tip=document.getElementById('toolTooltip');if(tip)tip.style.display='none';state.toolTooltipTarget=null;if(state.toolTooltipTimer)clearInterval(state.toolTooltipTimer);state.toolTooltipTimer=null}
function updateToolAgeTitles(){document.querySelectorAll('.tool[data-created-at]').forEach(el=>el.setAttribute('aria-label',toolAgeText(el)))}
const toolStreamEl=document.getElementById('toolStream');
toolStreamEl.addEventListener('mouseover',e=>{const target=e.target.closest?.('.tool[data-created-at]');if(target&&target!==state.toolTooltipTarget)showToolTooltip(target,e)});
toolStreamEl.addEventListener('mousemove',e=>positionToolTooltip(e));
toolStreamEl.addEventListener('mouseout',e=>{const target=e.target.closest?.('.tool[data-created-at]');const related=e.relatedTarget instanceof Node?e.relatedTarget:null;if(target&&!target.contains(related))hideToolTooltip()});
toolStreamEl.addEventListener('focusin',e=>{const target=e.target.closest?.('.tool[data-created-at]');if(target)showToolTooltip(target,{clientX:target.getBoundingClientRect().left,clientY:target.getBoundingClientRect().bottom})});
toolStreamEl.addEventListener('focusout',hideToolTooltip);
function tool(cls,text){const div=document.createElement('div');div.className='tool '+(cls==='danger'?'danger':'');div.dataset.createdAt=String(Date.now());div.tabIndex=0;div.textContent=text;document.getElementById('toolStream').prepend(div);updateToolAgeTitles()}
setInterval(updateToolAgeTitles,30000);
