const CHAT_CODE_BLOCK_PREFIX='\uE010C';
const CHAT_CODE_BLOCK_SUFFIX='\uE010';
const CHAT_INLINE_CODE_PREFIX='\uE011I';
const CHAT_INLINE_CODE_SUFFIX='\uE011';
function isChatNearBottom(){const box=document.getElementById('messages');if(!box)return true;return box.scrollHeight-box.scrollTop-box.clientHeight<80}
function scrollChatToBottom(options:any={}){const box=document.getElementById('messages');if(!box)return;if(!options.force&&!isChatNearBottom())return;requestAnimationFrame(()=>{box.scrollTop=box.scrollHeight;requestAnimationFrame(()=>{box.scrollTop=box.scrollHeight})})}
function markChatRendered(){state.chatRenderVersion=(state.chatRenderVersion||0)+1}
function appendMessage(cls,text,options:any={}){const box=document.getElementById('messages');const stick=options.forceScroll||isChatNearBottom();const previousTop=box?.scrollTop??0;const div=document.createElement('div');div.className='message '+cls;div.insertAdjacentHTML('beforeend',chatMessageCopyButtonHtml());const body=document.createElement('div');body.className='message-body';div.appendChild(body);setMessageText(div,text);box.appendChild(div);if(stick)scrollChatToBottom({force:true});else box.scrollTop=previousTop;return div}
function messageBody(div){let body=div.querySelector?.('.message-body');if(!body){body=document.createElement('div');body.className='message-body';div.textContent='';div.appendChild(body)}return body}
function setMessageText(div,text){div.__rawText=String(text??'');const body=messageBody(div);body.innerHTML=renderChatMarkdown(div.__rawText);bindChatCopyButtons(body);bindChatMessageCopyButton(div);markChatRendered();return div}
function appendQueuedMessage(id,correlationId){const div=appendMessage('system','Queued prompt '+id);const body=messageBody(div);if(correlationId){body.insertAdjacentHTML('beforeend','<br><small>'+uiTraceControls(correlationId)+'</small>');bindUiCopyButtons(body);bindUiTraceButtons(body)}const btn=document.createElement('button');btn.textContent='Cancel queued message';btn.className='danger';btn.onclick=()=>safe(async()=>{const r=await api('/api/queue',{method:'POST',body:JSON.stringify({action:'cancel',id})});renderQueue(r.queue,r.paused);setMessageText(div,'Cancelled queued prompt '+id)});body.appendChild(document.createElement('br'));body.appendChild(btn)}
function renderChatMessages(messages,options:any={}){state.chatMessages=messages||[];const box=document.getElementById('messages');const stick=options.forceScroll||isChatNearBottom();const previousTop=box?.scrollTop??0;box.innerHTML=(messages||[]).map((m,index)=>'<div class="message '+esc(m.role)+'" data-message-index="'+index+'">'+chatMessageCopyButtonHtml()+'<small>'+esc((m.source||'web')+' / '+fmtDate(m.timestamp))+'</small><br><div class="message-body">'+renderChatMarkdown(m.text)+'</div></div>').join('')+chatWorkingIndicatorHtml();(messages||[]).forEach((m,index)=>{const el=box.querySelector('.message[data-message-index="'+index+'"]');if(el)el.__rawText=String(m.text??'')});bindChatCopyButtons(box);markChatRendered();if(stick)scrollChatToBottom({force:true});else box.scrollTop=previousTop}
Object.assign(window,{renderChatMessages});
async function loadChatHistory(options:any={}){const requestId=(state.chatHistoryRequestId||0)+1;state.chatHistoryRequestId=requestId;const renderVersion=state.chatRenderVersion||0;const data=await api('/api/chat/history');if(requestId!==state.chatHistoryRequestId)return false;if(options.skipIfRendered!==false&&(state.chatRenderVersion||0)!==renderVersion)return false;renderChatMessages(data.messages||[],options);return true}
let currentAgentMessage=null;
function currentChatWorkingSession(){const session=state.snapshot?.session||{};const threadId=session.threadId;if(!threadId)return null;return (state.activeSessions?.sessions||[]).find(item=>item.threadId===threadId&&(!session.agentId||item.agentId===session.agentId)&&(item.status==='running'||item.status==='external'))||null}
function chatWorkingIndicatorHtml(){const active=currentChatWorkingSession();if(!active)return'';const source=activeSourceLabel(active.source);const tool=active.currentTool||active.lastTool;const detail=[source,tool&&tool!=='-'?'tool '+tool:'',active.queueLength?active.queueLength+' queued':''].filter(Boolean).join(' · ');return '<div id="chatWorkingIndicator" class="chat-working-indicator" aria-live="polite"><span class="chat-working-dot"></span><span>Working...</span>'+(detail?'<small>'+esc(detail)+'</small>':'')+'</div>'}
function renderChatWorkingIndicator(){const box=document.getElementById('messages');if(!box)return;const stick=isChatNearBottom();const previousTop=box.scrollTop;document.getElementById('chatWorkingIndicator')?.remove();const html=chatWorkingIndicatorHtml();if(html)box.insertAdjacentHTML('beforeend',html);if(stick)scrollChatToBottom({force:true});else box.scrollTop=previousTop}
function renderChatMarkdown(text){let output=esc(String(text??''));const codeBlocks=[];const inlineCode=[];output=extractChatCodeBlocks(output,codeBlocks);output=extractChatInlineCode(output,inlineCode);output=formatChatBold(output);output=formatChatItalic(output);output=formatChatLinks(output);output=formatChatBlockquotes(output);output=formatChatLists(output);output=formatChatHeadings(output);output=restoreChatMarkdown(output,CHAT_INLINE_CODE_PREFIX,CHAT_INLINE_CODE_SUFFIX,inlineCode);output=restoreChatMarkdown(output,CHAT_CODE_BLOCK_PREFIX,CHAT_CODE_BLOCK_SUFFIX,codeBlocks);return normalizeChatCodeBlockSpacing(output)}
function extractChatCodeBlocks(text,blocks){return text.replace(/```([^\n`]*)\n?([\s\S]*?)```/g,(_match,rawLanguage,rawCode)=>{const language=String(rawLanguage||'').trim().replace(/[^a-zA-Z0-9_+-]/g,'');const className=language?' class="language-'+attr(language)+'"':'';const label=language?' data-code-language="'+attr(language)+'"':'';const code=String(rawCode??'').replace(/\n$/,'');const block='<pre class="chat-code-block" tabindex="0" title="Copy code" data-chat-copy="code-block"'+label+'><code'+className+'>'+code+'</code></pre>';const index=blocks.push(block)-1;return CHAT_CODE_BLOCK_PREFIX+index+CHAT_CODE_BLOCK_SUFFIX})}
function normalizeChatCodeBlockSpacing(text){return text.replace(/(<\/pre>)[ \t]*\n(?:[ \t]*\n)+/g,'$1\n')}
function extractChatInlineCode(text,inline){let result='';let index=0;while(index<text.length){if(text[index]!=='`'){result+=text[index];index+=1;continue}let tickCount=1;while(text[index+tickCount]==='`')tickCount+=1;const fence='`'.repeat(tickCount);const start=index+tickCount;const end=text.indexOf(fence,start);if(end===-1){result+=fence;index+=tickCount;continue}const content=text.slice(start,end);if(content.includes('\n')){result+=fence;index+=tickCount;continue}const button='<button type="button" class="chat-inline-code copy-id" title="Copy code" data-chat-copy="inline-code">'+content+'</button>';result+=CHAT_INLINE_CODE_PREFIX+(inline.push(button)-1)+CHAT_INLINE_CODE_SUFFIX;index=end+tickCount}return result}
function formatChatBold(text){return text.replace(/(?<!\*)\*\*(?!\s)([^\n]*?\S)\*\*(?!\*)/g,'<strong>$1</strong>')}
function formatChatItalic(text){return text.replace(/(?<![\w_])_(?!\s)([^_\n]*?\S)_(?![\w_])/g,'<em>$1</em>').replace(/(?<![\w*])\*(?!\s)([^*\n]*?\S)\*(?![\w*])/g,'<em>$1</em>')}
function formatChatLinks(text){return text.replace(/\[([^\]]+)\]\(([^)\s]+)\)/g,(_match,label,url)=>{const safeUrl=sanitizeChatUrl(String(url).replace(/&amp;/g,'&'));return '<a class="chat-link" href="'+attr(safeUrl)+'" target="_blank" rel="noreferrer noopener">'+label+'</a>'})}
function sanitizeChatUrl(url){const trimmed=String(url||'').trim().replace(/"/g,'%22');return /^(https?|mailto):/i.test(trimmed)?trimmed:'#'}
function formatChatBlockquotes(text){const lines=text.split('\n');const out=[];let quote=[];const flush=()=>{if(quote.length){out.push('<blockquote class="chat-blockquote">'+quote.join('\n')+'</blockquote>');quote=[]}};for(const line of lines){const match=line.match(/^&gt; ?(.*)$/);if(match){quote.push(match[1]);continue}flush();out.push(line)}flush();return out.join('\n')}
function formatChatLists(text){const lines=text.split('\n');const out=[];let list=null;let itemOpen=false;const closeItem=()=>{if(itemOpen){out.push('</li>');itemOpen=false}};const flush=()=>{closeItem();if(list){out.push('</'+list+'>');list=null}};const openList=(type,className,start='')=>{if(list!==type){flush();out.push('<'+type+' class="'+className+'"'+(start?' start="'+start+'"':'')+'>');list=type}};const startItem=content=>{closeItem();out.push('<li>'+content);itemOpen=true};for(const line of lines){const task=line.match(/^\s*[-*]\s+\[([ xX])\]\s+(.+)$/);const bullet=line.match(/^\s*[-*]\s+(.+)$/);const ordered=line.match(/^\s*(\d+)[.)]\s+(.+)$/);if(task){openList('ul','chat-list chat-task-list');const checked=task[1].toLowerCase()==='x'?'[x]':'[ ]';startItem('<span class="chat-task-mark">'+checked+'</span> '+task[2]);continue}if(bullet){openList('ul','chat-list');startItem(bullet[1]);continue}if(ordered){openList('ol','chat-list',ordered[1]);startItem(ordered[2]);continue}if(list&&itemOpen&&line.trim()){out.push('<span class="chat-list-continuation">'+line.trim()+'</span>');continue}flush();out.push(line)}flush();return normalizeChatListSpacing(out.join('\n'))}
function normalizeChatListSpacing(text){return text.replace(/<\/(ul|ol)>\n+(?=\S)/g,'</$1>')}
function formatChatHeadings(text){return text.split('\n').map(line=>{const match=line.match(/^(#{1,4})\s+(.+)$/);return match?'<strong class="chat-heading chat-heading-'+match[1].length+'">'+match[2]+'</strong>':line}).join('\n')}
function restoreChatMarkdown(text,prefix,suffix,values){const pattern=new RegExp(escapeChatRegExp(prefix)+'(\\d+)'+escapeChatRegExp(suffix),'g');return text.replace(pattern,(_match,rawIndex)=>values[Number.parseInt(rawIndex,10)]??'')}
function escapeChatRegExp(text){return text.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function chatMessageCopyButtonHtml(){return '<button type="button" class="message-copy-button" title="Copy message" aria-label="Copy message"></button>'}
function bindChatMessageCopyButton(root){root.querySelectorAll?.('.message-copy-button').forEach(button=>{button.onclick=event=>{event.preventDefault();event.stopPropagation();const message=button.closest('.message');const text=message?.__rawText||message?.querySelector('.message-body')?.textContent||'';copyText(text,'Message copied')}})}
function bindChatCopyButtons(root){root.querySelectorAll?.('[data-chat-copy]').forEach(el=>{el.onclick=event=>{event.preventDefault();event.stopPropagation();const code=el.dataset.chatCopy==='code-block'?el.querySelector('code')?.textContent:el.textContent;copyText(code||'','Copied code')};el.onkeydown=event=>{if(el.tagName==='BUTTON')return;if(event.key==='Enter'||event.key===' '){event.preventDefault();el.click()}}});bindChatMessageCopyButton(root)}
const AGENT_UPDATE_TERMINAL_STATUSES=new Set(['completed','failed','cancelled']);
let agentUpdateVersionRefreshTimers=[];
function clearAgentUpdateVersionRefreshTimers(){agentUpdateVersionRefreshTimers.forEach(timer=>clearTimeout(timer));agentUpdateVersionRefreshTimers=[]}
function scheduleAgentUpdateVersionRefresh(job){if(!job||!AGENT_UPDATE_TERMINAL_STATUSES.has(job.status))return;clearAgentUpdateVersionRefreshTimers();const delays=job.status==='completed'?[500,2000,5000,10000]:[500];agentUpdateVersionRefreshTimers=delays.map(delay=>setTimeout(()=>{if(state.currentPage==='version')loadVersion({quiet:true,refreshJobs:false})},delay))}
function connectEvents(){
  if(state.events) state.events.close();
  const eventsUrl = state.selectedPeer && state.selectedPeer !== 'local'
    ? '/api/peers/'+encodeURIComponent(state.selectedPeer)+'/events?contextKey='+encodeURIComponent('web:dashboard')
    : '/api/events';
  const events = new EventSource(eventsUrl);
  state.events=events;
  setConnection('Connecting','warn');
  events.onopen=()=>{if(state.reconnectTimer){clearTimeout(state.reconnectTimer);state.reconnectTimer=null}setConnection('Live','ok')};
  events.addEventListener('snapshot', e=>{const d=JSON.parse(e.data).data;state.snapshot=d;renderSnapshot(d);renderSessionControls();renderChatWorkingIndicator()});
  events.addEventListener('chat_history', e=>renderChatMessages(JSON.parse(e.data).messages||[]));
  events.addEventListener('activity_update', e=>renderActivity(JSON.parse(e.data).events||[]));
  events.addEventListener('active_sessions_update', e=>{const d=JSON.parse(e.data);state.activeSessions=d.active||null;if(state.currentPage==='overview')renderActiveSessions(state.activeSessions?.sessions||[]);else renderChatWorkingIndicator()});
  events.addEventListener('session_update', e=>{loadBootstrap();loadChatHistory()});
  events.addEventListener('agent_update', e=>{const d=JSON.parse(e.data);upsertAgentUpdateJob(d.job);if(state.currentPage==='version'){renderAgentUpdateJobs();scheduleAgentUpdateVersionRefresh(d.job)}});
  events.addEventListener('queue_update', e=>{const d=JSON.parse(e.data);renderQueue(d.queue,d.paused);if(state.currentPage==='queue')void loadQueuePlanner().catch(()=>{})});
  events.addEventListener('turn_start', e=>{const d=JSON.parse(e.data);appendMessage('user',d.prompt);currentAgentMessage=appendMessage('agent','');if(isMonitorTabActive('tasks'))loadTasks()});
  events.addEventListener('text_delta', e=>{const d=JSON.parse(e.data);const stick=isChatNearBottom();if(!currentAgentMessage)currentAgentMessage=appendMessage('agent','');setMessageText(currentAgentMessage,(currentAgentMessage.__rawText||'')+d.delta);if(stick)scrollChatToBottom({force:true});if(isMonitorTabActive('tasks'))loadTasks()});
  events.addEventListener('tool_start', e=>{const d=JSON.parse(e.data);tool('tool','Started '+d.toolName);if(isMonitorTabActive('tasks'))loadTasks()});
  events.addEventListener('tool_update', e=>{const d=JSON.parse(e.data);if(d.partialResult)tool('tool',d.partialResult.slice(-600))});
  events.addEventListener('tool_end', e=>{const d=JSON.parse(e.data);tool(d.isError?'danger':'tool','Finished '+d.toolCallId+(d.isError?' with error':''))});
  events.addEventListener('todo_update', e=>{const d=JSON.parse(e.data);tool('tool','Plan:\n'+d.items.map(i=>(i.completed?'[x] ':'[ ] ')+i.text).join('\n'))});
  events.addEventListener('turn_error', e=>{const d=JSON.parse(e.data);appendMessage('system','Error: '+d.error);currentAgentMessage=null});
  events.addEventListener('turn_complete', ()=>{currentAgentMessage=null;notify('NordRelay turn finished','The active task completed.');loadBootstrap();if(isMonitorTabActive('tasks'))loadTasks()});
  events.addEventListener('status', e=>{const d=JSON.parse(e.data);const msg=d.message||'';if(isCliRunningStatus(msg)){state.cliStatusActive=true;toast(msg,{sticky:true});return}if(isCliDoneStatus(msg)){state.cliStatusActive=false;clearStickyToast()}toast(msg)});
  events.onerror=()=>{setConnection('Reconnecting','error');if(!state.reconnectTimer)state.reconnectTimer=setTimeout(()=>{state.reconnectTimer=null;connectEvents()},5000)};
}
function setConnection(text,kind){const el=document.getElementById('connectionStatus');el.className='footer-connection';el.innerHTML='<span class="footer-label">Connection:</span> <span class="footer-connection-value connection-'+attr(kind)+'">'+esc(text)+'</span>'}
window.addEventListener('offline',()=>setConnection('Offline','error'));
window.addEventListener('online',()=>{setConnection('Reconnecting','warn');connectEvents()});
async function enableNotifications(){if(!('Notification' in window)){toast('Browser notifications are not supported');return}const permission=Notification.permission==='granted'?'granted':await Notification.requestPermission();state.notifications=permission==='granted';toast(state.notifications?'Browser notifications enabled':'Browser notifications denied')}
function notify(title,body){if(state.notifications&&'Notification' in window&&Notification.permission==='granted')new Notification(title,{body})}
function toolAgeText(el){const created=Number(el.dataset.createdAt||Date.now());return 'Updated '+fmtAge(Date.now()-created)}
function refreshToolTooltip(){const tip=document.getElementById('toolTooltip');if(tip&&state.toolTooltipTarget)tip.textContent=toolAgeText(state.toolTooltipTarget)}
function positionToolTooltip(event){const tip=document.getElementById('toolTooltip');if(!tip||tip.style.display==='none')return;const gap=12;const rect=tip.getBoundingClientRect();let x=event.clientX+gap;let y=event.clientY+gap;if(x+rect.width>window.innerWidth-8)x=event.clientX-rect.width-gap;if(y+rect.height>window.innerHeight-8)y=event.clientY-rect.height-gap;tip.style.left=Math.max(8,x)+'px';tip.style.top=Math.max(8,y)+'px'}
function showToolTooltip(target,event){state.toolTooltipTarget=target;const tip=document.getElementById('toolTooltip');if(!tip)return;refreshToolTooltip();tip.style.display='block';positionToolTooltip(event);if(state.toolTooltipTimer)clearInterval(state.toolTooltipTimer);state.toolTooltipTimer=setInterval(refreshToolTooltip,1000)}
function hideToolTooltip(){const tip=document.getElementById('toolTooltip');if(tip)tip.style.display='none';state.toolTooltipTarget=null;if(state.toolTooltipTimer)clearInterval(state.toolTooltipTimer);state.toolTooltipTimer=null}
function updateToolAgeTitles(){document.querySelectorAll('.tool[data-created-at]').forEach(el=>el.setAttribute('aria-label',toolAgeText(el)))}
const toolStreamEl=document.getElementById('toolStream');
toolStreamEl.addEventListener('mouseover',e=>{const target=e.target.closest?.('.tool[data-created-at]');if(target&&target!==state.toolTooltipTarget)showToolTooltip(target,e)});
toolStreamEl.addEventListener('mousemove',e=>positionToolTooltip(e));
toolStreamEl.addEventListener('mouseout',e=>{const target=e.target.closest?.('.tool[data-created-at]');if(target&&!target.contains(e.relatedTarget))hideToolTooltip()});
toolStreamEl.addEventListener('focusin',e=>{const target=e.target.closest?.('.tool[data-created-at]');if(target)showToolTooltip(target,{clientX:target.getBoundingClientRect().left,clientY:target.getBoundingClientRect().bottom})});
toolStreamEl.addEventListener('focusout',hideToolTooltip);
function tool(cls,text){const div=document.createElement('div');div.className='tool '+(cls==='danger'?'danger':'');div.dataset.createdAt=String(Date.now());div.tabIndex=0;div.textContent=text;document.getElementById('toolStream').prepend(div);updateToolAgeTitles()}
setInterval(updateToolAgeTitles,30000);
