const CHAT_CODE_BLOCK_PREFIX='\uE010C';
const CHAT_CODE_BLOCK_SUFFIX='\uE010';
const CHAT_INLINE_CODE_PREFIX='\uE011I';
const CHAT_INLINE_CODE_SUFFIX='\uE011';
function isChatNearBottom(){const box=document.getElementById('messages');if(!box)return true;return box.scrollHeight-box.scrollTop-box.clientHeight<80}
function scrollChatToBottom(options:any={}){const box=document.getElementById('messages');if(!box)return;if(!options.force&&!isChatNearBottom())return;requestAnimationFrame(()=>{box.scrollTop=box.scrollHeight;requestAnimationFrame(()=>{box.scrollTop=box.scrollHeight})})}
function markChatRendered(){state.chatRenderVersion=(state.chatRenderVersion||0)+1}
function appendMessage(cls,text,options:any={}){const box=document.getElementById('messages');const stick=options.forceScroll||isChatNearBottom();const previousTop=box?.scrollTop??0;const div=document.createElement('div');div.className='message '+cls;div.insertAdjacentHTML('beforeend',chatMessageActionsHtml());const body=document.createElement('div');body.className='message-body';div.appendChild(body);setMessageText(div,text);box.appendChild(div);if(stick)scrollChatToBottom({force:true});else box.scrollTop=previousTop;return div}
function messageBody(div){let body=div.querySelector?.('.message-body');if(!body){body=document.createElement('div');body.className='message-body';div.textContent='';div.appendChild(body)}return body}
function setMessageText(div,text){div.__rawText=String(text??'');const body=messageBody(div);body.innerHTML=renderChatMarkdown(div.__rawText);bindChatCopyButtons(body);bindChatMessageActionButtons(div);markChatRendered();return div}
function appendQueuedMessage(id,correlationId){const div=appendMessage('system','Queued prompt '+id);const body=messageBody(div);if(correlationId){body.insertAdjacentHTML('beforeend','<br><small>'+uiTraceControls(correlationId)+'</small>');bindUiCopyButtons(body);bindUiTraceButtons(body)}const btn=document.createElement('button');btn.textContent='Cancel queued message';btn.className='danger';btn.onclick=()=>safe(async()=>{const r=await api('/api/queue',{method:'POST',body:JSON.stringify({action:'cancel',id})});renderQueue(r.queue,r.paused);setMessageText(div,'Cancelled queued prompt '+id)});body.appendChild(document.createElement('br'));body.appendChild(btn)}
function chatMessageRoleClass(role){return String(role||'system').replace(/[^a-z0-9_-]/gi,'')||'system'}
function isChatUserPromptMessage(message){return message?.role==='user'||(message?.role==='system'&&message?.source==='cli'&&/^Working on\b/i.test(String(message?.text||'')))}
function chatMessageClass(message){return ['message',chatMessageRoleClass(message?.role),isChatUserPromptMessage(message)?'user-prompt':''].filter(Boolean).join(' ')}
function renderChatMessages(messages,options:any={}){state.chatMessages=messages||[];const box=document.getElementById('messages');const stick=options.forceScroll||isChatNearBottom();const previousTop=box?.scrollTop??0;box.innerHTML=(messages||[]).map((m,index)=>'<div class="'+attr(chatMessageClass(m))+'" data-message-index="'+index+'">'+chatMessageActionsHtml()+'<small>'+esc((m.source||'web')+' / '+fmtDate(m.timestamp))+'</small><br><div class="message-body">'+renderChatMarkdown(m.text)+'</div></div>').join('')+chatWorkingIndicatorHtml();(messages||[]).forEach((m,index)=>{const el=box.querySelector('.message[data-message-index="'+index+'"]');if(el)el.__rawText=String(m.text??'')});bindChatCopyButtons(box);markChatRendered();updateComposerAbortVisibility();syncChatWorkingTimer();if(stick)scrollChatToBottom({force:true});else box.scrollTop=previousTop}
Object.assign(window,{renderChatMessages});
async function loadChatHistory(options:any={}){const requestId=(state.chatHistoryRequestId||0)+1;state.chatHistoryRequestId=requestId;const renderVersion=state.chatRenderVersion||0;const data=await api('/api/chat/history');if(requestId!==state.chatHistoryRequestId)return false;if(options.skipIfRendered!==false&&(state.chatRenderVersion||0)!==renderVersion)return false;renderChatMessages(data.messages||[],options);return true}
let currentAgentMessage=null;
function currentChatWorkingSession(){const session=state.snapshot?.session||{};const threadId=session.threadId;if(!threadId)return null;const active=(state.activeSessions?.sessions||[]).find(item=>item.threadId===threadId&&(!session.agentId||item.agentId===session.agentId)&&(item.status==='running'||item.status==='external'));if(active)return active;if(state.localTurnThreadId===threadId&&(!session.agentId||!state.localTurnAgentId||state.localTurnAgentId===session.agentId))return{source:'web',status:'running',startedAt:state.localTurnStartedAt||new Date().toISOString()};return null}
function currentCompletionSoundSessionKey(){const session=state.snapshot?.session||{};const thread=session.threadId||'';if(!thread)return'';return [state.selectedPeer||'local',session.agentId||'',thread].join('::')}
function syncCompletionSoundActivity(){const key=currentCompletionSoundSessionKey();const active=Boolean(currentChatWorkingSession());if(!key){state.completionSoundArmedKey=null;return}if(active){state.completionSoundArmedKey=key;return}if(state.completionSoundArmedKey===key){state.completionSoundArmedKey=null;playCompletionSound();return}if(state.completionSoundArmedKey&&state.completionSoundArmedKey!==key)state.completionSoundArmedKey=null}
function clearCurrentChatWorkingState(){state.localTurnThreadId=null;state.localTurnAgentId=null;state.localTurnStartedAt=null;const session=state.snapshot?.session||{};const threadId=session.threadId;if(!threadId||!state.activeSessions?.sessions)return;state.activeSessions={...state.activeSessions,sessions:state.activeSessions.sessions.filter(item=>!(item.threadId===threadId&&(!session.agentId||item.agentId===session.agentId)))}}
function updateComposerAbortVisibility(){const active=Boolean(currentChatWorkingSession());const form=document.getElementById('promptForm');const button=document.getElementById('abortBtn') as HTMLButtonElement|null;if(button)button.hidden=!active;if(form)form.classList.toggle('composer-abort-visible',active)}
function chatWorkingStartedMs(active){const parsed=Date.parse(active?.startedAt||'');if(Number.isFinite(parsed))return parsed;if(Number.isFinite(Number(active?.durationMs)))return Date.now()-Number(active.durationMs);return Date.now()}
function fmtChatWorkingElapsed(ms){const sec=Math.max(0,Math.floor(ms/1000));if(sec<60)return sec+'s';const min=Math.floor(sec/60);if(min<60)return min+'m '+(sec%60)+'s';const hours=Math.floor(min/60);return hours+'h '+(min%60)+'m'}
function updateChatWorkingElapsed(){const el=document.getElementById('chatWorkingElapsed');if(!el)return;const started=Number(el.dataset.workingStartedMs||0);if(!Number.isFinite(started)||started<=0)return;el.textContent='('+fmtChatWorkingElapsed(Date.now()-started)+')'}
function stopChatWorkingTimer(){if(state.chatWorkingTimer)clearInterval(state.chatWorkingTimer);state.chatWorkingTimer=null}
function syncChatWorkingTimer(){updateChatWorkingElapsed();if(!document.getElementById('chatWorkingIndicator')){stopChatWorkingTimer();return}if(state.chatWorkingTimer)return;state.chatWorkingTimer=setInterval(()=>{if(!document.getElementById('chatWorkingIndicator')){stopChatWorkingTimer();return}updateChatWorkingElapsed()},1000)}
function chatWorkingIndicatorHtml(){const active=currentChatWorkingSession();if(!active)return'';const source=activeSourceLabel(active.source);const tool=active.currentTool||active.lastTool;const detail=[source,tool&&tool!=='-'?'tool '+tool:'',active.queueLength?active.queueLength+' queued':''].filter(Boolean).join(' · ');const startedMs=chatWorkingStartedMs(active);return '<div id="chatWorkingIndicator" class="chat-working-indicator" aria-live="polite"><span class="chat-working-dot"></span><span>Working... <span id="chatWorkingElapsed" data-working-started-ms="'+attr(String(startedMs))+'">('+esc(fmtChatWorkingElapsed(Date.now()-startedMs))+')</span></span>'+(detail?'<small>'+esc(detail)+'</small>':'')+'</div>'}
function renderChatWorkingIndicator(){updateComposerAbortVisibility();const box=document.getElementById('messages');if(!box)return;const stick=isChatNearBottom();const previousTop=box.scrollTop;document.getElementById('chatWorkingIndicator')?.remove();const html=chatWorkingIndicatorHtml();if(html)box.insertAdjacentHTML('beforeend',html);syncChatWorkingTimer();if(stick)scrollChatToBottom({force:true});else box.scrollTop=previousTop}
function renderChatMarkdown(text){let output=esc(String(text??''));const codeBlocks=[];const inlineCode=[];output=extractChatCodeBlocks(output,codeBlocks);output=extractChatInlineCode(output,inlineCode);output=formatChatBold(output);output=formatChatItalic(output);output=formatChatLinks(output);output=formatChatBlockquotes(output);output=formatChatLists(output);output=formatChatHeadings(output);output=restoreChatMarkdown(output,CHAT_INLINE_CODE_PREFIX,CHAT_INLINE_CODE_SUFFIX,inlineCode);output=restoreChatMarkdown(output,CHAT_CODE_BLOCK_PREFIX,CHAT_CODE_BLOCK_SUFFIX,codeBlocks);return normalizeChatCodeBlockSpacing(output)}
function extractChatCodeBlocks(text,blocks){return text.replace(/```([^\n`]*)\n?([\s\S]*?)```/g,(_match,rawLanguage,rawCode)=>{const language=String(rawLanguage||'').trim().replace(/[^a-zA-Z0-9_+-]/g,'');const className=language?' class="language-'+attr(language)+'"':'';const label=language?' data-code-language="'+attr(language)+'"':'';const code=String(rawCode??'').replace(/\n$/,'');const block='<pre class="chat-code-block" tabindex="0" title="Copy code" data-chat-copy="code-block"'+label+'><code'+className+'>'+code+'</code></pre>';const index=blocks.push(block)-1;return CHAT_CODE_BLOCK_PREFIX+index+CHAT_CODE_BLOCK_SUFFIX})}
function normalizeChatCodeBlockSpacing(text){return text.replace(/(<\/pre>)[ \t]*\n(?:[ \t]*\n)+/g,'$1\n')}
function extractChatInlineCode(text,inline){let result='';let index=0;while(index<text.length){if(text[index]!=='`'){result+=text[index];index+=1;continue}let tickCount=1;while(text[index+tickCount]==='`')tickCount+=1;const fence='`'.repeat(tickCount);const start=index+tickCount;const end=text.indexOf(fence,start);if(end===-1){result+=fence;index+=tickCount;continue}const content=text.slice(start,end);if(content.includes('\n')){result+=fence;index+=tickCount;continue}const button='<button type="button" class="chat-inline-code copy-id" title="Copy code" data-chat-copy="inline-code">'+content+'</button>';result+=CHAT_INLINE_CODE_PREFIX+(inline.push(button)-1)+CHAT_INLINE_CODE_SUFFIX;index=end+tickCount}return result}
function formatChatBold(text){return text.replace(/(?<!\*)\*\*(?!\s)([^\n]*?\S)\*\*(?!\*)/g,'<strong>$1</strong>')}
function formatChatItalic(text){return text.replace(/(?<![\w_])_(?!\s)([^_\n]*?\S)_(?![\w_])/g,'<em>$1</em>').replace(/(?<![\w*])\*(?!\s)([^*\n]*?\S)\*(?![\w*])/g,'<em>$1</em>')}
function formatChatLinks(text){return text.replace(/\[([^\]]+)\]\(([^)\s]+)\)/g,(_match,label,url)=>{const safeUrl=sanitizeChatUrl(String(url).replace(/&amp;/g,'&'));return '<a class="chat-link" href="'+attr(safeUrl)+'" target="_blank" rel="noreferrer noopener">'+label+'</a>'})}
function sanitizeChatUrl(url){const trimmed=String(url||'').trim().replace(/"/g,'%22');return /^(https?|mailto):/i.test(trimmed)?trimmed:'#'}
function formatChatBlockquotes(text){const lines=text.split('\n');const out=[];let quote=[];const flush=()=>{if(quote.length){out.push('<blockquote class="chat-blockquote">'+quote.join('\n')+'</blockquote>');quote=[]}};for(const line of lines){const match=line.match(/^&gt; ?(.*)$/);if(match){quote.push(match[1]);continue}flush();out.push(line)}flush();return out.join('\n')}
function formatChatLists(text){const lines=text.split('\n');const out=[];let list=null;let itemOpen=false;const closeItem=()=>{if(itemOpen){out.push('</li>');itemOpen=false}};const flush=()=>{closeItem();if(list){out.push('</'+list+'>');list=null}};const openList=(type,className,start='')=>{if(list!==type){flush();out.push('<'+type+' class="'+className+'"'+(start?' start="'+start+'"':'')+'>');list=type}};const startItem=content=>{closeItem();out.push('<li>'+content);itemOpen=true};for(const line of lines){const task=line.match(/^\s*[-*]\s+\[([ xX])\]\s+(.+)$/);const bullet=line.match(/^\s*[-*]\s+(.+)$/);const ordered=line.match(/^\s*(\d+)[.)]\s+(.+)$/);if(task){openList('ul','chat-list chat-task-list');const checked=task[1].toLowerCase()==='x'?'[x]':'[ ]';startItem('<span class="chat-task-mark">'+checked+'</span> '+task[2]);continue}if(bullet){openList('ul','chat-list');startItem(bullet[1]);continue}if(ordered){openList('ol','chat-list',ordered[1]);startItem(ordered[2]);continue}if(list&&itemOpen&&line.trim()){out.push('<span class="chat-list-continuation">'+line.trim()+'</span>');continue}flush();out.push(line)}flush();return normalizeChatListSpacing(out.join('\n'))}
function normalizeChatListSpacing(text){return text.replace(/<\/(ul|ol)>\n+(?=\S)/g,'</$1>')}
function formatChatHeadings(text){return text.split('\n').map(line=>{const match=line.match(/^(#{1,4})\s+(.+)$/);return match?'<strong class="chat-heading chat-heading-'+match[1].length+'">'+match[2]+'</strong>':line}).join('\n')}
function restoreChatMarkdown(text,prefix,suffix,values){const pattern=new RegExp(escapeChatRegExp(prefix)+'(\\d+)'+escapeChatRegExp(suffix),'g');return text.replace(pattern,(_match,rawIndex)=>values[Number.parseInt(rawIndex,10)]??'')}
function escapeChatRegExp(text){return text.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function chatMessageActionsHtml(){return '<button type="button" class="message-action-button message-copy-button" title="Copy message" aria-label="Copy message"></button><button type="button" class="message-action-button message-edit-button" title="Edit message" aria-label="Edit message"></button><button type="button" class="message-action-button message-retry-button" title="Retry message" aria-label="Retry message"></button>'}
function messageRawText(message){return message?.__rawText||message?.querySelector('.message-body')?.textContent||''}
function editChatMessage(message){const input=document.getElementById('promptInput') as HTMLTextAreaElement|null;if(!input)return;input.value=messageRawText(message);input.focus();input.setSelectionRange(input.value.length,input.value.length)}
async function retryChatMessage(message){if(!can('prompt.send')){toast('Permission required: prompt.send');return}const text=messageRawText(message).trim();if(!text){toast('Message is empty');return}const r=await api('/api/prompt',{method:'POST',body:{text,correlationId:createWebCorrelationId()}});toast(r.queued?'Retry queued '+r.queueId:'Retry started');if(r.queued&&r.queueId)appendQueuedMessage(r.queueId,r.correlationId)}
function bindChatMessageActionButtons(root){root.querySelectorAll?.('.message-copy-button').forEach(button=>{button.onclick=event=>{event.preventDefault();event.stopPropagation();const message=button.closest('.message');copyText(messageRawText(message),'Message copied')}});root.querySelectorAll?.('.message-edit-button').forEach(button=>{button.onclick=event=>{event.preventDefault();event.stopPropagation();editChatMessage(button.closest('.message'))}});root.querySelectorAll?.('.message-retry-button').forEach(button=>{button.onclick=event=>safe(async()=>{event.preventDefault();event.stopPropagation();await retryChatMessage(button.closest('.message'))},event)})}
function bindChatCopyButtons(root){root.querySelectorAll?.('[data-chat-copy]').forEach(el=>{el.onclick=event=>{event.preventDefault();event.stopPropagation();const code=el.dataset.chatCopy==='code-block'?el.querySelector('code')?.textContent:el.textContent;copyText(code||'','Copied code')};el.onkeydown=event=>{if(el.tagName==='BUTTON')return;if(event.key==='Enter'||event.key===' '){event.preventDefault();el.click()}}});bindChatMessageActionButtons(root)}
const AGENT_UPDATE_TERMINAL_STATUSES=new Set(['completed','failed','cancelled']);
let agentUpdateVersionRefreshTimers=[];
function clearAgentUpdateVersionRefreshTimers(){agentUpdateVersionRefreshTimers.forEach(timer=>clearTimeout(timer));agentUpdateVersionRefreshTimers=[]}
function scheduleAgentUpdateVersionRefresh(job){if(!job||!AGENT_UPDATE_TERMINAL_STATUSES.has(job.status))return;clearAgentUpdateVersionRefreshTimers();const delays=job.status==='completed'?[500,2000,5000,10000]:[500];agentUpdateVersionRefreshTimers=delays.map(delay=>setTimeout(()=>{if(state.currentPage==='version')loadVersion({quiet:true,refreshJobs:false})},delay))}
function connectEvents(){
  if(state.events) state.events.close();
  const eventsUrl = state.selectedPeer && state.selectedPeer !== 'local'
    ? '/api/peers/'+encodeURIComponent(state.selectedPeer)+'/events?contextKey='+encodeURIComponent('web:dashboard')
    : '/api/events';
  const events = new EventSource(eventsUrl);
  state.events=events;
  setConnection('Connecting','warn');
  events.onopen=()=>{if(state.reconnectTimer){clearTimeout(state.reconnectTimer);state.reconnectTimer=null}setConnection('Live','ok')};
  events.addEventListener('snapshot', e=>{const d=JSON.parse(e.data).data;state.snapshot=d;syncCompletionSoundActivity();renderSnapshot(d);renderSessionControls();renderChatWorkingIndicator()});
  events.addEventListener('chat_history', e=>renderChatMessages(JSON.parse(e.data).messages||[]));
  events.addEventListener('activity_update', e=>renderActivity(JSON.parse(e.data).events||[]));
  events.addEventListener('active_sessions_update', e=>{const d=JSON.parse(e.data);state.activeSessions=d.active||null;syncCompletionSoundActivity();if(state.currentPage==='overview')renderActiveSessions(state.activeSessions?.sessions||[]);else renderChatWorkingIndicator()});
  events.addEventListener('session_update', e=>{loadBootstrap();loadChatHistory()});
  events.addEventListener('agent_update', e=>{const d=JSON.parse(e.data);upsertAgentUpdateJob(d.job);if(state.currentPage==='version'){renderAgentUpdateJobs();scheduleAgentUpdateVersionRefresh(d.job)}});
  events.addEventListener('queue_update', e=>{const d=JSON.parse(e.data);renderQueue(d.queue,d.paused);if(state.currentPage==='queue')void loadQueuePlanner().catch(()=>{})});
  events.addEventListener('turn_start', e=>{const d=JSON.parse(e.data);state.localTurnThreadId=state.snapshot?.session?.threadId||null;state.localTurnAgentId=state.snapshot?.session?.agentId||null;state.localTurnStartedAt=d.at||new Date().toISOString();syncCompletionSoundActivity();appendMessage('user',d.prompt);currentAgentMessage=appendMessage('agent','');renderChatWorkingIndicator();if(isMonitorTabActive('tasks'))loadTasks()});
  events.addEventListener('text_delta', e=>{const d=JSON.parse(e.data);const stick=isChatNearBottom();if(!currentAgentMessage)currentAgentMessage=appendMessage('agent','');setMessageText(currentAgentMessage,(currentAgentMessage.__rawText||'')+d.delta);if(stick)scrollChatToBottom({force:true});if(isMonitorTabActive('tasks'))loadTasks()});
  events.addEventListener('tool_start', e=>{const d=JSON.parse(e.data);tool('tool','Started '+d.toolName);if(isMonitorTabActive('tasks'))loadTasks()});
  events.addEventListener('tool_update', e=>{const d=JSON.parse(e.data);if(d.partialResult)tool('tool',d.partialResult.slice(-600))});
  events.addEventListener('tool_end', e=>{const d=JSON.parse(e.data);tool(d.isError?'danger':'tool','Finished '+d.toolCallId+(d.isError?' with error':''))});
  events.addEventListener('todo_update', e=>{const d=JSON.parse(e.data);tool('tool','Plan:\n'+d.items.map(i=>(i.completed?'[x] ':'[ ] ')+i.text).join('\n'))});
  events.addEventListener('turn_error', e=>{const d=JSON.parse(e.data);appendMessage('system','Error: '+d.error);currentAgentMessage=null;clearCurrentChatWorkingState();state.completionSoundArmedKey=null;renderChatWorkingIndicator()});
  events.addEventListener('turn_complete', ()=>{currentAgentMessage=null;clearCurrentChatWorkingState();syncCompletionSoundActivity();renderChatWorkingIndicator();notify('NordRelay turn finished','The active task completed.');loadBootstrap();if(isMonitorTabActive('tasks'))loadTasks()});
  events.addEventListener('status', e=>{const d=JSON.parse(e.data);const msg=d.message||'';if(isCliRunningStatus(msg)){state.cliStatusActive=true;toast(msg,{sticky:true});return}if(isCliDoneStatus(msg)){state.cliStatusActive=false;clearStickyToast()}toast(msg)});
  events.onerror=()=>{setConnection('Reconnecting','error');if(!state.reconnectTimer)state.reconnectTimer=setTimeout(()=>{state.reconnectTimer=null;connectEvents()},5000)};
}
function setConnection(text,kind){const el=document.getElementById('connectionStatus');el.className='footer-connection';el.innerHTML='<span class="footer-label">Connection:</span> <span class="footer-connection-value connection-'+attr(kind)+'">'+esc(text)+'</span>'}
window.addEventListener('offline',()=>setConnection('Offline','error'));
window.addEventListener('online',()=>{setConnection('Reconnecting','warn');connectEvents()});
const NOTIFICATION_PREF_KEY='nordrelayNotificationsEnabled';
function updateNotificationButton(){const button=document.getElementById('notifyBtn');if(!button)return;const enabled=Boolean(state.notifications);const blocked='Notification' in window&&Notification.permission==='denied';button.classList.toggle('notifications-enabled',enabled);button.setAttribute('aria-pressed',enabled?'true':'false');const label=enabled?'Disable notifications':blocked?'Notifications blocked by browser':'Enable notifications';button.setAttribute('aria-label',label);button.setAttribute('title',label)}
function setNotificationPreference(enabled,options:any={}){const supported='Notification' in window;state.notifications=Boolean(enabled&&supported&&Notification.permission==='granted');if(options.persist!==false)localStorage.setItem(NOTIFICATION_PREF_KEY,state.notifications?'true':'false');updateNotificationButton()}
function initializeNotificationPreference(){const enabled=localStorage.getItem(NOTIFICATION_PREF_KEY)==='true';setNotificationPreference(enabled,{persist:false});if(!state.notifications&&enabled)localStorage.setItem(NOTIFICATION_PREF_KEY,'false')}
async function toggleNotifications(){if(state.notifications){setNotificationPreference(false);toast('Browser notifications disabled');return}if(!('Notification' in window)){toast('Browser notifications are not supported');updateNotificationButton();return}const permission=Notification.permission==='granted'?'granted':await Notification.requestPermission();if(permission==='granted'){setNotificationPreference(true);toast('Browser notifications enabled');return}setNotificationPreference(false);toast(permission==='denied'?'Browser notifications blocked':'Browser notifications denied')}
function notify(title,body){if(state.notifications&&'Notification' in window&&Notification.permission==='granted')new Notification(title,{body})}
const COMPLETION_SOUND_PREF_KEY='nordrelayCompletionSoundEnabled';
function updateCompletionSoundButton(){const button=document.getElementById('soundBtn');if(!button)return;const enabled=Boolean(state.completionSound);button.classList.toggle('sound-enabled',enabled);button.setAttribute('aria-pressed',enabled?'true':'false');const label=enabled?'Disable completion sound':'Enable completion sound';button.setAttribute('aria-label',label);button.setAttribute('title',label)}
function completionAudioContext(){const AudioCtor=window.AudioContext||(window as any).webkitAudioContext;if(!AudioCtor)return null;if(!state.completionSoundAudioContext)state.completionSoundAudioContext=new AudioCtor();return state.completionSoundAudioContext}
async function unlockCompletionSoundAudio(){const ctx=completionAudioContext();if(!ctx)throw new Error('Completion sounds are not supported in this browser.');if(ctx.state==='suspended')await ctx.resume();return ctx}
function setCompletionSoundPreference(enabled,options:any={}){state.completionSound=Boolean(enabled);if(options.persist!==false)localStorage.setItem(COMPLETION_SOUND_PREF_KEY,state.completionSound?'true':'false');updateCompletionSoundButton();if(state.completionSound)syncCompletionSoundActivity()}
function initializeCompletionSoundPreference(){setCompletionSoundPreference(localStorage.getItem(COMPLETION_SOUND_PREF_KEY)==='true',{persist:false})}
async function toggleCompletionSound(){if(state.completionSound){setCompletionSoundPreference(false);toast('Completion sound disabled');return}try{await unlockCompletionSoundAudio();setCompletionSoundPreference(true);toast('Completion sound enabled')}catch(error){setCompletionSoundPreference(false,{persist:false});toast(error instanceof Error?error.message:'Completion sound could not be enabled')}}
function playCompletionSound(){if(!state.completionSound)return;const start=ctx=>{const now=ctx.currentTime;const output=ctx.createGain();output.gain.setValueAtTime(0.0001,now);output.gain.exponentialRampToValueAtTime(0.18,now+0.012);output.gain.exponentialRampToValueAtTime(0.0001,now+0.22);output.connect(ctx.destination);const body=ctx.createOscillator();body.type='sine';body.frequency.setValueAtTime(520,now);body.frequency.exponentialRampToValueAtTime(180,now+0.16);body.connect(output);body.start(now);body.stop(now+0.24);const pop=ctx.createOscillator();pop.type='triangle';pop.frequency.setValueAtTime(950,now+0.01);pop.frequency.exponentialRampToValueAtTime(420,now+0.09);pop.connect(output);pop.start(now+0.01);pop.stop(now+0.1)};try{const ctx=completionAudioContext();if(!ctx)return;if(ctx.state==='suspended')void ctx.resume().then(()=>start(ctx)).catch(()=>{});else start(ctx)}catch{}}
function bindCompletionSoundUnlockGesture(){const unlock=()=>{if(state.completionSound)void unlockCompletionSoundAudio().catch(()=>{});document.removeEventListener('pointerdown',unlock);document.removeEventListener('keydown',unlock)};document.addEventListener('pointerdown',unlock,{once:true});document.addEventListener('keydown',unlock,{once:true})}
initializeNotificationPreference();
initializeCompletionSoundPreference();
bindCompletionSoundUnlockGesture();
function toolAgeText(el){const created=Number(el.dataset.createdAt||Date.now());return 'Updated '+fmtAge(Date.now()-created)}
function refreshToolTooltip(){const tip=document.getElementById('toolTooltip');if(tip&&state.toolTooltipTarget)tip.textContent=toolAgeText(state.toolTooltipTarget)}
function positionToolTooltip(event){const tip=document.getElementById('toolTooltip');if(!tip||tip.style.display==='none')return;const gap=12;const rect=tip.getBoundingClientRect();let x=event.clientX+gap;let y=event.clientY+gap;if(x+rect.width>window.innerWidth-8)x=event.clientX-rect.width-gap;if(y+rect.height>window.innerHeight-8)y=event.clientY-rect.height-gap;tip.style.left=Math.max(8,x)+'px';tip.style.top=Math.max(8,y)+'px'}
function showToolTooltip(target,event){state.toolTooltipTarget=target;const tip=document.getElementById('toolTooltip');if(!tip)return;refreshToolTooltip();tip.style.display='block';positionToolTooltip(event);if(state.toolTooltipTimer)clearInterval(state.toolTooltipTimer);state.toolTooltipTimer=setInterval(refreshToolTooltip,1000)}
function hideToolTooltip(){const tip=document.getElementById('toolTooltip');if(tip)tip.style.display='none';state.toolTooltipTarget=null;if(state.toolTooltipTimer)clearInterval(state.toolTooltipTimer);state.toolTooltipTimer=null}
function updateToolAgeTitles(){document.querySelectorAll('.tool[data-created-at]').forEach(el=>el.setAttribute('aria-label',toolAgeText(el)))}
const toolStreamEl=document.getElementById('toolStream');
toolStreamEl.addEventListener('mouseover',e=>{const target=e.target.closest?.('.tool[data-created-at]');if(target&&target!==state.toolTooltipTarget)showToolTooltip(target,e)});
toolStreamEl.addEventListener('mousemove',e=>positionToolTooltip(e));
toolStreamEl.addEventListener('mouseout',e=>{const target=e.target.closest?.('.tool[data-created-at]');if(target&&!target.contains(e.relatedTarget))hideToolTooltip()});
toolStreamEl.addEventListener('focusin',e=>{const target=e.target.closest?.('.tool[data-created-at]');if(target)showToolTooltip(target,{clientX:target.getBoundingClientRect().left,clientY:target.getBoundingClientRect().bottom})});
toolStreamEl.addEventListener('focusout',hideToolTooltip);
function tool(cls,text){const div=document.createElement('div');div.className='tool '+(cls==='danger'?'danger':'');div.dataset.createdAt=String(Date.now());div.tabIndex=0;div.textContent=text;document.getElementById('toolStream').prepend(div);updateToolAgeTitles()}
setInterval(updateToolAgeTitles,30000);
