async function loadSettings(){
  state.settingsWizard=null;
  state.settingsDraft={};
  state.settingsErrors={};
  document.getElementById('settingsTabHeader').style.display='';
  document.getElementById('settingsSubnav').style.display='';
  document.getElementById('settingsActions').style.display='';
  document.getElementById('settingsLayout')?.classList.remove('settings-wizard-layout');
  setLoading('settingsForm','Loading settings...');
  const data=await api('/api/settings');
  state.settings=data.settings;
  renderSettings();
}
const settingsCategoryDefinitions=[
  {id:'agents',label:'Agents',groups:['Agents','Codex','Pi','Hermes','OpenClaw','Claude Code']},
  {id:'chat',label:'Chat',groups:['Telegram','Discord','Slack','Matrix']},
  {id:'operations',label:'Operations',groups:['Operations','Artifacts','Peers','Voice']},
  {id:'workspace',label:'Workspace',groups:['Workspace']},
  {id:'dashboard',label:'Dashboard',groups:['Dashboard']},
];
function settingsGroups(){const groups:WebuiSettingsGroupMap={};state.settings.forEach(s=>(groups[s.group||'General']??=[]).push(s));return groups}
function settingsCategories(groups){const used=new Set();const categories=settingsCategoryDefinitions.map(def=>{const available=def.groups.filter(name=>groups[name]);available.forEach(name=>used.add(name));return available.length?{id:def.id,label:def.label,groups:available,count:available.reduce((sum,name)=>sum+groups[name].length,0)}:null}).filter(Boolean);Object.keys(groups).filter(name=>!used.has(name)).sort().forEach(name=>categories.push({id:'extra:'+name,label:name,groups:[name],count:groups[name].length}));return categories}
function settingsCategoryForGroup(categories,group){return categories.find(category=>category.groups.includes(group))||categories[0]}
function settingHelp(s){return s.help?'<span class="setting-info" tabindex="0" role="img" aria-label="'+attr(s.help)+'" title="'+attr(s.help)+'">i</span>':''}
function settingLabel(s){return '<label class="setting-label"><span>'+esc(s.label)+'</span>'+settingHelp(s)+'</label>'}
function settingOriginalValue(s){if(s.options||s.kind==='boolean')return s.configured?(s.value||''):'';return s.configured?(s.value||''):(s.effectiveValue||'')}
function settingCurrentValue(s){const draft=state.settingsDraft||{};if(Object.prototype.hasOwnProperty.call(draft,s.key))return draft[s.key];if(s.options||s.kind==='boolean')return s.configured?(s.value||''):'';return s.configured?(s.value||''):(s.effectiveValue||'')}
function settingIsDirty(s){return Object.prototype.hasOwnProperty.call(state.settingsDraft||{},s.key)&&String(state.settingsDraft[s.key]??'')!==String(settingOriginalValue(s))}
function settingsDirtyKeys(){const byKey=new Map((state.settings||[]).map(s=>[s.key,s]));return Object.keys(state.settingsDraft||{}).filter(key=>{const s=byKey.get(key);return s&&String(state.settingsDraft[key]??'')!==String(settingOriginalValue(s))})}
function settingsSearchQuery(){return String(state.settingsSearch||'').trim().toLowerCase()}
function settingMatchesSearch(s,query){if(!query)return true;return [s.key,s.label,s.group,s.description,s.help,s.effectiveValue,s.value].filter(Boolean).join(' ').toLowerCase().includes(query)}
function settingsMatchesByGroup(groups,query){const result:WebuiSettingsGroupMap={};Object.keys(groups).forEach(name=>{result[name]=(groups[name]||[]).filter(s=>settingMatchesSearch(s,query))});return result}
function settingsVisibleCount(category,matchesByGroup,searching){return category.groups.reduce((sum,name)=>sum+((searching?matchesByGroup[name]:null)||[]).length,0)}
function settingCategoryExpanded(category,activeCategory,searching){if(searching)return true;const open=state.settingsOpenCategories||{};if(open[category.id]===undefined)return true;return Boolean(open[category.id])}
function renderSettingsNavigator(categories,groups,matchesByGroup,searching,activeCategory){
  const target=document.getElementById('settingsSubnav');if(!target)return;
  const nav=categories.map(category=>{const count=searching?settingsVisibleCount(category,matchesByGroup,true):category.count;if(searching&&count===0)return'';const expanded=settingCategoryExpanded(category,activeCategory,searching);const groupButtons=category.groups.map(name=>{const items=searching?(matchesByGroup[name]||[]):(groups[name]||[]);if(searching&&items.length===0)return'';const active=state.settingsGroup===name&&!searching;return '<button type="button" class="settings-nav-group '+(active?'active':'')+'" data-setting-group="'+attr(name)+'">'+esc(name)+' <span>'+esc(String(items.length))+'</span></button>'}).join('');return '<div class="settings-nav-category '+(expanded?'open':'')+'" data-settings-nav-category="'+attr(category.id)+'"><button type="button" class="settings-nav-category-button" data-setting-category-toggle="'+attr(category.id)+'" aria-expanded="'+(expanded?'true':'false')+'"><span>'+esc(category.label)+'</span><span>'+esc(String(count))+'</span></button><div class="settings-nav-groups">'+groupButtons+'</div></div>'}).join('');
  target.innerHTML=nav||'<div class="settings-nav-empty">No matching settings.</div>';
  bindSettingsNavigator(categories);
}
function bindSettingsNavigator(categories){
  document.querySelectorAll('[data-setting-category-toggle]').forEach(button=>button.onclick=()=>{const id=button.dataset.settingCategoryToggle;state.settingsOpenCategories={...(state.settingsOpenCategories||{}),[id]:!settingCategoryExpanded(categories.find(category=>category.id===id)||{id},null,false)};renderSettings()});
  document.querySelectorAll('[data-setting-group]').forEach(button=>button.onclick=()=>{state.settingsGroup=button.dataset.settingGroup;state.settingsSearch='';const search=document.getElementById('settingsSearchInput');if(search)search.value='';renderSettings()});
}
function bindSettingsSearch(){
  const input=document.getElementById('settingsSearchInput');if(!input)return;
  input.value=state.settingsSearch||'';
  if(input.dataset.bound)return;
  input.dataset.bound='true';
  input.oninput=()=>{state.settingsSearch=input.value;renderSettings()};
}
function renderSettings(){const groups=settingsGroups();const categories=settingsCategories(groups);if(!state.settingsGroup||!groups[state.settingsGroup])state.settingsGroup=groups.Agents?'Agents':categories[0]?.groups[0];const activeCategory=settingsCategoryForGroup(categories,state.settingsGroup);const query=settingsSearchQuery();const searching=Boolean(query);const matchesByGroup=settingsMatchesByGroup(groups,query);bindSettingsSearch();renderSettingsNavigator(categories,groups,matchesByGroup,searching,activeCategory);document.getElementById('settingsForm').innerHTML='<div id="settingsRestartBanner"></div>'+(searching?renderSettingsSearchResults(categories,matchesByGroup,query):renderSettingsGroup(state.settingsGroup,groups[state.settingsGroup]||[]));bindSettingsUx();updateSettingsDirtyStatus()}
function renderSettingsSearchResults(categories,matchesByGroup,query){const sections=categories.flatMap(category=>category.groups.map(name=>({name,items:matchesByGroup[name]||[]})).filter(group=>group.items.length>0)).map(group=>renderSettingsGroup(group.name,group.items,'Search result'));if(!sections.length)return '<div class="settings-section"><h2>Search results</h2><div class="empty">No settings match "'+esc(query)+'".</div></div>';return '<div class="settings-search-summary">'+esc(sections.length+' section(s) match "'+query+'".')+'</div>'+sections.join('')}
function renderSettingsGroup(name,items,prefix=''){return '<div class="settings-section" data-settings-section="'+attr(name)+'"><h2>'+(prefix?'<span>'+esc(prefix)+'</span> ':'')+esc(name||'Settings')+'</h2>'+items.map(renderSettingCard).join('')+'</div>'}
function renderSettingCard(s){return '<div class="setting '+(settingIsDirty(s)?'dirty':'')+'" data-setting-box="'+attr(s.key)+'" data-restart-required="'+(s.restartRequired?'true':'false')+'">'+settingLabel(s)+settingInput(s)+'<small>'+esc(s.key)+' - '+esc(s.description)+(s.effectiveValue?' Active: '+esc(s.effectiveValue)+'.':'')+(s.restartRequired?' Restart required.':'')+(s.configured?' Saved in env file.':' Using default.')+'</small><div class="setting-actions"><button type="button" class="secondary" data-reset-setting="'+attr(s.key)+'">Use default</button>'+(s.kind==='secret'?'<button type="button" class="secondary" data-reveal-setting="'+attr(s.key)+'">Reveal/replace</button>':'')+'</div><div class="setting-error">'+esc((state.settingsErrors||{})[s.key]||'')+'</div></div>'}
function settingAttrs(s,original){return ' data-setting="'+attr(s.key)+'" data-original-value="'+attr(original)+'" data-configured="'+(s.configured?'true':'false')+'"'}
function settingInput(s){const current=settingCurrentValue(s);const original=settingOriginalValue(s);if(s.options){const blankLabel=s.effectiveValue?'Use active default ('+s.effectiveValue+')':'Use active default';return '<select'+settingAttrs(s,original)+'><option value="" '+(current===''?'selected':'')+'>'+esc(blankLabel)+'</option>'+s.options.map(o=>'<option value="'+attr(o)+'" '+(current===o?'selected':'')+'>'+esc(o)+'</option>').join('')+'</select>'}if(s.kind==='boolean'){const blankLabel=s.effectiveValue?'Use active default ('+s.effectiveValue+')':'Use active default';return '<select'+settingAttrs(s,original)+'><option value="" '+(current===''?'selected':'')+'>'+esc(blankLabel)+'</option><option value="true" '+(current==='true'?'selected':'')+'>true</option><option value="false" '+(current==='false'?'selected':'')+'>false</option></select>'}const value=esc(current);if(s.kind==='json')return '<textarea rows="4"'+settingAttrs(s,original)+'>'+value+'</textarea>';return '<input'+settingAttrs(s,original)+' value="'+value+'" '+(s.kind==='secret'?'type="password"':'')+'>'}
function bindSettingsUx(){document.querySelectorAll('[data-setting]').forEach(el=>{el.oninput=markSettingDirty;el.onchange=markSettingDirty});document.querySelectorAll('[data-reset-setting]').forEach(b=>b.onclick=()=>{const input=document.querySelector('[data-setting="'+cssEscape(b.dataset.resetSetting)+'"]');if(input){input.value='';markSettingDirty({target:input})}});document.querySelectorAll('[data-reveal-setting]').forEach(b=>b.onclick=()=>{const input=document.querySelector('[data-setting="'+cssEscape(b.dataset.revealSetting)+'"]');if(input){input.type=input.type==='password'?'text':'password';input.focus()}})}
function markSettingDirty(e){const el=e.target;const key=el.dataset.setting;const original=el.dataset.originalValue??'';state.settingsDraft={...(state.settingsDraft||{})};if(String(el.value)===String(original))delete state.settingsDraft[key];else state.settingsDraft[key]=el.value;if(state.settingsErrors)delete state.settingsErrors[key];const box=el.closest('.setting');if(box){box.classList.toggle('dirty',String(el.value)!==String(original));const error=box.querySelector('.setting-error');if(error)error.textContent=''}updateSettingsDirtyStatus()}
function updateSettingsDirtyStatus(){const dirty=settingsDirtyKeys();const restart=dirty.some(key=>document.querySelector('[data-setting-box="'+cssEscape(key)+'"]')?.dataset.restartRequired==='true'||(state.settings||[]).find(s=>s.key===key)?.restartRequired);document.getElementById('settingsStatus').textContent=dirty.length?dirty.length+' unsaved change(s)':'';const banner=document.getElementById('settingsRestartBanner');if(banner)banner.innerHTML=restart?'<div class="restart-banner">Some changed settings require a NordRelay restart.</div>':''}
document.getElementById('saveSettingsBtn').onclick=()=>safe(async()=>{if(!can('settings.write')){toast('Permission required: settings.write');return}state.settingsErrors={};document.querySelectorAll('.setting-error').forEach(e=>e.textContent='');const patch:WebuiStringMap={};settingsDirtyKeys().forEach(key=>patch[key]=state.settingsDraft[key]);const r=await api('/api/settings',{method:'PATCH',body:JSON.stringify({settings:patch})});(r.errors||[]).forEach(err=>{state.settingsErrors[err.key]=err.message});if(r.errors&&r.errors.length){renderSettings();document.getElementById('settingsStatus').textContent='Fix '+r.errors.length+' setting error(s)';toast('Settings need attention');return}const statusText=r.changedKeys.length?'Saved '+r.changedKeys.length+' setting(s)'+(r.restartRequired?' - restart required':''):'No changes';toast('Settings saved');state.settingsDraft={};state.settingsErrors={};await loadSettings();document.getElementById('settingsStatus').textContent=statusText});
document.getElementById('restartBtn').onclick=()=>safe(async()=>{if(!can('system.restart')){toast('Permission required: system.restart');return}if(confirm('Restart NordRelay now?')){await api('/api/runtime/restart',{method:'POST'});toast('Restart requested')}});
