async function loadSettings(){state.settingsWizard=null;document.getElementById('settingsTabHeader').style.display='';document.getElementById('settingsSubnav').style.display='';document.getElementById('settingsActions').style.display='';setLoading('settingsForm','Loading settings...');const data=await api('/api/settings');state.settings=data.settings;renderSettings()}
const settingsCategoryDefinitions=[
  {id:'agents',label:'Agents',groups:['Agents','Codex','Pi','Hermes','OpenClaw','Claude Code']},
  {id:'chat',label:'Chat',groups:['Telegram','Discord','Slack']},
  {id:'operations',label:'Operations',groups:['Operations','Artifacts','Peers','Voice']},
  {id:'workspace',label:'Workspace',groups:['Workspace']},
  {id:'dashboard',label:'Dashboard',groups:['Dashboard']},
];
function settingsCategories(groups){const used=new Set();const categories=settingsCategoryDefinitions.map(def=>{const available=def.groups.filter(name=>groups[name]);available.forEach(name=>used.add(name));return available.length?{id:def.id,label:def.label,groups:available,count:available.reduce((sum,name)=>sum+groups[name].length,0)}:null}).filter(Boolean);Object.keys(groups).filter(name=>!used.has(name)).sort().forEach(name=>categories.push({id:'extra:'+name,label:name,groups:[name],count:groups[name].length}));return categories}
function settingsCategoryForGroup(categories,group){return categories.find(category=>category.groups.includes(group))||categories[0]}
function settingHelp(s){return s.help?'<span class="setting-info" tabindex="0" role="img" aria-label="'+attr(s.help)+'" title="'+attr(s.help)+'">i</span>':''}
function settingLabel(s){return '<label class="setting-label"><span>'+esc(s.label)+'</span>'+settingHelp(s)+'</label>'}
function settingCategoryButton(category,activeCategory){const active=category.id===activeCategory?.id;return '<button type="button" role="tab" aria-selected="'+(active?'true':'false')+'" tabindex="'+(active?'0':'-1')+'" data-setting-category="'+attr(category.id)+'" class="'+(active?'active':'')+'">'+esc(category.label+' ('+category.count+')')+'</button>'}
function renderSettingsSubnav(category,groups){const target=document.getElementById('settingsSubnav');if(!target)return;if(!category||category.groups.length<2){target.hidden=true;target.innerHTML='';return}target.hidden=false;target.innerHTML='<label><span>'+esc(category.label)+' section</span><select id="settingsSubgroupSelect">'+category.groups.map(name=>'<option value="'+attr(name)+'" '+(name===state.settingsGroup?'selected':'')+'>'+esc(name+' ('+groups[name].length+')')+'</option>').join('')+'</select></label>';document.getElementById('settingsSubgroupSelect').onchange=e=>{state.settingsGroup=e.target.value;renderSettings()}}
function bindSettingsTabs(categories){document.querySelectorAll('#settingsTabs [data-setting-category]').forEach(b=>b.onclick=()=>{const category=categories.find(item=>item.id===b.dataset.settingCategory);if(!category)return;if(!category.groups.includes(state.settingsGroup))state.settingsGroup=category.groups[0];renderSettings()})}
function renderSettings(){const groups:any={};state.settings.forEach(s=>(groups[s.group]??=[]).push(s));const categories=settingsCategories(groups);if(!state.settingsGroup||!groups[state.settingsGroup])state.settingsGroup=groups.Agents?'Agents':categories[0]?.groups[0];const activeCategory=settingsCategoryForGroup(categories,state.settingsGroup);document.getElementById('settingsTabs').innerHTML=categories.map(category=>settingCategoryButton(category,activeCategory)).join('');renderSettingsSubnav(activeCategory,groups);const items=groups[state.settingsGroup]||[];document.getElementById('settingsForm').innerHTML='<div class="settings-section"><h2>'+esc(state.settingsGroup||'Settings')+'</h2><div id="settingsRestartBanner"></div>'+items.map(s=>'<div class="setting" data-setting-box="'+attr(s.key)+'" data-restart-required="'+(s.restartRequired?'true':'false')+'">'+settingLabel(s)+settingInput(s)+'<small>'+esc(s.key)+' - '+esc(s.description)+(s.effectiveValue?' Active: '+esc(s.effectiveValue)+'.':'')+(s.restartRequired?' Restart required.':'')+(s.configured?' Saved in env file.':' Using default.')+'</small><div class="setting-actions"><button type="button" class="secondary" data-reset-setting="'+attr(s.key)+'">Use default</button>'+(s.kind==='secret'?'<button type="button" class="secondary" data-reveal-setting="'+attr(s.key)+'">Reveal/replace</button>':'')+'</div><div class="setting-error"></div></div>').join('')+'</div>';bindSettingsTabs(categories);bindSettingsUx()}
function settingAttrs(s,original){return ' data-setting="'+attr(s.key)+'" data-original-value="'+attr(original)+'" data-configured="'+(s.configured?'true':'false')+'"'}
function settingInput(s){const display=s.configured?(s.value||''):(s.effectiveValue||''); if(s.options){const blankLabel=s.effectiveValue?'Use active default ('+s.effectiveValue+')':'Use active default';return '<select'+settingAttrs(s,s.configured?s.value:'')+'><option value="" '+(!s.configured?'selected':'')+'>'+esc(blankLabel)+'</option>'+s.options.map(o=>'<option value="'+attr(o)+'" '+(s.configured&&s.value===o?'selected':'')+'>'+esc(o)+'</option>').join('')+'</select>'} if(s.kind==='boolean'){const blankLabel=s.effectiveValue?'Use active default ('+s.effectiveValue+')':'Use active default';return '<select'+settingAttrs(s,s.configured?s.value:'')+'><option value="" '+(!s.configured?'selected':'')+'>'+esc(blankLabel)+'</option><option value="true" '+(s.configured&&s.value==='true'?'selected':'')+'>true</option><option value="false" '+(s.configured&&s.value==='false'?'selected':'')+'>false</option></select>'} const value=esc(display); if(s.kind==='json')return '<textarea rows="4"'+settingAttrs(s,display)+'>'+value+'</textarea>'; return '<input'+settingAttrs(s,display)+' value="'+value+'" '+(s.kind==='secret'?'type="password"':'')+'>'}
function bindSettingsUx(){document.querySelectorAll('[data-setting]').forEach(el=>{el.oninput=markSettingDirty;el.onchange=markSettingDirty});document.querySelectorAll('[data-reset-setting]').forEach(b=>b.onclick=()=>{const input=document.querySelector('[data-setting="'+cssEscape(b.dataset.resetSetting)+'"]');if(input){input.value='';markSettingDirty({target:input})}});document.querySelectorAll('[data-reveal-setting]').forEach(b=>b.onclick=()=>{const input=document.querySelector('[data-setting="'+cssEscape(b.dataset.revealSetting)+'"]');if(input){input.type=input.type==='password'?'text':'password';input.focus()}})}
function markSettingDirty(e){const el=e.target;const box=el.closest('.setting');const dirty=el.value!==(el.dataset.originalValue??'');box.classList.toggle('dirty',dirty);const dirtyInputs=Array.from(document.querySelectorAll('[data-setting]')).filter(x=>x.value!==(x.dataset.originalValue??''));const restart=dirtyInputs.some(x=>x.closest('.setting')?.dataset.restartRequired==='true');document.getElementById('settingsStatus').textContent=dirtyInputs.length?dirtyInputs.length+' unsaved change(s)':'';const banner=document.getElementById('settingsRestartBanner');if(banner)banner.innerHTML=restart?'<div class="restart-banner">Some changed settings require a NordRelay restart.</div>':''}
document.getElementById('saveSettingsBtn').onclick=()=>safe(async()=>{if(!can('settings.write')){toast('Permission required: settings.write');return}document.querySelectorAll('.setting-error').forEach(e=>e.textContent='');const patch:any={};document.querySelectorAll('[data-setting]').forEach(el=>{const original=el.dataset.originalValue??'';if(el.value!==original)patch[el.dataset.setting]=el.value});const r=await api('/api/settings',{method:'PATCH',body:JSON.stringify({settings:patch})});(r.errors||[]).forEach(err=>{const box=document.querySelector('[data-setting-box="'+cssEscape(err.key)+'"] .setting-error');if(box)box.textContent=err.message});document.getElementById('settingsStatus').textContent=(r.errors&&r.errors.length)?'Fix '+r.errors.length+' setting error(s)':(r.changedKeys.length?'Saved '+r.changedKeys.length+' setting(s)'+(r.restartRequired?' - restart required':''):'No changes');toast((r.errors&&r.errors.length)?'Settings need attention':'Settings saved');if(!(r.errors&&r.errors.length))await loadSettings()});
document.getElementById('restartBtn').onclick=()=>safe(async()=>{if(!can('system.restart')){toast('Permission required: system.restart');return}if(confirm('Restart NordRelay now?')){await api('/api/runtime/restart',{method:'POST'});toast('Restart requested')}});
