interface Element {
  __rawText?: string;
  __pendingRawText?: string;
  __pendingStick?: boolean;
  __meta?: unknown[];
  __attachments?: WebuiChatAttachment[];
  __actions?: WebuiRecord[];
  __actionResolution?: WebuiRecord | null;
  checked?: boolean;
  close?: () => void;
  dataset: DOMStringMap;
  disabled?: boolean;
  files?: FileList | null;
  hidden: boolean;
  onchange?: ((event: Event) => void) | null;
  onclick?: ((event: MouseEvent) => void) | null;
  ondragend?: ((event: DragEvent) => void) | null;
  ondragover?: ((event: DragEvent) => void) | null;
  ondragstart?: ((event: DragEvent) => void) | null;
  ondrop?: ((event: DragEvent) => void) | null;
  oninput?: ((event: Event) => void) | null;
  showModal?: () => void;
  tabIndex: number;
  title: string;
  type?: string;
  value?: string;
  focus?: () => void;
}

interface EventTarget {
  checked?: boolean;
  close?: () => void;
  closest?: (selector: string) => Element | null;
  dataset?: DOMStringMap;
  files?: FileList | null;
  value?: string;
}

interface HTMLElement {
  __rawText?: string;
  __pendingRawText?: string;
  __pendingStick?: boolean;
  __meta?: unknown[];
  __attachments?: WebuiChatAttachment[];
  __actions?: WebuiRecord[];
  __actionResolution?: WebuiRecord | null;
}

interface Window {
  webkitAudioContext?: typeof AudioContext;
  NordRelayPluginPanels?: WebuiRecord;
}

declare const state: DashboardState;
declare const activityPager: WebuiPager;
declare const artifactPager: WebuiPager;
declare const auditPager: WebuiPager;
declare const jobsPager: WebuiPager;
declare const logPager: WebuiPager;
declare const sessionsPager: WebuiPager;

declare function accessCopyButton(value: unknown, label?: string): string;
declare function activeSourceLabel(value: unknown): string;
declare function activeChatTab(): WebuiChatTab | null;
declare function adminDialog(title: string, body: string, onSubmit: () => unknown | Promise<unknown>, options?: AdminDialogOptions): void;
declare function api<P extends import("./core/api-client-types.js").WebApiPath>(path: P, options?: import("./core/api-client-types.js").WebApiClientOptions<P> & { local?: boolean }): Promise<import("./core/api-client-types.js").WebApiClientResponse<P>>;
declare function apiPeer<P extends import("./core/api-client-types.js").WebApiPath>(peerId: string, path: P, options?: import("./core/api-client-types.js").WebApiClientOptions<P>): Promise<import("./core/api-client-types.js").WebApiClientResponse<P>>;
declare function appendMessage(role: string, text: string, options?: WebuiAppendMessageOptions): HTMLElement | void;
declare function appendQueuedMessage(queueId: string, correlationId?: string | null): void;
declare function applyAccountChrome(auth?: WebuiAuth | null): void;
declare function applyHeaderPeerSnapshot(peers: WebuiPeerState | null, bootstrap: WebuiBootstrap | null): void;
declare function applyPermissions(root?: Element | Document): void;
declare function applyThemePreference(preference: unknown, options?: { persist?: boolean }): void;
declare function attr(value: unknown): string;
declare function apiFetchFailureStatus(target?: unknown): WebuiApiStateStatus;
declare function apiResponseFailureStatus(response: Response, message: string, target?: unknown): WebuiApiStateStatus | null;
declare function createApiStateError(status: WebuiApiStateStatus, message: string, options?: WebuiApiStateTransition): Error;
declare function defaultApiStateEntry(target: string): WebuiApiStateEntry;
declare function artifactDeliverySelect(id: string, selected?: string, label?: string, inherit?: string): string;
declare function bindAccessCopyButtons(root?: Element | Document): void;
declare let bindAccessTabs: () => void;
declare function bindDiscordChannelButtons(root?: Element | Document): void;
declare function bindSlackChannelButtons(root?: Element | Document): void;
declare function bindSlackUserButtons(root?: Element | Document): void;
declare function bindTableActionMenus(root?: Document | Element): void;
declare function bindUiCopyButtons(root?: Element | Document): void;
declare function bindPluginPanelSurface(surface: HTMLElement, item: WebuiRecord, result: WebuiRecord, input?: WebuiRecord): void;
declare function bindUiTraceButtons(root?: Element | Document): void;
declare let bindUserButtons: (root?: Element | Document) => void;
declare function can(permission: string): boolean;
declare function card(title: string, rows?: WebuiRows, options?: UiCardOptions): string;
declare function closeChatMoreMenu(): void;
declare function closeCompactControlMenus(except?: Element | null): void;
declare function clearStickyToast(): void;
declare function clearCurrentChatWorkingState(): void;
declare function codexPermissionId(session?: WebuiSessionSnapshot): string;
declare function codexPermissionMenuItems(controls?: WebuiControls, session?: WebuiSessionSnapshot, selectedLaunch?: string): Array<{ value: string; label: string }>;
declare function connectEvents(): void;
declare function syncChatEventStreamForActiveContext(): boolean;
declare function setLocalTurnFromCurrentChat(at?: string): void;
declare function startChatHistoryFollowup(): void;
declare function upsertOptimisticChatMessage(message: WebuiChatMessage): void;
declare function removeChatMessageForCorrelation(correlationId: string): void;
declare function webProxyContextKey(path: string, method?: WebApiMethod, body?: WebuiRecord, query?: Record<string, string | string[]>, explicitContextKey?: string, peerId?: string): string;
declare function webProxyEventContextKey(): string;
declare function activeChatTabApiOptions<P extends import("./core/api-client-types.js").WebApiPath>(options?: import("./core/api-client-types.js").WebApiClientOptions<P>): import("./core/api-client-types.js").WebApiClientOptions<P>;
declare function activeChatTabContextKey(): string;
declare function copyText(value: string, label?: string): void;
declare function currentChatPeerId(): string;
declare function currentChatWorkingSession(): WebuiRecord | null;
declare function cssEscape(value: string): string;
declare function cleanupPluginPanelSurface(surface: HTMLElement | null): void;
declare function cleanupPluginPanelSurfaces(root?: ParentNode): void;
declare function csv(value: unknown): string;
declare function csvToList(value: string): string[];
declare function disabledAttr(permission?: string): string;
declare function discordChannelLabel(value: Partial<WebuiChannelRecord>): string;
declare function discordScopeLabel(value: unknown): string;
declare function downloadBase64(name: string, data: string, mimeType?: string): void;
declare function downloadJson(name: string, value: unknown): void;
declare function downloadTextFile(name: string, text: string, mimeType?: string): void;
declare function bindWorktreeReviewCenter(): void;
declare function collectWorktreeResolutions(root?: Element | Document | null): WebuiRecord[];
declare function exportWorktreeBundle(ids: string[]): Promise<void>;
declare function isWorktreeReviewSelected(id: string): boolean;
declare function openWorktreeResolverPreview(ids: string[]): Promise<void>;
declare function selectedWorktreeIds(): string[];
declare function sessionCell(label: string, html: string, cls?: string): string;
declare function splitDiff(text: string): string;
declare function structuredDiffToUnified(file: WebuiRecord): string;
declare function worktreePreviewSourcesTable(preview: WebuiRecord): string;
declare function worktreeResolutionControls(item: WebuiRecord, preview: WebuiRecord): string;
declare function worktreeSourceName(source: unknown, preview: WebuiRecord): string;
declare function worktreeStatusClass(status: string): string;
declare function worktreeVersionPreviews(item: WebuiRecord): string;
declare function toggleNotifications(): Promise<void>;
declare function toggleCompletionSound(): Promise<void>;
declare function esc(value: unknown): string;
declare function fmtAge(value: number): string;
declare function finishBootstrapNavigation(): Promise<void>;
declare function headerTargetRequest(peerId: string, requestPath: string, options?: WebuiRecord): Promise<WebuiRecord>;
declare function shouldRefreshActiveSessions(): boolean;
declare function ensureChatTabs(): WebuiChatTab[];
declare function ensureActiveChatTabSelected(): Promise<boolean>;
declare function syncCurrentSessionChatTab(options?: { activate?: boolean }): WebuiChatTab | null;
declare function upsertChatTab(tab: Partial<WebuiChatTab>, options?: { activate?: boolean }): WebuiChatTab | null;
declare function pruneMirroredLocalSnapshotChatTabs(local?: WebuiBootstrap | null): void;
declare function syncActiveSessionsRefresh(): void;
declare function fmtBytes(value: number): string;
declare function fmtDate(value: unknown): string;
declare function fmtDuration(value: unknown): string;
declare function fmtRelativeAgo(value: unknown): string;
declare function fmtSessionAge(value: unknown): string;
declare function groupNames(groups?: unknown): string;
declare function groupOptions(selected?: string[]): string;
declare const HEADER_TARGET_PEER_TIMEOUT_MS: number;
declare function headerTargetName(peerId: string): string;
declare function markHeaderTargetError(peerId: string, error: unknown): void;
declare function handleUiError(error: unknown): void;
declare function chatTabFromActiveSession(session: WebuiActiveSession): WebuiChatTab | null;
declare function isApiStateError(error: unknown): error is Error & { apiStatus: WebuiApiStateStatus; apiTarget: string };
declare function isCliDoneStatus(value: unknown): boolean;
declare function isCliRunningStatus(value: unknown): boolean;
declare function isMonitorTabActive(tab?: string): boolean;
declare function jobStatusClass(status: string): string;
declare function loadingHtml(text: string): string;
declare function pluginPanelExtractExecutableHtml(html: string): { html: string; scripts: WebuiRecord[]; styles: WebuiRecord[] };
declare function pluginPanelInlineHtml(html: string, title: string, options?: WebuiRecord, className?: string): string;
declare function loadAccess(): Promise<void>;
declare function loadActiveSessions(options?: { silent?: boolean; fresh?: boolean }): Promise<void>;
declare function loadActivity(reset?: boolean): Promise<void>;
declare function loadAdapterHealth(): Promise<void>;
declare function loadArtifacts(reset?: boolean): Promise<void>;
declare function loadAudit(reset?: boolean): Promise<void>;
declare function loadBootstrap(options?: WebuiRecord): Promise<WebuiBootstrap>;
declare function loadHeaderTargetCandidates(local: WebuiBootstrap): Promise<void>;
declare function loadChatHistory(options?: { forceScroll?: boolean; preserveScrollOffset?: boolean; skipIfRendered?: boolean }): Promise<boolean>;
declare function loadDiagnostics(): Promise<void>;
declare function loadLogs(reset?: boolean): Promise<void>;
declare function loadMetrics(options?: { silent?: boolean }): Promise<void>;
declare function createWebCorrelationId(): string;
declare function loadMonitor(): Promise<void>;
declare function loadPeers(): Promise<void>;
declare function loadPlugins(): Promise<void>;
declare function loadPluginPanelNav(): Promise<void>;
declare function loadPluginPanelPage(): Promise<void>;
declare function stopPeerTableRefresh(): void;
declare function loadQueue(options?: WebuiRecord): Promise<void>;
declare function loadQueuePlanner(): Promise<void>;
declare function queueActionRequest(peerId: string, action: string, id?: string): Promise<WebuiRecord>;
declare function queueBulkAction(action: string): Promise<void>;
declare function loadSessions(reset?: boolean, agentId?: string): Promise<void>;
declare function loadSessionDetail(threadId: string, agentId?: string): Promise<void>;
declare function loadSettings(): Promise<void>;
declare function loadTasks(reset?: boolean): Promise<void>;
declare function loadVersion(options?: { quiet?: boolean; refreshJobs?: boolean }): Promise<void>;
declare function loadWorkflows(): Promise<void>;
declare function loadWorktrees(): Promise<void>;
declare function metricKvCard(title: string, rows?: WebuiRows): string;
declare function modelLabel(value: WebuiModelOption): string;
declare function normalizeThemePreference(value: unknown): string;
declare function openChatDialog(value?: WebuiRecord): void;
declare function openChatSession(tab: Partial<WebuiChatTab>, options?: { navigate?: boolean; loadHistory?: boolean; reload?: boolean; toast?: boolean }): Promise<void>;
declare function openDiscordChannelDialog(value?: WebuiChannelRecord): void;
declare function openDiscordLinkDialog(value?: unknown): void;
declare let openGroupDialog: (value?: WebuiAccessGroup) => void;
declare function openPasswordDialog(value?: unknown): void;
declare function openProfileDialog(): void;
declare function openSlackLinkDialog(value?: unknown): void;
declare function openMatrixLinkDialog(value?: unknown): void;
declare function openMatrixRoomDialog(value?: WebuiChannelRecord): void;
declare function openTelegramLinkDialog(value?: unknown): void;
declare function openTrace(correlationId: string): Promise<void>;
declare function openUserDialog(value?: WebuiUserRecord): void;
declare function page(name: string, options?: { persist?: boolean }): void;
declare function populateNewSessionForm(agents?: string[]): void;
declare function currentPluginPanelNonce(): string;
declare function pluginPanelPageTitle(): string;
declare function reloadCurrentPage(options?: { agentId?: string }): Promise<void>;
declare function renderAccessTab(tab?: string): void;
declare function renderActiveSessions(value?: WebuiActiveSession[]): void;
declare function updateActiveSessionsCount(value?: WebuiActiveSession[] | number): void;
declare function renderActivity(value?: WebuiRecord[]): void;
declare function renderAgentUpdateJobs(): void;
declare function renderArtifacts(value?: WebuiRecord[]): void;
declare function renderAudit(value?: WebuiAuditEvent[]): void;
declare function renderChatMessages(value?: WebuiChatMessage[], options?: { forceScroll?: boolean; preserveScrollOffset?: boolean }): void;
declare function renderPromptHistorySidebar(): void;
declare function renderChatTabs(): void;
declare function renderChatWorkspaceLine(): void;
declare let renderDiscordChannels: (channels?: WebuiChannelRecord[]) => void;
declare function renderHeaderTargetMenu(snapshot: WebuiSnapshot | null): void;
declare function renderHeaderTargetMenuIfClosed(snapshot: WebuiSnapshot | null): boolean;
declare function renderPageTitle(name?: string): void;
declare function renderApiState(): void;
declare function renderChatWorkingIndicator(): void;
declare function restoreActiveChatTabDraft(): void;
declare function renderIncrementalHtml<T>(target: string | Element, items: readonly T[], options: RenderIncrementalOptions<T>): void;
declare function renderIncrementalTable<T>(target: string | Element, items: readonly T[], options: RenderIncrementalOptions<T>): void;
declare function renderQueue(queue?: unknown, paused?: boolean, options?: WebuiRecord): void;
declare function renderSessionControls(value?: WebuiRecord): void;
declare function renderSettings(): void;
declare let renderSlackChannels: (channels?: WebuiChannelRecord[]) => void;
declare function renderSnapshot(value?: WebuiSnapshot | null): void;
declare function mergeHeaderTargetBootstrap(peerId: string, bootstrap: WebuiBootstrap): void;
declare function refreshRemoteHeaderTargets(local: WebuiBootstrap, selectedData: WebuiBootstrap): Promise<void>;
declare let renderUserManagement: (value?: WebuiUserManagement) => void;
declare function safe(fn: () => unknown | Promise<unknown>, event?: Event): void;
declare function savedThemePreference(): string;
declare function saveActiveChatTabDraft(): void;
declare function scrollChatToBottom(options?: { force?: boolean }): void;
declare function setLoading(id: string, text: string): void;
declare function syncPluginPanelThemes(): void;
declare function setApiState(status: WebuiApiStateStatus, options?: WebuiApiStateTransition): WebuiApiStateEntry;
declare function setConnection(text: string, kind: string): void;
declare function settingLabel(setting: WebuiRecord): string;
declare function syncNavSections(): void;
declare function short(value: unknown, length?: number): string;
declare function shortMiddle(value: unknown, head?: number, tail?: number): string;
declare function selectedValues(selector: string): string[];
declare function startActivityAgeCounter(): void;
declare function startActiveSessionsRefresh(): void;
declare function startSessionAgeCounter(): void;
declare function stopActivityAgeCounter(): void;
declare function stopActiveSessionsRefresh(): void;
declare function tableActionMenuHtml(buttons: string[] | string, options?: TableActionMenuOptions): string;
declare function currentOpenTableActionMenuId(selector?: string): string;
declare function restoreTableActionMenu(menuId: unknown, selector?: string): void;
declare function updateSessionAgeCounters(): void;
declare let switchAccessTab: (tab?: string) => void;
declare function slackChannelLabel(value: Partial<WebuiChannelRecord>): string;
declare function slackScopeLabel(value: unknown): string;
declare function toast(message: string, options?: { duration?: number; sticky?: boolean }): void;
declare function uiBadge(text: string, status?: string): string;
declare function uiButton(label: string, options?: UiButtonOptions): string;
declare function uiCard(title: string, rows?: WebuiRows, options?: UiCardOptions): string;
declare function uiCopyButton(value: unknown, label?: string, className?: string): string;
declare function uiEmpty(text: string): string;
declare function uiItem(title: string, options?: UiItemOptions): string;
declare function uiTraceControls(correlationId: string): string;
declare function recordApiSuccess(target?: unknown): void;
declare function upsertAgentUpdateJob(job: WebuiRecord): void;
declare function updateSnapshotQueue(queue?: WebuiRecord[], paused?: boolean): void;
declare function updateCurrentChatQueue(queue?: WebuiRecord[], paused?: boolean): void;
declare function updateQueueNavBadge(queue?: WebuiRecord[] | number): void;
declare function queuedQueueItems(queue?: WebuiRecord[]): WebuiRecord[];
declare function queuedQueueCount(queue?: WebuiRecord[]): number;
declare function val(id: string): string;
declare function versionStatusClass(status: string): string;
declare function versionStatusLabel(status: string): string;
declare function renderWorkflowBuilder(): void;
declare function validateWorkflowBuilder(): string[];
declare function workflowBuilderState(workflow?: WebuiRecord): WebuiWorkflowBuilderState;
declare function workflowBuilderStepsPayload(collect?: boolean): WebuiWorkflowBuilderStep[];
declare function workflowVariableDefinitions(items: WebuiRecord[]): WebuiRecord[];
declare function writeStoredPluginPanelPage(value?: WebuiRecord | null): void;
