interface Element {
  [key: string]: any;
}

interface EventTarget {
  [key: string]: any;
}

declare const state: any;
declare const activityPager: any;
declare const artifactPager: any;
declare const auditPager: any;
declare const jobsPager: any;
declare const sessionsPager: any;

declare function accessCopyButton(value: any, label?: string): string;
declare function activeSourceLabel(value: any): string;
declare var adminDialog: (...args: any[]) => any;
declare function api(path: string, options?: any): Promise<any>;
declare var apiPeer: (...args: any[]) => Promise<any>;
declare function appendMessage(role: string, text: string, options?: any): void;
declare function appendQueuedMessage(queueId: string, text: string, options?: any): void;
declare var applyAccountChrome: (...args: any[]) => any;
declare function applyHeaderPeerSnapshot(peers: any, bootstrap: any): void;
declare function applyPermissions(root?: any): void;
declare var applyThemePreference: (...args: any[]) => any;
declare function attr(value: any): string;
declare function bindAccessCopyButtons(root?: any): void;
declare var bindAccessTabs: (...args: any[]) => any;
declare function bindDiscordChannelButtons(root?: any): void;
declare function bindSlackChannelButtons(root?: any): void;
declare function bindSlackUserButtons(root?: any): void;
declare function bindUiCopyButtons(root?: any): void;
declare function bindUiTraceButtons(root?: any): void;
declare var bindUserButtons: (...args: any[]) => any;
declare function can(permission: string): boolean;
declare function card(title: string, rows?: any[], options?: any): string;
declare function clearStickyToast(): void;
declare function connectEvents(): void;
declare function copyText(value: string, label?: string): void;
declare function cssEscape(value: string): string;
declare function csv(value: any): string;
declare function csvToList(value: string): string[];
declare function disabledAttr(permission?: string): string;
declare function discordChannelLabel(value: any): string;
declare function discordScopeLabel(value: any): string;
declare function downloadBase64(name: string, data: string, mimeType?: string): void;
declare function downloadJson(name: string, value: any): void;
declare function enableNotifications(): Promise<void>;
declare function esc(value: any): string;
declare function fmtAge(value: any): string;
declare function fmtBytes(value: any): string;
declare function fmtDate(value: any): string;
declare function fmtDuration(value: any): string;
declare function fmtRelativeAgo(value: any): string;
declare function fmtSessionAge(value: any): string;
declare function groupNames(groups?: any): string;
declare function isCliDoneStatus(value: any): boolean;
declare function isCliRunningStatus(value: any): boolean;
declare function isMonitorTabActive(tab?: string): boolean;
declare function jobStatusClass(status: string): string;
declare function loadingHtml(text: string): string;
declare var loadAccess: (...args: any[]) => Promise<any>;
declare var loadActiveSessions: (...args: any[]) => Promise<any>;
declare var loadActivity: (...args: any[]) => Promise<any>;
declare var loadAdapterHealth: (...args: any[]) => Promise<any>;
declare var loadArtifacts: (...args: any[]) => Promise<any>;
declare var loadAudit: (...args: any[]) => Promise<any>;
declare function loadBootstrap(): Promise<any>;
declare var loadChatHistory: (...args: any[]) => Promise<any>;
declare function loadDiagnostics(): Promise<void>;
declare function loadLogs(): Promise<void>;
declare function loadMetrics(): Promise<void>;
declare function loadMirrorPreference(): Promise<void>;
declare function loadMonitor(): Promise<void>;
declare function loadPeers(): Promise<void>;
declare function loadQueue(): Promise<void>;
declare var loadQueuePlanner: (...args: any[]) => Promise<any>;
declare var loadSessions: (...args: any[]) => Promise<any>;
declare var loadSessionDetail: (...args: any[]) => Promise<any>;
declare function loadSettings(): Promise<void>;
declare function loadTasks(reset?: boolean): Promise<void>;
declare function loadVersion(): Promise<void>;
declare function loadWorkflows(): Promise<void>;
declare function loadWorktrees(): Promise<void>;
declare function metricKvCard(title: string, rows?: any[]): string;
declare function modelLabel(value: any): string;
declare function normalizeThemePreference(value: any): string;
declare function openChatDialog(value?: any): void;
declare function openDiscordChannelDialog(value?: any): void;
declare function openDiscordLinkDialog(value?: any): void;
declare var openGroupDialog: (...args: any[]) => any;
declare function openPasswordDialog(value?: any): void;
declare function openProfileDialog(): void;
declare function openSlackLinkDialog(value?: any): void;
declare function openTelegramLinkDialog(value?: any): void;
declare function openTrace(correlationId: string): Promise<void>;
declare function openUserDialog(value?: any): void;
declare function page(name: string): void;
declare var populateNewSessionForm: (...args: any[]) => any;
declare var reloadCurrentPage: (...args: any[]) => Promise<any>;
declare function renderAccessTab(tab?: string): void;
declare function renderActiveSessions(value?: any): void;
declare function renderActivity(value?: any): void;
declare function renderAgentUpdateJobs(): void;
declare function renderArtifacts(value?: any): void;
declare function renderAudit(value?: any): void;
declare function renderChatMessages(value?: any): void;
declare var renderDiscordChannels: (...args: any[]) => any;
declare function renderHeaderTargetMenu(snapshot: any): void;
declare var renderChatWorkingIndicator: (...args: any[]) => any;
declare var renderQueue: (...args: any[]) => any;
declare function renderSessionControls(value?: any): void;
declare function renderSettings(): void;
declare var renderSlackChannels: (...args: any[]) => any;
declare function renderSnapshot(value?: any): void;
declare var renderUserManagement: (...args: any[]) => any;
declare function safe(fn: (...args: any[]) => any, event?: any): void;
declare function savedThemePreference(): string;
declare function scrollChatToBottom(options?: any): void;
declare function setLoading(id: string, text: string): void;
declare function settingLabel(setting: any): string;
declare function short(value: any, length?: number): string;
declare function shortMiddle(value: any, head?: number, tail?: number): string;
declare function startActivityAgeCounter(): void;
declare function startSessionAgeCounter(): void;
declare function stopActivityAgeCounter(): void;
declare var switchAccessTab: (...args: any[]) => any;
declare function slackChannelLabel(value: any): string;
declare function slackScopeLabel(value: any): string;
declare function toast(message: string, options?: any): void;
declare function uiBadge(text: string, status?: string): string;
declare function uiButton(label: string, options?: any): string;
declare function uiCard(title: string, rows?: any[], options?: any): string;
declare function uiCopyButton(value: any, label?: string, className?: string): string;
declare function uiEmpty(text: string): string;
declare function uiItem(title: string, options?: any): string;
declare function uiTraceControls(correlationId: string): string;
declare function upsertAgentUpdateJob(job: any): void;
declare function val(id: string): string;
declare function versionStatusClass(status: string): string;
declare function versionStatusLabel(status: string): string;
