let selectedFiles=[];
function renderSelectedFiles(){const summary=document.getElementById('fileSummary');if(selectedFiles.length===0){summary.textContent='No files selected';return}const names=selectedFiles.slice(0,3).map(f=>f.name || 'file').join(', ');const more=selectedFiles.length>3?' +'+(selectedFiles.length-3)+' more':'';const bytes=selectedFiles.reduce((sum,file)=>sum+file.size,0);summary.textContent=names+more+' ('+fmtBytes(bytes)+')'}
function addFiles(files){selectedFiles=selectedFiles.concat(Array.from(files||[]));renderSelectedFiles()}
async function filePayload(file){return {name:file.name || 'upload',mimeType:file.type || 'application/octet-stream',dataBase64:await fileToBase64(file)}}
async function fileToBase64(file){const buffer=await file.arrayBuffer();const bytes=new Uint8Array(buffer);let binary='';const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk){binary+=String.fromCharCode(...bytes.subarray(i,i+chunk))}return btoa(binary)}
document.getElementById('fileInput').onchange=e=>{if(!can('files.write')){toast('Permission required: files.write');return}addFiles(e.target.files)};
document.getElementById('clearFilesBtn').onclick=()=>{selectedFiles=[];document.getElementById('fileInput').value='';renderSelectedFiles()};
document.addEventListener('paste',e=>{const files=Array.from(e.clipboardData?.files||[]);if(files.length){if(!can('files.write')){toast('Permission required: files.write');return}addFiles(files);toast('Pasted '+files.length+' file(s)')}});
document.addEventListener('dragover',e=>{e.preventDefault();document.body.classList.add('drop-active')});
document.addEventListener('dragleave',()=>document.body.classList.remove('drop-active'));
document.addEventListener('drop',e=>{e.preventDefault();document.body.classList.remove('drop-active');const files=Array.from(e.dataTransfer?.files||[]);if(files.length){if(!can('files.write')){toast('Permission required: files.write');return}addFiles(files);toast('Added '+files.length+' dropped file(s)')}});
document.getElementById('promptForm').onsubmit=e=>safe(async()=>{e.preventDefault();const input=document.getElementById('promptInput');const text=input.value.trim();if(/^\/mirror\b/i.test(text)){if(selectedFiles.length){toast('/mirror cannot be sent with attachments');return}const argument=text.replace(/^\/mirror\b/i,'').trim();if(argument&&!can('settings.write')){toast('Permission required: settings.write');return}if(!argument&&!can('sessions.read')){toast('Permission required: sessions.read');return}input.value='';const data=argument?await setMirrorPreference(argument):await loadMirrorPreference();appendMessage('system',data?.response?.plain||('CLI mirroring: '+(data?.mode||'-')));return}if(!can('prompt.send')){toast('Permission required: prompt.send');return}if(selectedFiles.length&&!can('files.write')){toast('Permission required: files.write');return}if(!text&&selectedFiles.length===0)return;const files=selectedFiles;input.value='';selectedFiles=[];document.getElementById('fileInput').value='';renderSelectedFiles();const payloadFiles=files.length?await Promise.all(files.map(filePayload)):[];const r=files.length?await api('/api/prompt/upload',{method:'POST',body:JSON.stringify({text,files:payloadFiles})}):await api('/api/prompt',{method:'POST',body:JSON.stringify({text})});if(r.transcribeOnly)appendMessage('system','Transcribed audio:\n'+(r.transcript||'(empty)'));else if(r.queued)appendQueuedMessage(r.queueId)},e);
document.getElementById('newSessionBtn').onclick=()=>{if(!can('sessions.write')){toast('Permission required: sessions.write');return}openNewSessionDialog()};
document.getElementById('retryBtn').onclick=()=>safe(async()=>{if(!can('prompt.send')){toast('Permission required: prompt.send');return}const r=await api('/api/retry',{method:'POST'});toast(r.queued?'Retry queued '+r.queueId:'Retry started')});
document.getElementById('editLastBtn').onclick=()=>{const last=[...(state.chatMessages||[])].reverse().find(m=>m.role==='user');if(last){document.getElementById('promptInput').value=last.text;document.getElementById('promptInput').focus()}else toast('No user prompt found')};
document.getElementById('syncBtn').onclick=()=>safe(async()=>{if(!can('sessions.write')){toast('Permission required: sessions.write');return}const r=await api('/api/sync',{method:'POST'});toast(r.changed?'Synced: '+(r.changedFields||[]).join(', '):'Already in sync');loadBootstrap()});
document.getElementById('notifyBtn').onclick=()=>enableNotifications();
document.getElementById('mirrorModeSelect').onchange=()=>safe(async()=>{if(!can('settings.write')){toast('Permission required: settings.write');renderMirrorPreference(state.webMirror);return}await setMirrorPreference(document.getElementById('mirrorModeSelect').value)});
document.getElementById('clearChatBtn').onclick=()=>safe(async()=>{if(!can('sessions.write')){toast('Permission required: sessions.write');return}if(confirm('Clear chat history for the current thread?')){const r=await api('/api/chat/history',{method:'DELETE'});renderChatMessages(r.messages||[]);toast('Removed '+r.removed+' messages')}});
document.getElementById('abortBtn').onclick=()=>safe(async()=>{if(!can('prompt.abort')){toast('Permission required: prompt.abort');return}await api('/api/abort',{method:'POST'});toast('Abort sent')});
document.getElementById('handbackBtn').onclick=()=>safe(async()=>{if(!can('sessions.write')){toast('Permission required: sessions.write');return}const r=await api('/api/handback',{method:'POST'});appendMessage('system','Handback command:\n'+(r.command||'No command available'))});
document.getElementById('recordBtn').onclick=()=>safe(async()=>{if(!can('files.write')){toast('Permission required: files.write');return}const btn=document.getElementById('recordBtn');if(state.mediaRecorder&&state.mediaRecorder.state==='recording'){state.mediaRecorder.stop();btn.textContent='Record voice';return}const stream=await navigator.mediaDevices.getUserMedia({audio:true});state.recordedChunks=[];state.mediaRecorder=new MediaRecorder(stream);state.mediaRecorder.ondataavailable=e=>{if(e.data.size>0)state.recordedChunks.push(e.data)};state.mediaRecorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(state.recordedChunks,{type:'audio/webm'});addFiles([new File([blob],'voice-note.webm',{type:'audio/webm'})]);toast('Voice note attached')};state.mediaRecorder.start();btn.textContent='Stop recording'});
function renderMirrorPreference(data){if(!data)return;state.webMirror=data;const select=document.getElementById('mirrorModeSelect');if(select&&data.mode)select.value=data.mode}
async function loadMirrorPreference(){if(!can('sessions.read'))return null;const data=await api('/api/chat/mirror');renderMirrorPreference(data);return data}
async function setMirrorPreference(argument){const data=await api('/api/chat/mirror',{method:'POST',body:JSON.stringify({argument})});renderMirrorPreference(data);toast('Mirror '+data.mode);return data}
function renderNewSessionControls(c){const s=state.snapshot?.session||{};const caps=c.capabilities||{};document.getElementById('workspaceOptions').innerHTML=(c.workspaces||[]).map(w=>'<option value="'+attr(w)+'"></option>').join('');document.getElementById('newModel').innerHTML='<option value="">Default</option>'+((c.models||[]).map(m=>'<option value="'+attr(m.slug)+'">'+esc(modelLabel(m))+'</option>').join(''));document.getElementById('newModel').parentElement.style.display=caps.modelSelection?'grid':'none';const reasoningWrap=document.getElementById('newReasoningWrap');reasoningWrap.firstChild.nodeValue=(c.reasoningLabel||'Reasoning');reasoningWrap.style.display=caps.reasoningSelection?'grid':'none';document.getElementById('newReasoning').innerHTML='<option value="">Default</option>'+((c.reasoningOptions||[]).map(v=>'<option value="'+attr(v)+'">'+esc(v)+'</option>').join(''));document.getElementById('newLaunch').innerHTML='<option value="">Default</option>'+((c.launchProfiles||[]).map(p=>'<option value="'+attr(p.id)+'">'+esc(p.label+' - '+p.behavior)+'</option>').join(''));document.getElementById('newFast').checked=Boolean(s.fastMode&&caps.fastMode);document.getElementById('newLaunchWrap').style.display=caps.launchProfiles?'grid':'none';document.getElementById('newFastWrap').style.display=caps.fastMode?'inline-flex':'none'}
function populateNewSessionForm(agents){const s=state.snapshot?.session||{};const agentSelect=document.getElementById('newAgent');agentSelect.innerHTML=(agents||[]).map(a=>'<option value="'+attr(a)+'" '+(a===s.agentId?'selected':'')+'>'+esc(a)+'</option>').join('');agentSelect.value=s.agentId||agentSelect.value;document.getElementById('newWorkspace').value=s.workspace||'';state.newSessionControls=state.controls||{};renderNewSessionControls(state.newSessionControls);agentSelect.onchange=()=>safe(async()=>{state.newSessionControls=await api('/api/control-options',{query:{agent:agentSelect.value}});renderNewSessionControls(state.newSessionControls)})}
function openNewSessionDialog(){populateNewSessionForm(state.enabledAgents);document.getElementById('newSessionDialog').showModal()}
document.getElementById('newSessionForm').onsubmit=e=>safe(async()=>{e.preventDefault();if(!can('sessions.write')){toast('Permission required: sessions.write');return}const payload={agentId:val('newAgent'),workspace:val('newWorkspace')||undefined,model:val('newModel')||undefined,reasoningEffort:val('newReasoning')||undefined,launchProfileId:val('newLaunch')||undefined,fastMode:document.getElementById('newFast').checked};await api('/api/sessions/new',{method:'POST',body:JSON.stringify(payload)});document.getElementById('newSessionDialog').close();toast('New session started');await loadBootstrap();await loadChatHistory({forceScroll:true})},e);
document.getElementById('cancelSessionBtn').onclick=()=>document.getElementById('newSessionDialog').close();
function val(id){return document.getElementById(id).value.trim()}
function activeAgentId(){return state.snapshot?.session?.agentId||document.getElementById('agentSelect').value||''}
async function loadSessions(reset=true,agentId){if(reset)sessionsPager.reset();const expectedAgent=agentId||activeAgentId();const requestId=++state.sessionsRequestId;setLoading('sessionsList','Loading '+(expectedAgent||'agent')+' sessions...');const q=document.getElementById('sessionSearch').value||'';const data=await api('/api/sessions',{query:{query:q,page:sessionsPager.page,limit:sessionsPager.pageSize,agent:expectedAgent||undefined}});if(requestId!==state.sessionsRequestId||expectedAgent!==activeAgentId())return;document.getElementById('sessionsList').innerHTML=data.sessions.map(s=>'<div class="item"><strong title="'+attr(s.title||s.firstUserMessage||s.id)+'">'+esc(short(s.title||s.firstUserMessage||s.id))+'</strong><small><button type="button" class="copy-id" data-copy-id="'+attr(s.id)+'" title="Copy thread ID">'+esc(short(s.id,64))+'</button> / '+esc(short((s.cwd||'')+' / '+fmtDate(s.updatedAt)))+'</small><div class="row"><button data-switch="'+attr(s.id)+'"'+disabledAttr('sessions.write')+'>Switch</button><button class="secondary" data-session-detail="'+attr(s.id)+'">Details</button></div></div>').join('')||'<div class="item">No sessions found.</div>';sessionsPager.render(data.pagination||{});document.querySelectorAll('[data-copy-id]').forEach(b=>b.onclick=()=>copyText(b.dataset.copyId||'','Thread ID copied'));document.querySelectorAll('[data-switch]').forEach(b=>b.onclick=()=>safe(async()=>{if(!can('sessions.write')){toast('Permission required: sessions.write');return}await api('/api/sessions/switch',{method:'POST',body:{threadId:b.dataset.switch}});toast('Session switched');loadBootstrap()}));document.querySelectorAll('[data-session-detail]').forEach(b=>b.onclick=()=>safe(()=>loadSessionDetail(b.dataset.sessionDetail)));applyPermissions()}
function usageRows(rows){return (rows||[]).map(row=>{if(Array.isArray(row))return [row[0],row[1]];const text=String(row);const index=text.indexOf(':');return index>0?[text.slice(0,index),text.slice(index+1).trim()]:[text,'']})}
function detailSection(title,count,body){return '<details class="session-detail-section"><summary>'+esc(title+' ('+count+')')+'</summary><div class="list">'+(body||'<div class="item">No entries.</div>')+'</div></details>'}
async function loadSessionDetail(threadId){const d=await api('/api/sessions/detail',{query:{threadId}});const r=d.record||{};const messages=d.messages||[];const activity=d.activity||[];const metadataRows=[['Thread',threadId],['Agent',r.agentId],['Title',r.title],['Workspace',r.cwd],['Model',r.model],['Reasoning',r.reasoningEffort],['Updated',fmtDate(r.updatedAt)],['Path',r.sessionPath]].concat(usageRows(d.usageRows));const messageItems=messages.slice(-20).map(m=>'<div class="item"><strong>'+esc(m.role+' / '+fmtDate(m.timestamp))+'</strong><small>'+esc(short(m.text,500))+'</small></div>').join('');const activityItems=activity.map(e=>'<div class="item"><strong>'+esc(e.status+' / '+e.type+' / '+fmtDate(e.timestamp))+'</strong><small>'+esc(short(e.prompt||e.detail||'',300))+'</small></div>').join('');document.getElementById('sessionDetail').innerHTML='<h2>Session detail</h2>'+card('Metadata',metadataRows)+detailSection('Recent messages',messages.length,messageItems)+detailSection('Activity',activity.length,activityItems);document.getElementById('sessionDetailDialog').showModal()}
document.getElementById('closeSessionDetailBtn').onclick=()=>document.getElementById('sessionDetailDialog').close();
document.getElementById('sessionSearchBtn').onclick=()=>loadSessions(true);document.getElementById('sessionSearch').addEventListener('keydown',e=>{if(e.key==='Enter')loadSessions(true)});document.getElementById('attachBtn').onclick=async()=>{if(!can('sessions.write')){toast('Permission required: sessions.write');return}const threadId=document.getElementById('attachInput').value.trim();if(threadId){await api('/api/sessions/attach',{method:'POST',body:JSON.stringify({threadId})});toast('Session attached');loadBootstrap()}};
function renderQueue(queue,paused){document.getElementById('queueStatus').textContent=paused?'Paused':'Running';document.getElementById('queueList').innerHTML=(queue||[]).map((q,i)=>'<div class="item queue-item" draggable="true" data-queue-id="'+attr(q.id)+'"><strong>'+esc((i+1)+'. '+q.id+' - '+q.description)+'</strong><small>Created '+fmtDate(q.createdAt)+' / attempts '+q.attempts+(q.correlationId?' / CID: <button type="button" class="copy-id" data-copy-id="'+attr(q.correlationId)+'">'+esc(q.correlationId)+'</button>':'')+(q.lastError?' / '+esc(q.lastError):'')+'</small><div class="row"><button data-q="run" data-id="'+q.id+'"'+disabledAttr('queue.write')+'>Run</button><button data-q="top" data-id="'+q.id+'"'+disabledAttr('queue.write')+'>Top</button><button data-q="up" data-id="'+q.id+'"'+disabledAttr('queue.write')+'>Up</button><button data-q="down" data-id="'+q.id+'"'+disabledAttr('queue.write')+'>Down</button><button data-q="cancel" data-id="'+q.id+'" class="danger"'+disabledAttr('queue.write')+'>Cancel</button></div></div>').join('')||'<div class="item">Queue is empty.</div>';document.querySelectorAll('#queueList [data-copy-id]').forEach(b=>b.onclick=()=>copyText(b.dataset.copyId||'','Correlation ID copied'));document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>safe(async()=>{if(!can('queue.write')){toast('Permission required: queue.write');return}const r=await api('/api/queue',{method:'POST',body:JSON.stringify({action:b.dataset.q,id:b.dataset.id})});renderQueue(r.queue,r.paused)}));let dragged=null;document.querySelectorAll('.queue-item').forEach(item=>{item.ondragstart=()=>{if(!can('queue.write'))return;dragged=item.dataset.queueId;item.classList.add('dragging')};item.ondragend=()=>item.classList.remove('dragging');item.ondragover=e=>{if(can('queue.write'))e.preventDefault()};item.ondrop=()=>safe(async()=>{if(!can('queue.write')){toast('Permission required: queue.write');return}if(dragged&&dragged!==item.dataset.queueId){const ids=Array.from(document.querySelectorAll('.queue-item')).map(el=>el.dataset.queueId);const targetIndex=Math.max(0,ids.indexOf(item.dataset.queueId));await api('/api/queue',{method:'POST',body:JSON.stringify({action:'top',id:dragged})});for(let i=0;i<targetIndex;i++)await api('/api/queue',{method:'POST',body:JSON.stringify({action:'down',id:dragged})});const r=await api('/api/queue');renderQueue(r.queue,r.paused)}})});applyPermissions()}
document.querySelectorAll('[data-queue]').forEach(b=>b.onclick=()=>safe(async()=>{if(!can('queue.write')){toast('Permission required: queue.write');return}const r=await api('/api/queue',{method:'POST',body:JSON.stringify({action:b.dataset.queue})});renderQueue(r.queue,r.paused)}));
async function loadArtifacts(reset=true){if(reset)artifactPager.reset();setLoading('artifactList','Loading artifacts...');document.getElementById('artifactPreview').innerHTML='';const data=await api('/api/artifacts',{query:{limit:50,cursor:artifactPager.cursor||undefined}});state.artifactReports=data.reports||[];renderArtifacts();artifactPager.render(data.pagination||{})}
function artifactMatches(a,kind,query){const name=(a.name||a.relativePath||'').toLowerCase();if(query&&!name.includes(query))return false;if(kind==='images')return /\\.(png|jpe?g|gif|webp|svg)$/i.test(name);if(kind==='docs')return !/\\.(png|jpe?g|gif|webp|svg)$/i.test(name);return true}
document.getElementById('reloadArtifactsBtn').onclick=()=>loadArtifacts(true);
document.getElementById('artifactSearch').oninput=renderArtifacts;
document.getElementById('artifactKind').onchange=renderArtifacts;
document.getElementById('deleteSelectedArtifactsBtn').onclick=()=>safe(async()=>{if(!can('files.write')){toast('Permission required: files.write');return}const turnIds=[...state.selectedArtifactTurns];if(turnIds.length===0){toast('No artifact turns selected');return}if(confirm('Delete '+turnIds.length+' selected artifact turn(s)?')){const r=await api('/api/artifacts/bulk',{method:'POST',body:JSON.stringify({action:'delete',turnIds})});state.selectedArtifactTurns.clear();toast('Deleted '+(r.removed||[]).length+' artifact turn(s)');loadArtifacts()}});
function highlightCode(text){return esc(text).replace(/\\b(import|export|const|let|function|return|if|else|for|while|class|interface|type|async|await)\\b/g,'<span class="chip">$1</span>')}
function isRemotePeerTarget(){return Boolean(state.selectedPeer&&state.selectedPeer!=='local')}
function artifactFileHref(turnId,path){return isRemotePeerTarget()?'#':'/api/artifacts/file?turnId='+encodeURIComponent(turnId)+'&path='+encodeURIComponent(path)}
function artifactZipHref(turnId){return isRemotePeerTarget()?'#':'/api/artifacts/zip?turnId='+encodeURIComponent(turnId)}
async function downloadArtifactFile(turnId,path){const file=await api('/api/artifacts/file',{query:{turnId,path}});downloadBase64(file.name||path,file.dataBase64||'',file.mimeType||'application/octet-stream')}
async function downloadArtifactZip(turnId){const file=await api('/api/artifacts/zip',{query:{turnId}});downloadBase64(file.name||('nordrelay-artifacts-'+turnId+'.zip'),file.dataBase64||'',file.mimeType||'application/zip')}
async function artifactDataUrl(turnId,path){const file=await api('/api/artifacts/file',{query:{turnId,path}});return 'data:'+(file.mimeType||'application/octet-stream')+';base64,'+(file.dataBase64||'')}
function renderArtifacts(){const query=(document.getElementById('artifactSearch').value||'').toLowerCase();const kind=document.getElementById('artifactKind').value;const reports=state.artifactReports||[];document.getElementById('artifactList').innerHTML=reports.map(r=>{const files=(r.artifacts||[]).filter(a=>artifactMatches(a,kind,query));if(files.length===0)return'';const gallery=files.map(a=>{const href=artifactFileHref(r.turnId,a.relativePath);const isImage=/\.(png|jpe?g|gif|webp|svg)$/i.test(a.name);const img=isImage&&!isRemotePeerTarget()?'<img src="'+href+'">':'<pre>'+esc(a.name.split('.').pop()||'file')+'</pre>';return '<div class="artifact-card"><label><input type="checkbox" data-artifact-select="'+attr(r.turnId)+'" '+(state.selectedArtifactTurns.has(r.turnId)?'checked':'')+'> '+esc(short(a.name,32))+'</label>'+img+'<small>'+esc(fmtBytes(a.sizeBytes))+'</small><div class="row"><a href="'+href+'" data-open-artifact="'+attr(r.turnId)+'" data-open-path="'+attr(a.relativePath)+'">Open</a><button class="secondary" data-preview-turn="'+attr(r.turnId)+'" data-preview-path="'+attr(a.relativePath)+'">Preview</button></div></div>'}).join('');return '<div class="item"><strong>'+esc(r.turnId)+' - '+files.length+'/'+r.fileCount+' files - '+fmtBytes(r.totalSizeBytes)+'</strong><small>'+fmtDate(r.updatedAt)+' / '+esc(r.source||'turn')+'</small><div class="row"><a href="'+artifactZipHref(r.turnId)+'" data-zip-artifact="'+attr(r.turnId)+'">Download ZIP</a><button data-del-art="'+esc(r.turnId)+'" class="danger"'+disabledAttr('files.write')+'>Delete</button></div><div class="gallery">'+gallery+'</div></div>'}).join('')||'<div class="item">No artifacts.</div>';document.querySelectorAll('[data-artifact-select]').forEach(c=>c.onchange=()=>{if(c.checked)state.selectedArtifactTurns.add(c.dataset.artifactSelect);else state.selectedArtifactTurns.delete(c.dataset.artifactSelect)});document.querySelectorAll('[data-open-artifact]').forEach(a=>a.onclick=e=>{if(!isRemotePeerTarget())return;e.preventDefault();safe(()=>downloadArtifactFile(a.dataset.openArtifact,a.dataset.openPath))});document.querySelectorAll('[data-zip-artifact]').forEach(a=>a.onclick=e=>{if(!isRemotePeerTarget())return;e.preventDefault();safe(()=>downloadArtifactZip(a.dataset.zipArtifact))});document.querySelectorAll('[data-del-art]').forEach(b=>b.onclick=()=>safe(async()=>{if(!can('files.write')){toast('Permission required: files.write');return}if(confirm('Delete artifact turn '+b.dataset.delArt+'?')){await api('/api/artifacts',{method:'DELETE',query:{turnId:b.dataset.delArt}});state.selectedArtifactTurns.delete(b.dataset.delArt);loadArtifacts()}}));document.querySelectorAll('[data-preview-turn]').forEach(b=>b.onclick=()=>safe(()=>previewArtifact(b.dataset.previewTurn,b.dataset.previewPath)));applyPermissions()}
document.getElementById('zipSelectedArtifactsBtn').onclick=()=>{const turnIds=[...state.selectedArtifactTurns];if(turnIds.length===0){toast('No artifact turns selected');return}turnIds.forEach(turnId=>isRemotePeerTarget()?safe(()=>downloadArtifactZip(turnId)):window.open('/api/artifacts/zip?turnId='+encodeURIComponent(turnId),'_blank'))};
async function previewArtifact(turnId,path){const target=document.getElementById('artifactPreview');target.innerHTML='<div class="panel">'+loadingHtml('Loading preview...')+'</div>';target.scrollIntoView({block:'start',behavior:'smooth'});try{const data=await api('/api/artifacts/preview',{query:{turnId,path}});if(data.kind==='image'){const src=isRemotePeerTarget()?await artifactDataUrl(turnId,path):'/api/artifacts/file?turnId='+encodeURIComponent(turnId)+'&path='+encodeURIComponent(path);target.innerHTML='<div class="panel"><h2>'+esc(data.name)+'</h2><img src="'+src+'"></div>';return}if(data.kind==='text'){target.innerHTML='<div class="panel"><h2>'+esc(data.name)+' '+fmtBytes(data.sizeBytes)+'</h2><pre>'+highlightCode(data.text||'')+'</pre>'+(data.truncated?'<small>Preview truncated.</small>':'')+'</div>';return}target.innerHTML='<div class="panel"><h2>'+esc(data.name)+'</h2><p>'+esc(data.detail||'Preview unavailable')+'</p></div>'}catch(err){target.innerHTML='<div class="panel"><h2>Preview failed</h2><p>'+esc(err.message||String(err))+'</p></div>';throw err}}
