function bindWorkflowTabs(){document.querySelectorAll('[data-workflow-tab]').forEach(b=>b.onclick=()=>switchWorkflowTab(b.dataset.workflowTab))}
function switchWorkflowTab(tab){state.workflowTab=tab||'templates';document.querySelectorAll('[data-workflow-tab]').forEach(b=>{const active=b.dataset.workflowTab===state.workflowTab;b.classList.toggle('active',active);b.setAttribute('aria-selected',active?'true':'false');b.tabIndex=active?0:-1});document.querySelectorAll('[data-workflow-tab-panel]').forEach(p=>p.classList.toggle('active',p.dataset.workflowTabPanel===state.workflowTab))}
async function loadWorkflows(){bindWorkflowTabs();switchWorkflowTab(state.workflowTab||'templates');if(!can('workflows.read')){document.getElementById('templateList').innerHTML=uiEmpty('Permission required: workflows.read');return}setLoading('templateList','Loading templates...');setLoading('workflowList','Loading workflows...');setLoading('workflowRunList','Loading runs...');const [templates,workflows]=await Promise.all([api('/api/templates'),api('/api/workflows')]);state.workflowTemplates=templates.templates||[];state.workflows=workflows.workflows||[];state.workflowRuns=workflows.runs||[];renderWorkflowSections()}
function renderWorkflowSections(){renderTemplates();renderWorkflowList();renderWorkflowRuns();applyPermissions()}
function workflowFilter(value,id){const q=(document.getElementById(id)?.value||'').toLowerCase();if(!q)return true;return [value.name,value.description,(value.tags||[]).join(' '),value.id].join(' ').toLowerCase().includes(q)}
function workflowTags(tags){return (tags||[]).map(t=>'<span class="chip">'+esc(t)+'</span>').join('')}
function renderTemplates(){const list=(state.workflowTemplates||[]).filter(t=>workflowFilter(t,'templateSearch'));document.getElementById('templateList').innerHTML=list.map(t=>'<div class="item"><strong>'+esc(t.name)+' <span class="adapter-status '+(t.scope==='shared'?'enabled':'planned')+'">'+esc(t.scope)+'</span></strong><small>'+esc(short(t.description||t.prompt,260))+'</small><small>'+workflowTags(t.tags)+' '+esc((t.variables||[]).length+' variable(s) · updated '+fmtDate(t.updatedAt))+'</small><div class="row"><button data-template-run="'+attr(t.id)+'"'+disabledAttr('workflows.run')+'>Run</button><button class="secondary" data-template-insert="'+attr(t.id)+'">Insert</button><button class="secondary" data-template-preview="'+attr(t.id)+'">Preview</button><button class="secondary" data-template-edit="'+attr(t.id)+'"'+disabledAttr('workflows.write')+'>Edit</button><button class="danger" data-template-delete="'+attr(t.id)+'"'+disabledAttr('workflows.write')+'>Delete</button></div></div>').join('')||uiEmpty('No templates.');bindTemplateButtons()}
function renderWorkflowList(){const list=(state.workflows||[]).filter(w=>workflowFilter(w,'workflowSearch'));document.getElementById('workflowList').innerHTML=list.map(w=>'<div class="item"><strong>'+esc(w.name)+' <span class="adapter-status '+(w.scope==='shared'?'enabled':'planned')+'">'+esc(w.scope)+'</span></strong><small>'+esc(short(w.description||'',260))+'</small><small>'+workflowTags(w.tags)+' '+esc((w.steps||[]).length+' step(s) · updated '+fmtDate(w.updatedAt))+'</small><div class="row"><button data-workflow-run="'+attr(w.id)+'"'+disabledAttr('workflows.run')+'>Run</button><button class="secondary" data-workflow-preview="'+attr(w.id)+'">Preview</button><button class="secondary" data-workflow-edit="'+attr(w.id)+'"'+disabledAttr('workflows.write')+'>Edit</button><button class="danger" data-workflow-delete="'+attr(w.id)+'"'+disabledAttr('workflows.write')+'>Delete</button></div></div>').join('')||uiEmpty('No workflows.');bindWorkflowButtons()}
function renderWorkflowRuns(){document.getElementById('workflowRunList').innerHTML=(state.workflowRuns||[]).map(r=>'<div class="item"><strong>'+esc(r.name)+' <span class="adapter-status '+runStatusClass(r.status)+'">'+esc(r.status)+'</span></strong><small>'+esc('Created '+fmtDate(r.createdAt)+' · updated '+fmtDate(r.updatedAt))+'</small>'+(r.error?'<small class="error">'+esc(r.error)+'</small>':'')+'<details><summary>'+esc((r.steps||[]).filter(s=>s.status==='completed').length+'/'+(r.steps||[]).length+' steps')+'</summary><div class="list">'+(r.steps||[]).map(s=>'<div class="item"><strong>'+esc(s.name+' · '+s.status)+'</strong>'+(s.correlationId?'<small>'+uiTraceControls(s.correlationId)+'</small>':'')+(s.error?'<small class="error">'+esc(s.error)+'</small>':'')+'<small>'+esc(short(s.prompt||'',300))+'</small></div>').join('')+'</div></details><div class="row">'+(r.status==='paused'?'<button class="secondary" data-workflow-run-resume="'+attr(r.id)+'"'+disabledAttr('workflows.run')+'>Resume</button>':'')+(['queued','running','paused'].includes(r.status)?'<button class="danger" data-workflow-run-cancel="'+attr(r.id)+'"'+disabledAttr('workflows.run')+'>Cancel</button>':'')+'</div></div>').join('')||uiEmpty('No workflow runs.');bindUiTraceButtons(document.getElementById('workflowRunList'));document.querySelectorAll('[data-workflow-run-cancel]').forEach(b=>b.onclick=()=>safe(async()=>{if(!can('workflows.run')){toast('Permission required: workflows.run');return}await api('/api/workflow-runs/'+encodeURIComponent(b.dataset.workflowRunCancel)+'/cancel',{method:'POST'});toast('Workflow run cancelled');await loadWorkflows()}));document.querySelectorAll('[data-workflow-run-resume]').forEach(b=>b.onclick=()=>safe(async()=>{if(!can('workflows.run')){toast('Permission required: workflows.run');return}await api('/api/jobs/'+encodeURIComponent('workflow-run:'+b.dataset.workflowRunResume)+'/action',{method:'POST',body:JSON.stringify({action:'retry'})});toast('Workflow resumed');await loadWorkflows()}));applyPermissions()}
function runStatusClass(status){if(status==='completed')return'enabled';if(status==='failed'||status==='aborted')return'disabled';return'planned'}
function bindTemplateButtons(){document.querySelectorAll('[data-template-run]').forEach(b=>b.onclick=()=>safe(()=>runTemplate(b.dataset.templateRun)));document.querySelectorAll('[data-template-insert]').forEach(b=>b.onclick=()=>insertTemplate(b.dataset.templateInsert));document.querySelectorAll('[data-template-preview]').forEach(b=>b.onclick=()=>safe(()=>previewTemplate(b.dataset.templatePreview)));document.querySelectorAll('[data-template-edit]').forEach(b=>b.onclick=()=>openTemplateDialog(state.workflowTemplates.find(t=>t.id===b.dataset.templateEdit)));document.querySelectorAll('[data-template-delete]').forEach(b=>b.onclick=()=>safe(async()=>{if(confirm('Delete template?')){await api('/api/templates/'+encodeURIComponent(b.dataset.templateDelete),{method:'DELETE'});await loadWorkflows()}}))}
function bindWorkflowButtons(){document.querySelectorAll('[data-workflow-run]').forEach(b=>b.onclick=()=>safe(()=>runWorkflow(b.dataset.workflowRun)));document.querySelectorAll('[data-workflow-preview]').forEach(b=>b.onclick=()=>safe(()=>previewWorkflow(b.dataset.workflowPreview)));document.querySelectorAll('[data-workflow-edit]').forEach(b=>b.onclick=()=>openWorkflowDialog(state.workflows.find(w=>w.id===b.dataset.workflowEdit)));document.querySelectorAll('[data-workflow-delete]').forEach(b=>b.onclick=()=>safe(async()=>{if(confirm('Delete workflow?')){await api('/api/workflows/'+encodeURIComponent(b.dataset.workflowDelete),{method:'DELETE'});await loadWorkflows()}}))}
function collectVariablesFromPrompt(prompt){return Array.from(new Set(String(prompt||'').match(/\{\{\s*([a-zA-Z_][a-zA-Z0-9_-]*)\s*\}\}/g)?.map(v=>v.replace(/[{}]/g,'').trim())||[]))}
function promptVariables(items){const vars=Array.from(new Set((items||[]).filter(Boolean).flatMap(item=>item.variables?(item.variables||[]).map(v=>v.name):collectVariablesFromPrompt(item.prompt))));if(!vars.length)return{};const raw=prompt('Variables as JSON object for '+vars.join(', '),'{}');return raw?JSON.parse(raw):{}}
async function runTemplate(id){if(!can('workflows.run')){toast('Permission required: workflows.run');return}const t=state.workflowTemplates.find(x=>x.id===id);const variables=promptVariables([t]);const r=await api('/api/templates/'+encodeURIComponent(id)+'/run',{method:'POST',body:JSON.stringify({variables})});toast('Template run started: '+(r.run?.name||id));await loadWorkflows()}
async function runWorkflow(id){if(!can('workflows.run')){toast('Permission required: workflows.run');return}const w=state.workflows.find(x=>x.id===id);const variables=promptVariables((w?.steps||[]).map(step=>step.templateId?state.workflowTemplates.find(t=>t.id===step.templateId)||step:step));const r=await api('/api/workflows/'+encodeURIComponent(id)+'/run',{method:'POST',body:JSON.stringify({variables})});toast('Workflow queued: '+(r.run?.name||id));await loadWorkflows()}
async function previewTemplate(id){const variables=promptVariables([state.workflowTemplates.find(t=>t.id===id)]);const p=await api('/api/templates/'+encodeURIComponent(id)+'/preview',{method:'POST',body:JSON.stringify({variables})});showPreview(p)}
async function previewWorkflow(id){const w=state.workflows.find(x=>x.id===id);const variables=promptVariables((w?.steps||[]).map(step=>step.templateId?state.workflowTemplates.find(t=>t.id===step.templateId)||step:step));const p=await api('/api/workflows/'+encodeURIComponent(id)+'/preview',{method:'POST',body:JSON.stringify({variables})});showPreview(p)}
function showPreview(p){toast((p.prompts||[]).map((step,i)=>(i+1)+'. '+step.name+'\n'+step.prompt).join('\n\n---\n\n').slice(0,3500),{duration:12000})}
function insertTemplate(id){const t=state.workflowTemplates.find(x=>x.id===id);if(!t)return;document.getElementById('promptInput').value=t.prompt;page('chat');document.getElementById('promptInput').focus()}
function openTemplateDialog(t){if(!can('workflows.write')){toast('Permission required: workflows.write');return}adminDialog(t?'Edit template':'Create template','<label>Name<input id="dlgTemplateName" value="'+attr(t?.name||'')+'"></label><label>Scope<select id="dlgTemplateScope"><option value="private">Private</option><option value="shared">Shared</option></select></label><label class="full-span">Description<input id="dlgTemplateDescription" value="'+attr(t?.description||'')+'"></label><label class="full-span">Tags<input id="dlgTemplateTags" value="'+attr((t?.tags||[]).join(', '))+'"></label><label class="full-span">Prompt<textarea id="dlgTemplatePrompt" rows="10">'+esc(t?.prompt||'')+'</textarea></label>',async()=>{const promptText=val('dlgTemplatePrompt');const body={name:val('dlgTemplateName'),description:val('dlgTemplateDescription'),tags:csvToList(val('dlgTemplateTags')),prompt:promptText,variables:collectVariablesFromPrompt(promptText).map(name=>({name,required:true})),scope:val('dlgTemplateScope')};if(t)await api('/api/templates/'+encodeURIComponent(t.id),{method:'PUT',body:JSON.stringify(body)});else await api('/api/templates',{method:'POST',body:JSON.stringify(body)});await loadWorkflows()});document.getElementById('dlgTemplateScope').value=t?.scope||'private'}
function openWorkflowDialog(w){if(!can('workflows.write')){toast('Permission required: workflows.write');return}const example=[{name:'Review',type:'prompt',prompt:'Review {{target}}',sessionMode:'current',target:'local',requiresApproval:false,continueOnError:false}];adminDialog(w?'Edit workflow':'Create workflow','<label>Name<input id="dlgWorkflowName" value="'+attr(w?.name||'')+'"></label><label>Scope<select id="dlgWorkflowScope"><option value="private">Private</option><option value="shared">Shared</option></select></label><label class="full-span">Description<input id="dlgWorkflowDescription" value="'+attr(w?.description||'')+'"></label><label class="full-span">Tags<input id="dlgWorkflowTags" value="'+attr((w?.tags||[]).join(', '))+'"></label><label class="full-span">Steps JSON<textarea id="dlgWorkflowSteps" rows="12">'+esc(JSON.stringify(w?.steps?.length?w.steps:example,null,2))+'</textarea></label>',async()=>{const body={name:val('dlgWorkflowName'),description:val('dlgWorkflowDescription'),tags:csvToList(val('dlgWorkflowTags')),steps:JSON.parse(val('dlgWorkflowSteps')),scope:val('dlgWorkflowScope')};if(w)await api('/api/workflows/'+encodeURIComponent(w.id),{method:'PUT',body:JSON.stringify(body)});else await api('/api/workflows',{method:'POST',body:JSON.stringify(body)});await loadWorkflows()});document.getElementById('dlgWorkflowScope').value=w?.scope||'private'}
document.getElementById('createTemplateBtn').onclick=()=>openTemplateDialog();
document.getElementById('createWorkflowBtn').onclick=()=>openWorkflowDialog();
document.getElementById('reloadWorkflowsBtn').onclick=()=>loadWorkflows();
document.getElementById('reloadWorkflowRunsBtn').onclick=()=>loadWorkflows();
document.getElementById('templateSearch').oninput=renderTemplates;
document.getElementById('workflowSearch').oninput=renderWorkflowList;
document.getElementById('templatePickerBtn').onclick=()=>{if(!can('workflows.read')){toast('Permission required: workflows.read');return}page('workflows')};
