function isWorktreeReviewSelected(id){return (state.worktreeReviewIds||[]).includes(String(id||''))}
function setWorktreeReviewIds(ids){state.worktreeReviewIds=[...new Set<string>((ids||[]).map(String).filter(Boolean))];renderWorktreeReviewCenter()}
function syncWorktreeReviewSelection(){setWorktreeReviewIds(selectedWorktreeIds())}
function worktreeSelectedRecords(){const ids=state.worktreeReviewIds||[];const records=state.worktrees?.records||[];return ids.map(id=>records.find(r=>r.id===id)).filter(Boolean)}
function worktreeStatusClass(status){return status==='added'||status==='modified'||status==='copied'?'enabled':status==='deleted'||status==='renamed'||status==='conflict'?'planned':''}
function worktreeRiskClass(level){return level==='low'?'enabled':level==='medium'?'planned':'disabled'}
function worktreeRiskBadge(level){return '<span class="adapter-status '+worktreeRiskClass(level||'low')+'">'+esc(level||'low')+'</span>'}
function structuredDiffToUnified(file){const header='diff --git a/'+file.path+' b/'+file.path+'\\n--- a/'+file.path+'\\n+++ b/'+file.path;const body=(file.lines||[]).map(line=>{if(line.kind==='hunk')return line.text;if(line.kind==='add')return '+'+(line.text||'');if(line.kind==='delete')return '-' +(line.text||'');if(line.kind==='context')return ' '+(line.text||'');return line.text||''}).filter(Boolean).join('\\n');return header+(body?'\\n'+body:'')}
function worktreeReviewSummaryHtml(records){const ids=state.worktreeReviewIds||[];if(!ids.length)return '<div class="item worktree-review-empty"><strong>Worktree review center</strong><small>Select committed worktrees to compare, preview merge risk, resolve conflicts, or export patches/PR notes.</small></div>';const dirty=records.filter(r=>r.dirty).length;const committed=records.filter(r=>r.commitSha).length;const branches=records.map(r=>r.branchName).join(', ');return '<div class="metric-card worktree-review-summary"><span class="metric-label">Selected</span><span class="metric-value">'+esc(ids.length)+'</span><span class="metric-meta truncate-cell" title="'+attr(branches)+'">'+esc(short(branches||'-',180))+'</span></div><div class="metric-card"><span class="metric-label">Committed</span><span class="metric-value">'+esc(committed)+'</span><span class="metric-meta">'+esc(dirty?dirty+' dirty':'clean selection')+'</span></div>'}
function renderWorktreeReviewCenter(){const target=document.getElementById('worktreeReviewCenter');if(!target)return;const records=worktreeSelectedRecords();const ids=state.worktreeReviewIds||[];target.innerHTML='<div class="metrics-grid worktree-review-grid">'+worktreeReviewSummaryHtml(records)+'</div>'+(ids.length?'<div class="row worktree-review-actions"><button type="button" id="reviewCenterPreviewBtn" class="secondary">Resolver preview</button><button type="button" id="reviewCenterCompareBtn" class="secondary">Side-by-side diffs</button><button type="button" id="reviewCenterExportBtn" class="secondary">Export patch + PR notes</button><button type="button" id="reviewCenterClearBtn" class="secondary">Clear selection</button></div>':'');const preview=document.getElementById('reviewCenterPreviewBtn');if(preview)preview.onclick=()=>safe(()=>openWorktreeResolverPreview(ids));const compare=document.getElementById('reviewCenterCompareBtn');if(compare)compare.onclick=()=>safe(()=>openWorktreeCompareDialog(ids));const exp=document.getElementById('reviewCenterExportBtn');if(exp)exp.onclick=()=>safe(()=>exportWorktreeBundle(ids));const clear=document.getElementById('reviewCenterClearBtn');if(clear)clear.onclick=()=>{setWorktreeReviewIds([]);document.querySelectorAll('[data-worktree-select]').forEach(el=>el.checked=false)}}
function bindWorktreeReviewCenter(){const known=new Set((state.worktrees?.records||[]).map(r=>r.id));state.worktreeReviewIds=(state.worktreeReviewIds||[]).filter(id=>known.has(id));document.querySelectorAll('[data-worktree-select]').forEach(el=>{el.onchange=()=>syncWorktreeReviewSelection()});renderWorktreeReviewCenter()}
function worktreeRiskSummaryHtml(preview){const risk=preview.riskSummary||{};return '<div class="metrics-grid worktree-risk-grid"><div class="metric-card"><span class="metric-label">Risk</span><span class="metric-value">'+worktreeRiskBadge(risk.label||'low')+'</span><span class="metric-meta">'+esc((risk.riskyFiles||0)+' risky of '+(risk.totalFiles||0)+' files')+'</span></div><div class="metric-card"><span class="metric-label">Blocked / High / Medium</span><span class="metric-value">'+esc((risk.blocked||0)+' / '+(risk.high||0)+' / '+(risk.medium||0))+'</span><span class="metric-meta">'+esc((preview.warnings||[]).length+' warning(s)')+'</span></div></div>'}
function worktreePreviewWarningsHtml(preview){return (preview.warnings||[]).length?'<div class="peer-warning full-span"><strong>Warnings</strong>'+(preview.warnings||[]).map(w=>'<small>'+esc(w)+'</small>').join('')+'</div>':'<div class="item"><strong>Ready to integrate</strong><small>No warnings reported by the preview.</small></div>'}
function worktreeRiskDetail(item){const ranges=(item.changedRanges||[]).map(source=>source.branchName+': '+(source.ranges||[]).map(r=>r.start===r.end?String(r.start):r.start+'-'+r.end).join(', ')).join('\\n');return [(item.riskReasons||[]).join('\\n'),ranges?'Changed ranges:\\n'+ranges:''].filter(Boolean).join('\\n\\n')}
function worktreeConflictReviewWizardTable(preview){const items=preview.conflictReview||[];if(!items.length)return uiEmpty('No changed files in selected worktrees.');return '<div class="data-table-wrap"><table class="data-table worktree-conflict-table"><thead><tr><th>Risk</th><th>File</th><th>Status</th><th>Sources</th><th>Resolution</th><th>Recommendation</th></tr></thead><tbody>'+items.map(item=>{const sourceNames=(item.sourceWorktrees||[]).map(source=>worktreeSourceName(source,preview)).join(', ');return '<tr>'+sessionCell('Risk','<span title="'+attr(worktreeRiskDetail(item))+'">'+worktreeRiskBadge(item.riskLevel||'low')+'</span>','status-cell')+sessionCell('File','<span class="truncate-cell" title="'+attr(item.path)+'">'+esc(short(item.path,180))+'</span>'+worktreeVersionPreviews(item),'primary-cell')+sessionCell('Status','<span class="adapter-status '+worktreeStatusClass(item.status)+'">'+esc(item.status||'-')+'</span>')+sessionCell('Sources','<span class="truncate-cell" title="'+attr(sourceNames)+'">'+esc(short(sourceNames||'-',160))+'</span>')+sessionCell('Resolution',worktreeResolutionControls(item,preview),'actions-cell')+sessionCell('Recommendation','<span class="truncate-cell" title="'+attr(item.recommendation||'-')+'">'+esc(short(item.recommendation||'-',220))+'</span>')+'</tr>'}).join('')+'</tbody></table></div>'}
function worktreeResolverPreviewHtml(preview){return '<div class="full-span worktree-resolver-preview">'+worktreeRiskSummaryHtml(preview)+worktreePreviewWarningsHtml(preview)+worktreePreviewSourcesTable(preview)+'<h3 class="table-section-title">Guided conflict resolver</h3>'+worktreeConflictReviewWizardTable(preview)+'<small>Save resolutions before integrating. Manual content is applied only to files that Git reports as conflicted during integration.</small></div>'}
async function openWorktreeResolverPreview(ids){const p=await api('/api/sessions/worktrees/integrate/preview',{method:'POST',body:JSON.stringify({ids})});const risky=(p.conflictReview||[]).some(item=>(item.riskLevel||'low')!=='low');adminDialog('Integration preview',worktreeResolverPreviewHtml(p),async()=>{state.worktreeConflictResolutions=collectWorktreeResolutions(document.getElementById('adminDialog'));toast(state.worktreeConflictResolutions.length+' conflict resolution(s) saved')},{submitText:risky?'Save resolutions':'Close',reloadAccess:false});bindUiCopyButtons(document.getElementById('adminDialog'))}
function worktreeCompareFileTable(compare){const rows=[];(compare.diffs||[]).forEach(diff=>{(diff.structuredFiles||[]).forEach(file=>rows.push({branch:diff.record?.branchName||diff.record?.id||'-',path:file.path,status:file.status,additions:file.additions,deletions:file.deletions,body:structuredDiffToUnified(file)}))});if(!rows.length)return uiEmpty('No diffs available.');return rows.map(row=>'<details class="worktree-diff-file"><summary>'+esc(row.path)+' <small>'+esc(row.branch)+' · '+row.status+' · +'+row.additions+' / -'+row.deletions+'</small></summary>'+splitDiff(row.body)+'</details>').join('')}
async function openWorktreeCompareDialog(ids){const compare=await api('/api/sessions/worktrees/compare',{method:'POST',body:JSON.stringify({ids})});adminDialog('Side-by-side worktree diffs','<div class="full-span">'+worktreeRiskSummaryHtml(compare.preview||{})+worktreeCompareFileTable(compare)+'</div>',async()=>{}, {submitText:'Close',reloadAccess:false})}
async function exportWorktreeBundle(ids){const patch=await api('/api/sessions/worktrees/integrate/patch',{method:'POST',body:JSON.stringify({ids})});downloadTextFile(patch.fileName||'nordrelay-worktree-patches.patch',patch.content||'','text/x-patch');if(patch.summary)downloadTextFile(patch.summaryFileName||'nordrelay-worktree-summary.md',patch.summary,'text/markdown');if(patch.riskReportJson)downloadTextFile(patch.riskReportFileName||'nordrelay-worktree-risk.json',patch.riskReportJson,'application/json');const commands=(patch.prCommands||[]).join('\\n');const body='<div class="full-span"><p>Patch, summary, and risk report were downloaded. Use these commands after applying the patch in a local checkout.</p><label>PR title<input readonly value="'+attr(patch.prTitle||'')+'"></label><label>PR body<textarea readonly rows="6">'+esc(patch.prBody||'')+'</textarea></label><label>Commands<textarea readonly rows="5">'+esc(commands||'-')+'</textarea></label></div>';adminDialog('Patch and PR export',body,async()=>{if(commands)copyText(commands,'PR commands copied')},{submitText:'Copy commands',reloadAccess:false});toast('Patch, summary, and risk report exported')}
const compareWorktreesBtn=document.getElementById('compareWorktreesBtn');if(compareWorktreesBtn)compareWorktreesBtn.onclick=()=>safe(async()=>{const ids=selectedWorktreeIds();if(!ids.length){toast('Select committed worktrees first');return}await openWorktreeCompareDialog(ids)});
