// Generated by scripts/generate-web-api-routes.mjs from src/web/web-api-contract.ts.
// Do not edit by hand.

export type WebApiMethod = "GET" | "POST" | "PATCH" | "PUT" | "DELETE";
export type WebApiQueryValue = string | number | boolean | null | undefined;
export type WebApiQuery = Record<string, WebApiQueryValue | WebApiQueryValue[]>;

export type WebApiStaticPath =
  | "/api/abort"
  | "/api/active-sessions"
  | "/api/activity"
  | "/api/adapters/conformance"
  | "/api/adapters/health"
  | "/api/agent"
  | "/api/agent-update"
  | "/api/agent-updates"
  | "/api/artifacts"
  | "/api/artifacts/bulk"
  | "/api/artifacts/cleanup/preview"
  | "/api/artifacts/cleanup/run"
  | "/api/artifacts/diff"
  | "/api/artifacts/file"
  | "/api/artifacts/preview"
  | "/api/artifacts/usage"
  | "/api/artifacts/zip"
  | "/api/audit"
  | "/api/auth/login"
  | "/api/auth/logout"
  | "/api/auth/me"
  | "/api/auth/status"
  | "/api/bootstrap"
  | "/api/chat/history"
  | "/api/chat/mirror"
  | "/api/control-options"
  | "/api/dashboard/logout"
  | "/api/diagnostics"
  | "/api/diagnostics/bundle"
  | "/api/discord-channels"
  | "/api/groups"
  | "/api/handback"
  | "/api/health"
  | "/api/jobs"
  | "/api/locks"
  | "/api/logs"
  | "/api/logs/clear"
  | "/api/metrics"
  | "/api/models"
  | "/api/peers"
  | "/api/peers/discover"
  | "/api/peers/discovery-jobs"
  | "/api/peers/global-sessions"
  | "/api/peers/identity/backup"
  | "/api/peers/identity/restore"
  | "/api/peers/invite"
  | "/api/peers/pair"
  | "/api/peers/probe"
  | "/api/peers/relay"
  | "/api/permissions"
  | "/api/profile"
  | "/api/profile/logout-other-sessions"
  | "/api/profile/password"
  | "/api/progress"
  | "/api/prompt"
  | "/api/prompt/upload"
  | "/api/queue"
  | "/api/queue/plans"
  | "/api/retry"
  | "/api/runtime/restart"
  | "/api/session/fast"
  | "/api/session/launch"
  | "/api/session/model"
  | "/api/session/reasoning"
  | "/api/sessions"
  | "/api/sessions/attach"
  | "/api/sessions/detail"
  | "/api/sessions/new"
  | "/api/sessions/switch"
  | "/api/sessions/worktrees"
  | "/api/sessions/worktrees/cleanup"
  | "/api/sessions/worktrees/fork"
  | "/api/sessions/worktrees/integrate"
  | "/api/sessions/worktrees/integrate/preview"
  | "/api/settings"
  | "/api/settings/wizard/test"
  | "/api/slack-channels"
  | "/api/snapshot"
  | "/api/stop"
  | "/api/sync"
  | "/api/tasks"
  | "/api/telegram-chats"
  | "/api/templates"
  | "/api/trace"
  | "/api/update"
  | "/api/users"
  | "/api/version"
  | "/api/workflows";

export type WebApiDynamicPath =
  | `/api/agent-update/${string}/cancel`
  | `/api/agent-update/${string}/input`
  | `/api/agent-update/${string}/log`
  | `/api/discord-channels/${string}`
  | `/api/groups/${string}`
  | `/api/jobs/${string}/action`
  | `/api/jobs/${string}/log`
  | `/api/peers/${string}`
  | `/api/peers/${string}/events`
  | `/api/peers/${string}/health`
  | `/api/peers/${string}/proxy`
  | `/api/peers/${string}/repin`
  | `/api/peers/${string}/rotate`
  | `/api/peers/discovery-jobs/${string}`
  | `/api/peers/discovery-jobs/${string}/cancel`
  | `/api/peers/discovery-jobs/${string}/log`
  | `/api/peers/invitations/${string}`
  | `/api/queue/plans/${string}`
  | `/api/queue/plans/${string}/approve`
  | `/api/queue/plans/${string}/enqueue`
  | `/api/queue/plans/${string}/move`
  | `/api/sessions/worktrees/${string}`
  | `/api/sessions/worktrees/${string}/commit`
  | `/api/sessions/worktrees/${string}/diff`
  | `/api/sessions/worktrees/${string}/update`
  | `/api/slack-channels/${string}`
  | `/api/telegram-chats/${string}`
  | `/api/templates/${string}`
  | `/api/templates/${string}/preview`
  | `/api/templates/${string}/run`
  | `/api/users/${string}`
  | `/api/users/${string}/discord`
  | `/api/users/${string}/discord/${string}`
  | `/api/users/${string}/password`
  | `/api/users/${string}/sessions`
  | `/api/users/${string}/sessions/${string}`
  | `/api/users/${string}/slack`
  | `/api/users/${string}/slack/${string}`
  | `/api/users/${string}/telegram`
  | `/api/users/${string}/telegram/${string}`
  | `/api/workflow-runs/${string}`
  | `/api/workflow-runs/${string}/cancel`
  | `/api/workflow-runs/${string}/rerun-failed`
  | `/api/workflows/${string}`
  | `/api/workflows/${string}/preview`
  | `/api/workflows/${string}/run`;

export type WebApiKnownPath = WebApiStaticPath | WebApiDynamicPath;
export type WebApiPath = WebApiKnownPath | (string & {});

export interface WebApiClientOptions<P extends WebApiPath = WebApiPath> {
  method?: WebApiMethod;
  query?: WebApiQuery;
  headers?: Record<string, string>;
  body?: WebApiRequestBody<P> | string | FormData | Blob | ArrayBuffer | null;
}

export type WebApiRequestBody<P extends WebApiPath> =
  P extends "/api/prompt" ? { text: string; correlationId?: string } :
  P extends "/api/prompt/upload" ? { text?: string; correlationId?: string; files: Array<{ name: string; mimeType?: string; dataBase64: string }> } :
  P extends "/api/agent" ? { agentId: string } :
  P extends "/api/agent-update" ? { agentId: string; operation?: "update" | "install" } :
  P extends "/api/sessions/new" ? { agentId?: string; workspace?: string; workspaceMode?: "shared" | "worktree" | "attached"; model?: string; reasoningEffort?: string; launchProfileId?: string; fastMode?: boolean } :
  P extends "/api/sessions/worktrees/fork" ? { includeUncommitted?: boolean } :
  P extends "/api/sessions/worktrees/integrate" ? { ids: string[]; resolutions?: Array<{ path: string; choice: "auto" | "ours" | "theirs" | "both" | "manual"; sourceWorktreeId?: string; content?: string }> } :
  P extends "/api/sessions/worktrees/integrate/preview" ? { ids: string[] } :
  P extends "/api/sessions/worktrees/cleanup" ? Record<string, never> :
  P extends `/api/sessions/worktrees/${string}/commit` ? { message?: string } :
  P extends `/api/sessions/worktrees/${string}/update` ? Record<string, never> :
  P extends `/api/sessions/worktrees/${string}` ? { force?: boolean } :
  P extends "/api/sessions/switch" | "/api/sessions/attach" ? { threadId: string } :
  P extends "/api/session/model" ? { model: string } :
  P extends "/api/session/reasoning" ? { reasoning: string } :
  P extends "/api/session/fast" ? { enabled: boolean } :
  P extends "/api/session/launch" ? { profileId: string; apply?: boolean } :
  P extends "/api/queue" ? { action: string; id?: string } :
  P extends "/api/peers/relay" ? { action: "cancel"; peerId: string; id: string } | { action: "retry"; peerId?: string; id?: string } | { action: "drain-expired" } :
  P extends "/api/settings" ? { settings: Record<string, string | null | undefined> } :
  P extends "/api/templates" | `/api/templates/${string}` ? Record<string, unknown> :
  P extends `/api/templates/${string}/run` | `/api/templates/${string}/preview` ? { variables?: Record<string, string> } :
  P extends "/api/workflows" | `/api/workflows/${string}` ? Record<string, unknown> :
  P extends `/api/workflows/${string}/run` | `/api/workflows/${string}/preview` ? { variables?: Record<string, string> } :
  P extends `/api/workflow-runs/${string}/cancel` | `/api/workflow-runs/${string}/rerun-failed` ? Record<string, never> :
  Record<string, unknown>;

export type WebApiClientResponse<P extends WebApiPath> = any;
