// Generated by scripts/generate-web-api-routes.mjs from src/web/web-api-contract.ts.
// Do not edit by hand.

import type {
  WebApiClientResponse as ServerWebApiClientResponse,
  WebApiMethod as ServerWebApiMethod,
  WebApiPath as ServerWebApiPath,
  WebApiQuery as ServerWebApiQuery,
  WebApiQueryValue as ServerWebApiQueryValue,
  WebApiRequestBody as ServerWebApiRequestBody,
} from "../../../web-api-types.js";

export type WebApiMethod = ServerWebApiMethod;
export type WebApiQueryValue = ServerWebApiQueryValue;
export type WebApiQuery = ServerWebApiQuery;

export type WebApiStaticPath =
  | "/api/abort"
  | "/api/active-sessions"
  | "/api/activity"
  | "/api/adapters/conformance"
  | "/api/adapters/health"
  | "/api/agent"
  | "/api/agent-update"
  | "/api/agent-updates"
  | "/api/artifacts"
  | "/api/artifacts/bulk"
  | "/api/artifacts/cleanup/preview"
  | "/api/artifacts/cleanup/run"
  | "/api/artifacts/diff"
  | "/api/artifacts/file"
  | "/api/artifacts/preview"
  | "/api/artifacts/usage"
  | "/api/artifacts/zip"
  | "/api/audit"
  | "/api/auth/login"
  | "/api/auth/logout"
  | "/api/auth/me"
  | "/api/auth/status"
  | "/api/bootstrap"
  | "/api/chat/history"
  | "/api/chat/mirror"
  | "/api/control-options"
  | "/api/dashboard/logout"
  | "/api/diagnostics"
  | "/api/diagnostics/bundle"
  | "/api/discord-channels"
  | "/api/groups"
  | "/api/handback"
  | "/api/health"
  | "/api/jobs"
  | "/api/locks"
  | "/api/logs"
  | "/api/logs/clear"
  | "/api/metrics"
  | "/api/models"
  | "/api/peers"
  | "/api/peers/discover"
  | "/api/peers/discovery-jobs"
  | "/api/peers/global-sessions"
  | "/api/peers/identity/backup"
  | "/api/peers/identity/restore"
  | "/api/peers/invite"
  | "/api/peers/pair"
  | "/api/peers/probe"
  | "/api/peers/relay"
  | "/api/permissions"
  | "/api/profile"
  | "/api/profile/logout-other-sessions"
  | "/api/profile/password"
  | "/api/progress"
  | "/api/prompt"
  | "/api/prompt/upload"
  | "/api/queue"
  | "/api/queue/plans"
  | "/api/retry"
  | "/api/runtime/restart"
  | "/api/session/fast"
  | "/api/session/launch"
  | "/api/session/model"
  | "/api/session/reasoning"
  | "/api/sessions"
  | "/api/sessions/attach"
  | "/api/sessions/detail"
  | "/api/sessions/new"
  | "/api/sessions/switch"
  | "/api/sessions/worktrees"
  | "/api/sessions/worktrees/cleanup"
  | "/api/sessions/worktrees/fork"
  | "/api/sessions/worktrees/integrate"
  | "/api/sessions/worktrees/integrate/preview"
  | "/api/settings"
  | "/api/settings/wizard/test"
  | "/api/slack-channels"
  | "/api/snapshot"
  | "/api/stop"
  | "/api/sync"
  | "/api/tasks"
  | "/api/telegram-chats"
  | "/api/templates"
  | "/api/templates/import"
  | "/api/trace"
  | "/api/update"
  | "/api/users"
  | "/api/version"
  | "/api/workflows"
  | "/api/workflows/import";

export type WebApiDynamicPath =
  | `/api/agent-update/${string}/cancel`
  | `/api/agent-update/${string}/input`
  | `/api/agent-update/${string}/log`
  | `/api/discord-channels/${string}`
  | `/api/groups/${string}`
  | `/api/jobs/${string}/action`
  | `/api/jobs/${string}/log`
  | `/api/peers/${string}`
  | `/api/peers/${string}/events`
  | `/api/peers/${string}/health`
  | `/api/peers/${string}/proxy`
  | `/api/peers/${string}/repin`
  | `/api/peers/${string}/rotate`
  | `/api/peers/discovery-jobs/${string}`
  | `/api/peers/discovery-jobs/${string}/cancel`
  | `/api/peers/discovery-jobs/${string}/log`
  | `/api/peers/invitations/${string}`
  | `/api/queue/plans/${string}`
  | `/api/queue/plans/${string}/approve`
  | `/api/queue/plans/${string}/enqueue`
  | `/api/queue/plans/${string}/move`
  | `/api/sessions/worktrees/${string}`
  | `/api/sessions/worktrees/${string}/commit`
  | `/api/sessions/worktrees/${string}/diff`
  | `/api/sessions/worktrees/${string}/update`
  | `/api/slack-channels/${string}`
  | `/api/telegram-chats/${string}`
  | `/api/templates/${string}`
  | `/api/templates/${string}/diff`
  | `/api/templates/${string}/export`
  | `/api/templates/${string}/preview`
  | `/api/templates/${string}/run`
  | `/api/templates/${string}/versions`
  | `/api/templates/${string}/versions/${string}/export`
  | `/api/templates/${string}/versions/${string}/preview`
  | `/api/templates/${string}/versions/${string}/rollback`
  | `/api/templates/${string}/versions/${string}/run`
  | `/api/users/${string}`
  | `/api/users/${string}/discord`
  | `/api/users/${string}/discord/${string}`
  | `/api/users/${string}/password`
  | `/api/users/${string}/sessions`
  | `/api/users/${string}/sessions/${string}`
  | `/api/users/${string}/slack`
  | `/api/users/${string}/slack/${string}`
  | `/api/users/${string}/telegram`
  | `/api/users/${string}/telegram/${string}`
  | `/api/workflow-runs/${string}`
  | `/api/workflow-runs/${string}/cancel`
  | `/api/workflow-runs/${string}/rerun-failed`
  | `/api/workflows/${string}`
  | `/api/workflows/${string}/diff`
  | `/api/workflows/${string}/export`
  | `/api/workflows/${string}/preview`
  | `/api/workflows/${string}/run`
  | `/api/workflows/${string}/versions`
  | `/api/workflows/${string}/versions/${string}/export`
  | `/api/workflows/${string}/versions/${string}/preview`
  | `/api/workflows/${string}/versions/${string}/rollback`
  | `/api/workflows/${string}/versions/${string}/run`;

export type WebApiKnownPath = WebApiStaticPath | WebApiDynamicPath;
export type WebApiPath = WebApiKnownPath | (string & {});

export interface WebApiClientOptions<P extends WebApiPath = WebApiPath> {
  method?: WebApiMethod;
  query?: WebApiQuery;
  headers?: Record<string, string>;
  body?: WebApiRequestBody<P> | string | FormData | Blob | ArrayBuffer | null;
}

export type WebApiRequestBody<P extends WebApiPath> =
  P extends ServerWebApiPath ? ServerWebApiRequestBody<P> : Record<string, unknown>;

export type WebApiClientResponse<P extends WebApiPath> =
  P extends ServerWebApiPath ? ServerWebApiClientResponse<P> : unknown;
