import type { Bot, Context } from "grammy";

export async function registerCommands(bot: Bot<Context>): Promise<void> {
  await bot.api.setMyCommands([
    { command: "start", description: "Welcome & status" },
    { command: "help", description: "Command reference" },
    { command: "link", description: "Link Telegram to NordRelay user" },
    { command: "whoami", description: "Show your NordRelay user" },
    { command: "register_chat", description: "Admin: enable this group chat" },
    { command: "channels", description: "Messaging adapter status" },
    { command: "agents", description: "Agent adapter status" },
    { command: "agent", description: "Select agent" },
    { command: "new", description: "Start a new thread" },
    { command: "session", description: "Current thread details" },
    { command: "sessions", description: "Browse & switch threads" },
    { command: "sync", description: "Sync active session from CLI state" },
    { command: "pinned", description: "Show pinned threads" },
    { command: "pin", description: "Pin current or given thread" },
    { command: "unpin", description: "Unpin current or given thread" },
    { command: "retry", description: "Resend the last prompt" },
    { command: "queue", description: "Show queued prompts" },
    { command: "cancel", description: "Cancel a queued prompt" },
    { command: "clearqueue", description: "Clear queued prompts" },
    { command: "artifacts", description: "List or resend generated files" },
    { command: "workspaces", description: "List allowed workspaces" },
    { command: "abort", description: "Cancel current operation" },
    { command: "stop", description: "Cancel current operation" },
    { command: "launch_profiles", description: "Select launch profile" },
    { command: "fast", description: "Toggle fast mode" },
    { command: "model", description: "View & change model" },
    { command: "reasoning", description: "Set reasoning effort" },
    { command: "mirror", description: "Control CLI mirroring" },
    { command: "notify", description: "Control notifications" },
    { command: "auth", description: "Check auth status" },
    { command: "login", description: "Start authentication" },
    { command: "logout", description: "Sign out" },
    { command: "voice", description: "Voice transcription status" },
    { command: "tasks", description: "Current turn progress" },
    { command: "progress", description: "Current turn progress" },
    { command: "activity", description: "Thread activity timeline" },
    { command: "audit", description: "Admin: recent audit events" },
    { command: "status", description: "Connector runtime status" },
    { command: "health", description: "Connector health report" },
    { command: "version", description: "Connector version" },
    { command: "logs", description: "Admin: show connector logs" },
    { command: "diagnostics", description: "Admin: connector diagnostics" },
    { command: "support", description: "Admin: export diagnostics bundle" },
    { command: "lock", description: "Lock session writes to you" },
    { command: "unlock", description: "Release session write lock" },
    { command: "locks", description: "List session write locks" },
    { command: "restart", description: "Admin: restart connector" },
    { command: "update", description: "Admin: update connector or agents" },
    { command: "handback", description: "Hand session back to CLI" },
    { command: "attach", description: "Bind a session to this topic" },
    { command: "switch", description: "Switch to a thread by ID" },
  ]);
}
